// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, John Gough, QUT 2005-2014
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.5.2
// Machine:  VDI-VL17-059
// DateTime: 16/05/2017 6:54:20 PM
// UserName: n9004548
// Input file <parser.y - 16/05/2017 6:53:00 PM>

// options: conflicts lines gplex conflicts

using System;
using System.Collections.Generic;
using System.CodeDom.Compiler;
using System.Globalization;
using System.Text;
using QUT.Gppg;
using System.Collections;
using IFN660_Java_ECMAScript.AST;

namespace IFN660_Java_ECMAScript
{
public enum Tokens {error=128,EOF=129,NUMBER=130,IDENTIFIER=131,ABSTRACT=132,
    CONTINUE=133,FOR=134,NEW=135,SWITCH=136,ASSERT=137,DEFAULT=138,
    IF=139,PACKAGE=140,SYNCHRONIZED=141,BOOLEAN=142,DO=143,GOTO=144,
    PRIVATE=145,THIS=146,BREAK=147,DOUBLE=148,IMPLEMENTS=149,PROTECTED=150,
    THROW=151,BYTE=152,ELSE=153,IMPORT=154,PUBLIC=155,THROWS=156,
    CASE=157,ENUM=158,INSTANCEOF=159,RETURN=160,TRANSIENT=161,CATCH=162,
    EXTENDS=163,INT=164,SHORT=165,TRY=166,CHAR=167,FINAL=168,
    INTERFACE=169,STATIC=170,VOID=171,CLASS=172,FINALLY=173,LONG=174,
    STRICTFP=175,VOLATILE=176,CONST=177,FLOAT=178,NATIVE=179,SUPER=180,
    WHILE=181,IntegerLiteral=182,FloatingPointLiteral=183,BooleanLiteral=184,CharacterLiteral=185,StringLiteral=186,
    NullLiteral=187,ELLIPSIS=188,DOUBLE_COLON=189,EQUAL=190,GREATER_OR_EQUAL=191,LESS_THAN_OR_EQUAL=192,
    NOT_EQUAL=193,ARROW=194,LOGICAL_AND=195,LOGICAL_OR=196,INCREMENT=197,DECREMENT=198,
    LEFT_SHIFT=199,SIGNED_RIGHT_SHIFT=200,UNSIGNED_RIGHT_SHIFT=201,ADDITION_ASSIGNMENT=202,SUBTRACTION_ASSIGNMENT=203,MULTIPLICATION_ASSIGNMENT=204,
    DIVISION_ASSIGNMENT=205,MODULUS_ASSIGNMENT=206,BITWISE_AND_ASSIGNMENT=207,BITWISE_OR_ASSIGNMENT=208,BITWISE_XOR_ASSIGNMENT=209,LEFT_SHIFT_ASSIGNMENT=210,
    UNSIGNED_RIGHT_SHIFT_ASSIGNMENT=211,SIGNED_RIGHT_SHIFT_ASSIGNMENT=212};

public struct ValueType
#line 11 "parser.y"
{
    public long num;
	public double floatnum;
	public bool boolval;
	public char charval;
    public string name;
	public Statement stmt;
	public List<Statement> stmts;
	public Expression expr;
	public AST.Type type;
	public Modifier modf;
	public List<Modifier> modfs;
	public ArrayList arrlst;
	public List<string> strlst;
}
#line default
// Abstract base class for GPLEX scanners
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public abstract class ScanBase : AbstractScanner<ValueType,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

// Utility class for encapsulating token information
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public class ScanObj {
  public int token;
  public ValueType yylval;
  public LexLocation yylloc;
  public ScanObj( int t, ValueType val, LexLocation loc ) {
    this.token = t; this.yylval = val; this.yylloc = loc;
  }
}

[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public class Parser: ShiftReduceParser<ValueType, LexLocation>
{
  // Verbatim content from parser.y - 16/05/2017 6:53:00 PM
#line 7 "parser.y"
public static Statement root;
#line default
  // End verbatim content from parser.y - 16/05/2017 6:53:00 PM

#pragma warning disable 649
  private static Dictionary<int, string> aliases;
#pragma warning restore 649
  private static Rule[] rules = new Rule[216];
  private static State[] states = new State[295];
  private static string[] nonTerms = new string[] {
      "Literal", "StatementExpression", "Assignment", "LeftHandSide", "ExpressionName", 
      "TypeParameters_opt", "Superclass_opt", "Superinterfaces_opt", "AssignmentExpression", 
      "PrimaryNoNewArray", "Expression", "LambdaExpression", "LambdaBody", "ConditionalExpression", 
      "ConditionalOrExpression", "ConditionalAndExpression", "InclusiveOrExpression", 
      "ExclusiveOrExpression", "AndExpression", "EqualityExpression", "RelationalExpression", 
      "ShiftExpression", "AdditiveExpression", "MultiplicativeExpression", "UnaryExpression", 
      "PostfixExpression", "Primary", "PreIncrementExpression", "PreDecrementExpression", 
      "UnaryExpressionNotPlusMinus", "CastExpression", "PostIncrementExpression", 
      "PostDecrementExpression", "Statement", "CompilationUnit", "TypeDeclaration", 
      "ClassDeclaration", "NormalClassDeclaration", "ClassBodyDeclaration", "ExpressionStatement", 
      "StatementWithoutTrailingSubstatement", "LocalVariableDeclaration", "LocalVariableDeclarationStatement", 
      "BlockStatement", "Throws_opt", "ClassMemberDeclaration", "MethodDeclaration", 
      "FormalParameter", "PackageDeclaration_opt", "Block", "MethodBody", "StatementNoShortIf", 
      "IfThenElseStatementNoShortIf", "IfThenStatement", "IfThenElseStatement", 
      "WhileStatement", "TryStatement", "Catches", "Catches_opt", "CatchClause", 
      "Finally", "DoStatement", "ThrowStatement", "SynchronizedStatement", "SwitchStatement", 
      "AssertStatement", "LabeledStatement", "BreakStatement", "ContinueStatement", 
      "ReturnStatement", "ImportDeclaration", "SingleTypeImportDeclaration", 
      "TypeImportOnDemandDeclaration", "TypeDeclarations", "ClassBody", "ClassBodyDeclarations", 
      "BlockStatements", "BlockStatements_Opt", "FormalParameters", "FormalParameterList", 
      "FormalParameterList_Opt", "ImportDeclarations", "Result", "FloatingPointType", 
      "IntegralType", "NumericType", "UnannType", "UnannPrimitiveType", "UnannReferenceType", 
      "UnannArrayType", "UnannTypeVariable", "ReferenceType", "PrimitiveType", 
      "ClassModifier", "MethodModifier", "VariableModifier", "ClassModifiers", 
      "MethodModifiers", "VariableModifiers", "VariableDeclaratorId", "VariableDeclarator", 
      "MethodHeader", "MethodDeclarator", "VariableDeclaratorList", "Identifier_opt", 
      "Expression_opt", "TypeName", "PackageOrTypeName", "Program", "$accept", 
      "Empty", "Dims_Opt", "Dims", "TypeVariable", "AssignmentOperator", "LambdaParameters", 
      "AdditionalBounds", "AdditionalBound", "ConstantExpression", };

  static Parser() {
    states[0] = new State(-5,new int[]{-109,1,-35,3,-49,4});
    states[1] = new State(new int[]{129,2});
    states[2] = new State(-1);
    states[3] = new State(-2);
    states[4] = new State(new int[]{154,284,172,-8,155,-8,150,-8,145,-8,132,-8,170,-8,168,-8,175,-8,129,-8},new int[]{-82,5,-71,294,-72,283,-73,293});
    states[5] = new State(new int[]{154,284,172,-18,155,-18,150,-18,145,-18,132,-18,170,-18,168,-18,175,-18,129,-18},new int[]{-74,6,-71,282,-72,283,-73,293});
    states[6] = new State(new int[]{129,-4,172,-23,155,-23,150,-23,145,-23,132,-23,170,-23,168,-23,175,-23},new int[]{-36,7,-37,8,-38,9,-97,10});
    states[7] = new State(-17);
    states[8] = new State(-19);
    states[9] = new State(-20);
    states[10] = new State(new int[]{172,11,155,275,150,276,145,277,132,278,170,279,168,280,175,281},new int[]{-94,274});
    states[11] = new State(new int[]{131,12});
    states[12] = new State(-31,new int[]{-6,13});
    states[13] = new State(-32,new int[]{-7,14});
    states[14] = new State(-33,new int[]{-8,15});
    states[15] = new State(new int[]{123,17},new int[]{-75,16});
    states[16] = new State(-21);
    states[17] = new State(-36,new int[]{-76,18});
    states[18] = new State(new int[]{125,19,171,-41,131,-41,152,-41,165,-41,164,-41,174,-41,167,-41,178,-41,148,-41,142,-41,155,-41,170,-41},new int[]{-39,20,-46,21,-47,22,-98,23});
    states[19] = new State(-34);
    states[20] = new State(-35);
    states[21] = new State(-37);
    states[22] = new State(-38);
    states[23] = new State(new int[]{171,270,131,267,152,128,165,129,164,130,174,131,167,132,178,134,148,135,142,245,155,272,170,273},new int[]{-102,24,-95,249,-83,250,-87,271,-89,46,-90,47,-91,48,-88,243,-86,244,-85,127,-84,133});
    states[24] = new State(new int[]{123,27,59,248},new int[]{-51,25,-50,26});
    states[25] = new State(-39);
    states[26] = new State(-81);
    states[27] = new State(new int[]{131,50,152,128,165,129,164,130,174,131,167,132,178,134,148,135,142,245,123,27,147,174,143,179,133,187,160,191,151,196,141,200,136,206,137,211,139,218,181,228,125,-85},new int[]{-78,28,-77,30,-44,247,-43,32,-42,33,-87,35,-89,46,-90,47,-91,48,-88,243,-86,244,-85,127,-84,133,-34,246,-41,53,-40,54,-2,55,-3,57,-4,58,-5,170,-50,172,-68,173,-62,178,-69,186,-70,190,-63,195,-64,199,-65,205,-66,210,-54,217,-55,226,-56,227,-67,233});
    states[28] = new State(new int[]{125,29});
    states[29] = new State(-83);
    states[30] = new State(new int[]{131,50,152,128,165,129,164,130,174,131,167,132,178,134,148,135,142,245,123,27,147,174,143,179,133,187,160,191,151,196,141,200,136,206,137,211,139,218,181,228,125,-84},new int[]{-44,31,-43,32,-42,33,-87,35,-89,46,-90,47,-91,48,-88,243,-86,244,-85,127,-84,133,-34,246,-41,53,-40,54,-2,55,-3,57,-4,58,-5,170,-50,172,-68,173,-62,178,-69,186,-70,190,-63,195,-64,199,-65,205,-66,210,-54,217,-55,226,-56,227,-67,233});
    states[31] = new State(-87);
    states[32] = new State(-88);
    states[33] = new State(new int[]{59,34});
    states[34] = new State(-90);
    states[35] = new State(new int[]{131,40},new int[]{-104,36,-101,45,-100,39});
    states[36] = new State(new int[]{44,37,59,-91});
    states[37] = new State(new int[]{131,40},new int[]{-101,38,-100,39});
    states[38] = new State(-93);
    states[39] = new State(-94);
    states[40] = new State(new int[]{91,43,44,-59,59,-59,41,-59},new int[]{-112,41,-113,42});
    states[41] = new State(-95);
    states[42] = new State(-58);
    states[43] = new State(new int[]{93,44});
    states[44] = new State(-60);
    states[45] = new State(-92);
    states[46] = new State(-61);
    states[47] = new State(-78);
    states[48] = new State(new int[]{91,43},new int[]{-113,49});
    states[49] = new State(-79);
    states[50] = new State(new int[]{58,51,91,-80,61,-146});
    states[51] = new State(new int[]{131,171,123,27,147,174,143,179,133,187,160,191,151,196,141,200,136,206,137,211,139,218,181,228},new int[]{-34,52,-41,53,-40,54,-2,55,-3,57,-4,58,-5,170,-50,172,-68,173,-62,178,-69,186,-70,190,-63,195,-64,199,-65,205,-66,210,-54,217,-55,226,-56,227,-67,233});
    states[52] = new State(-136);
    states[53] = new State(-96);
    states[54] = new State(-103);
    states[55] = new State(new int[]{59,56});
    states[56] = new State(-119);
    states[57] = new State(-120);
    states[58] = new State(new int[]{61,169},new int[]{-115,59});
    states[59] = new State(new int[]{131,68,197,92,198,95,43,97,45,99,182,108,183,109,184,110,185,111,186,112,187,113,126,117,33,119,40,122,194,-161},new int[]{-11,60,-12,61,-116,62,-9,65,-3,66,-4,58,-5,67,-14,69,-15,70,-16,168,-17,167,-18,166,-19,165,-20,164,-21,163,-22,160,-23,149,-24,144,-25,141,-28,91,-29,94,-30,101,-26,102,-27,105,-10,106,-1,107,-32,115,-33,116,-31,121});
    states[60] = new State(-144);
    states[61] = new State(-158);
    states[62] = new State(new int[]{194,63});
    states[63] = new State(-162,new int[]{-13,64});
    states[64] = new State(-160);
    states[65] = new State(-159);
    states[66] = new State(-148);
    states[67] = new State(new int[]{61,-145,197,-206,198,-206,42,-206,47,-206,37,-206,43,-206,45,-206,199,-206,200,-206,201,-206,60,-206,62,-206,192,-206,191,-206,159,-206,190,-206,193,-206,38,-206,94,-206,124,-206,195,-206,196,-206,59,-206,41,-206,58,-206});
    states[68] = new State(-146);
    states[69] = new State(-149);
    states[70] = new State(new int[]{196,71,59,-163,41,-163,58,-163});
    states[71] = new State(new int[]{197,92,198,95,43,97,45,99,182,108,183,109,184,110,185,111,186,112,187,113,131,68,126,117,33,119,40,122},new int[]{-16,72,-17,167,-18,166,-19,165,-20,164,-21,163,-22,160,-23,149,-24,144,-25,141,-28,91,-29,94,-30,101,-26,102,-27,105,-10,106,-1,107,-5,114,-32,115,-33,116,-31,121});
    states[72] = new State(new int[]{195,73,196,-165,59,-165,41,-165,58,-165});
    states[73] = new State(new int[]{197,92,198,95,43,97,45,99,182,108,183,109,184,110,185,111,186,112,187,113,131,68,126,117,33,119,40,122},new int[]{-17,74,-18,166,-19,165,-20,164,-21,163,-22,160,-23,149,-24,144,-25,141,-28,91,-29,94,-30,101,-26,102,-27,105,-10,106,-1,107,-5,114,-32,115,-33,116,-31,121});
    states[74] = new State(new int[]{124,75,195,-167,196,-167,59,-167,41,-167,58,-167});
    states[75] = new State(new int[]{197,92,198,95,43,97,45,99,182,108,183,109,184,110,185,111,186,112,187,113,131,68,126,117,33,119,40,122},new int[]{-18,76,-19,165,-20,164,-21,163,-22,160,-23,149,-24,144,-25,141,-28,91,-29,94,-30,101,-26,102,-27,105,-10,106,-1,107,-5,114,-32,115,-33,116,-31,121});
    states[76] = new State(new int[]{94,77,124,-169,195,-169,196,-169,59,-169,41,-169,58,-169});
    states[77] = new State(new int[]{197,92,198,95,43,97,45,99,182,108,183,109,184,110,185,111,186,112,187,113,131,68,126,117,33,119,40,122},new int[]{-19,78,-20,164,-21,163,-22,160,-23,149,-24,144,-25,141,-28,91,-29,94,-30,101,-26,102,-27,105,-10,106,-1,107,-5,114,-32,115,-33,116,-31,121});
    states[78] = new State(new int[]{38,79,94,-171,124,-171,195,-171,196,-171,59,-171,41,-171,58,-171});
    states[79] = new State(new int[]{197,92,198,95,43,97,45,99,182,108,183,109,184,110,185,111,186,112,187,113,131,68,126,117,33,119,40,122},new int[]{-20,80,-21,163,-22,160,-23,149,-24,144,-25,141,-28,91,-29,94,-30,101,-26,102,-27,105,-10,106,-1,107,-5,114,-32,115,-33,116,-31,121});
    states[80] = new State(new int[]{190,81,193,161,38,-173,94,-173,124,-173,195,-173,196,-173,59,-173,41,-173,58,-173});
    states[81] = new State(new int[]{197,92,198,95,43,97,45,99,182,108,183,109,184,110,185,111,186,112,187,113,131,68,126,117,33,119,40,122},new int[]{-21,82,-22,160,-23,149,-24,144,-25,141,-28,91,-29,94,-30,101,-26,102,-27,105,-10,106,-1,107,-5,114,-32,115,-33,116,-31,121});
    states[82] = new State(new int[]{60,83,62,150,192,152,191,154,159,156,190,-175,193,-175,38,-175,94,-175,124,-175,195,-175,196,-175,59,-175,41,-175,58,-175});
    states[83] = new State(new int[]{197,92,198,95,43,97,45,99,182,108,183,109,184,110,185,111,186,112,187,113,131,68,126,117,33,119,40,122},new int[]{-22,84,-23,149,-24,144,-25,141,-28,91,-29,94,-30,101,-26,102,-27,105,-10,106,-1,107,-5,114,-32,115,-33,116,-31,121});
    states[84] = new State(new int[]{199,85,200,145,201,147,60,-178,62,-178,192,-178,191,-178,159,-178,190,-178,193,-178,38,-178,94,-178,124,-178,195,-178,196,-178,59,-178,41,-178,58,-178});
    states[85] = new State(new int[]{197,92,198,95,43,97,45,99,182,108,183,109,184,110,185,111,186,112,187,113,131,68,126,117,33,119,40,122},new int[]{-23,86,-24,144,-25,141,-28,91,-29,94,-30,101,-26,102,-27,105,-10,106,-1,107,-5,114,-32,115,-33,116,-31,121});
    states[86] = new State(new int[]{43,87,45,142,199,-184,200,-184,201,-184,60,-184,62,-184,192,-184,191,-184,159,-184,190,-184,193,-184,38,-184,94,-184,124,-184,195,-184,196,-184,59,-184,41,-184,58,-184});
    states[87] = new State(new int[]{197,92,198,95,43,97,45,99,182,108,183,109,184,110,185,111,186,112,187,113,131,68,126,117,33,119,40,122},new int[]{-24,88,-25,141,-28,91,-29,94,-30,101,-26,102,-27,105,-10,106,-1,107,-5,114,-32,115,-33,116,-31,121});
    states[88] = new State(new int[]{42,89,47,137,37,139,43,-188,45,-188,199,-188,200,-188,201,-188,60,-188,62,-188,192,-188,191,-188,159,-188,190,-188,193,-188,38,-188,94,-188,124,-188,195,-188,196,-188,59,-188,41,-188,58,-188});
    states[89] = new State(new int[]{197,92,198,95,43,97,45,99,182,108,183,109,184,110,185,111,186,112,187,113,131,68,126,117,33,119,40,122},new int[]{-25,90,-28,91,-29,94,-30,101,-26,102,-27,105,-10,106,-1,107,-5,114,-32,115,-33,116,-31,121});
    states[90] = new State(-191);
    states[91] = new State(-194);
    states[92] = new State(new int[]{197,92,198,95,43,97,45,99,182,108,183,109,184,110,185,111,186,112,187,113,131,68,126,117,33,119,40,122},new int[]{-25,93,-28,91,-29,94,-30,101,-26,102,-27,105,-10,106,-1,107,-5,114,-32,115,-33,116,-31,121});
    states[93] = new State(-199);
    states[94] = new State(-195);
    states[95] = new State(new int[]{197,92,198,95,43,97,45,99,182,108,183,109,184,110,185,111,186,112,187,113,131,68,126,117,33,119,40,122},new int[]{-25,96,-28,91,-29,94,-30,101,-26,102,-27,105,-10,106,-1,107,-5,114,-32,115,-33,116,-31,121});
    states[96] = new State(-200);
    states[97] = new State(new int[]{197,92,198,95,43,97,45,99,182,108,183,109,184,110,185,111,186,112,187,113,131,68,126,117,33,119,40,122},new int[]{-25,98,-28,91,-29,94,-30,101,-26,102,-27,105,-10,106,-1,107,-5,114,-32,115,-33,116,-31,121});
    states[98] = new State(-196);
    states[99] = new State(new int[]{197,92,198,95,43,97,45,99,182,108,183,109,184,110,185,111,186,112,187,113,131,68,126,117,33,119,40,122},new int[]{-25,100,-28,91,-29,94,-30,101,-26,102,-27,105,-10,106,-1,107,-5,114,-32,115,-33,116,-31,121});
    states[100] = new State(-197);
    states[101] = new State(-198);
    states[102] = new State(new int[]{197,103,198,104,42,-201,47,-201,37,-201,43,-201,45,-201,199,-201,200,-201,201,-201,60,-201,62,-201,192,-201,191,-201,159,-201,190,-201,193,-201,38,-201,94,-201,124,-201,195,-201,196,-201,59,-201,41,-201,58,-201});
    states[103] = new State(-209);
    states[104] = new State(-210);
    states[105] = new State(-205);
    states[106] = new State(-150);
    states[107] = new State(-151);
    states[108] = new State(-152);
    states[109] = new State(-153);
    states[110] = new State(-154);
    states[111] = new State(-155);
    states[112] = new State(-156);
    states[113] = new State(-157);
    states[114] = new State(-206);
    states[115] = new State(-207);
    states[116] = new State(-208);
    states[117] = new State(new int[]{197,92,198,95,43,97,45,99,182,108,183,109,184,110,185,111,186,112,187,113,131,68,126,117,33,119,40,122},new int[]{-25,118,-28,91,-29,94,-30,101,-26,102,-27,105,-10,106,-1,107,-5,114,-32,115,-33,116,-31,121});
    states[118] = new State(-202);
    states[119] = new State(new int[]{197,92,198,95,43,97,45,99,182,108,183,109,184,110,185,111,186,112,187,113,131,68,126,117,33,119,40,122},new int[]{-25,120,-28,91,-29,94,-30,101,-26,102,-27,105,-10,106,-1,107,-5,114,-32,115,-33,116,-31,121});
    states[120] = new State(-203);
    states[121] = new State(-204);
    states[122] = new State(new int[]{152,128,165,129,164,130,174,131,167,132,178,134,148,135,142,136},new int[]{-93,123,-86,126,-85,127,-84,133});
    states[123] = new State(new int[]{41,124});
    states[124] = new State(new int[]{197,92,198,95,43,97,45,99,182,108,183,109,184,110,185,111,186,112,187,113,131,68,126,117,33,119,40,122},new int[]{-25,125,-28,91,-29,94,-30,101,-26,102,-27,105,-10,106,-1,107,-5,114,-32,115,-33,116,-31,121});
    states[125] = new State(-211);
    states[126] = new State(-65);
    states[127] = new State(-69);
    states[128] = new State(-71);
    states[129] = new State(-72);
    states[130] = new State(-73);
    states[131] = new State(-74);
    states[132] = new State(-75);
    states[133] = new State(-70);
    states[134] = new State(-76);
    states[135] = new State(-77);
    states[136] = new State(-66);
    states[137] = new State(new int[]{197,92,198,95,43,97,45,99,182,108,183,109,184,110,185,111,186,112,187,113,131,68,126,117,33,119,40,122},new int[]{-25,138,-28,91,-29,94,-30,101,-26,102,-27,105,-10,106,-1,107,-5,114,-32,115,-33,116,-31,121});
    states[138] = new State(-192);
    states[139] = new State(new int[]{197,92,198,95,43,97,45,99,182,108,183,109,184,110,185,111,186,112,187,113,131,68,126,117,33,119,40,122},new int[]{-25,140,-28,91,-29,94,-30,101,-26,102,-27,105,-10,106,-1,107,-5,114,-32,115,-33,116,-31,121});
    states[140] = new State(-193);
    states[141] = new State(-190);
    states[142] = new State(new int[]{197,92,198,95,43,97,45,99,182,108,183,109,184,110,185,111,186,112,187,113,131,68,126,117,33,119,40,122},new int[]{-24,143,-25,141,-28,91,-29,94,-30,101,-26,102,-27,105,-10,106,-1,107,-5,114,-32,115,-33,116,-31,121});
    states[143] = new State(new int[]{42,89,47,137,37,139,43,-189,45,-189,199,-189,200,-189,201,-189,60,-189,62,-189,192,-189,191,-189,159,-189,190,-189,193,-189,38,-189,94,-189,124,-189,195,-189,196,-189,59,-189,41,-189,58,-189});
    states[144] = new State(new int[]{42,89,47,137,37,139,43,-187,45,-187,199,-187,200,-187,201,-187,60,-187,62,-187,192,-187,191,-187,159,-187,190,-187,193,-187,38,-187,94,-187,124,-187,195,-187,196,-187,59,-187,41,-187,58,-187});
    states[145] = new State(new int[]{197,92,198,95,43,97,45,99,182,108,183,109,184,110,185,111,186,112,187,113,131,68,126,117,33,119,40,122},new int[]{-23,146,-24,144,-25,141,-28,91,-29,94,-30,101,-26,102,-27,105,-10,106,-1,107,-5,114,-32,115,-33,116,-31,121});
    states[146] = new State(new int[]{43,87,45,142,199,-185,200,-185,201,-185,60,-185,62,-185,192,-185,191,-185,159,-185,190,-185,193,-185,38,-185,94,-185,124,-185,195,-185,196,-185,59,-185,41,-185,58,-185});
    states[147] = new State(new int[]{197,92,198,95,43,97,45,99,182,108,183,109,184,110,185,111,186,112,187,113,131,68,126,117,33,119,40,122},new int[]{-23,148,-24,144,-25,141,-28,91,-29,94,-30,101,-26,102,-27,105,-10,106,-1,107,-5,114,-32,115,-33,116,-31,121});
    states[148] = new State(new int[]{43,87,45,142,199,-186,200,-186,201,-186,60,-186,62,-186,192,-186,191,-186,159,-186,190,-186,193,-186,38,-186,94,-186,124,-186,195,-186,196,-186,59,-186,41,-186,58,-186});
    states[149] = new State(new int[]{43,87,45,142,199,-183,200,-183,201,-183,60,-183,62,-183,192,-183,191,-183,159,-183,190,-183,193,-183,38,-183,94,-183,124,-183,195,-183,196,-183,59,-183,41,-183,58,-183});
    states[150] = new State(new int[]{197,92,198,95,43,97,45,99,182,108,183,109,184,110,185,111,186,112,187,113,131,68,126,117,33,119,40,122},new int[]{-22,151,-23,149,-24,144,-25,141,-28,91,-29,94,-30,101,-26,102,-27,105,-10,106,-1,107,-5,114,-32,115,-33,116,-31,121});
    states[151] = new State(new int[]{199,85,200,145,201,147,60,-179,62,-179,192,-179,191,-179,159,-179,190,-179,193,-179,38,-179,94,-179,124,-179,195,-179,196,-179,59,-179,41,-179,58,-179});
    states[152] = new State(new int[]{197,92,198,95,43,97,45,99,182,108,183,109,184,110,185,111,186,112,187,113,131,68,126,117,33,119,40,122},new int[]{-22,153,-23,149,-24,144,-25,141,-28,91,-29,94,-30,101,-26,102,-27,105,-10,106,-1,107,-5,114,-32,115,-33,116,-31,121});
    states[153] = new State(new int[]{199,85,200,145,201,147,60,-180,62,-180,192,-180,191,-180,159,-180,190,-180,193,-180,38,-180,94,-180,124,-180,195,-180,196,-180,59,-180,41,-180,58,-180});
    states[154] = new State(new int[]{197,92,198,95,43,97,45,99,182,108,183,109,184,110,185,111,186,112,187,113,131,68,126,117,33,119,40,122},new int[]{-22,155,-23,149,-24,144,-25,141,-28,91,-29,94,-30,101,-26,102,-27,105,-10,106,-1,107,-5,114,-32,115,-33,116,-31,121});
    states[155] = new State(new int[]{199,85,200,145,201,147,60,-181,62,-181,192,-181,191,-181,159,-181,190,-181,193,-181,38,-181,94,-181,124,-181,195,-181,196,-181,59,-181,41,-181,58,-181});
    states[156] = new State(new int[]{131,159},new int[]{-92,157,-114,158});
    states[157] = new State(-182);
    states[158] = new State(-67);
    states[159] = new State(-68);
    states[160] = new State(new int[]{199,85,200,145,201,147,60,-177,62,-177,192,-177,191,-177,159,-177,190,-177,193,-177,38,-177,94,-177,124,-177,195,-177,196,-177,59,-177,41,-177,58,-177});
    states[161] = new State(new int[]{197,92,198,95,43,97,45,99,182,108,183,109,184,110,185,111,186,112,187,113,131,68,126,117,33,119,40,122},new int[]{-21,162,-22,160,-23,149,-24,144,-25,141,-28,91,-29,94,-30,101,-26,102,-27,105,-10,106,-1,107,-5,114,-32,115,-33,116,-31,121});
    states[162] = new State(new int[]{60,83,62,150,192,152,191,154,159,156,190,-176,193,-176,38,-176,94,-176,124,-176,195,-176,196,-176,59,-176,41,-176,58,-176});
    states[163] = new State(new int[]{60,83,62,150,192,152,191,154,159,156,190,-174,193,-174,38,-174,94,-174,124,-174,195,-174,196,-174,59,-174,41,-174,58,-174});
    states[164] = new State(new int[]{190,81,193,161,38,-172,94,-172,124,-172,195,-172,196,-172,59,-172,41,-172,58,-172});
    states[165] = new State(new int[]{38,79,94,-170,124,-170,195,-170,196,-170,59,-170,41,-170,58,-170});
    states[166] = new State(new int[]{94,77,124,-168,195,-168,196,-168,59,-168,41,-168,58,-168});
    states[167] = new State(new int[]{124,75,195,-166,196,-166,59,-166,41,-166,58,-166});
    states[168] = new State(new int[]{195,73,196,-164,59,-164,41,-164,58,-164});
    states[169] = new State(-147);
    states[170] = new State(-145);
    states[171] = new State(new int[]{58,51,61,-146});
    states[172] = new State(-104);
    states[173] = new State(-105);
    states[174] = new State(new int[]{131,177,59,-139},new int[]{-105,175});
    states[175] = new State(new int[]{59,176});
    states[176] = new State(-137);
    states[177] = new State(-138);
    states[178] = new State(-106);
    states[179] = new State(new int[]{131,171,123,27,147,174,143,179,133,187,160,191,151,196,141,200,136,206,137,211,139,218,181,228},new int[]{-34,180,-41,53,-40,54,-2,55,-3,57,-4,58,-5,170,-50,172,-68,173,-62,178,-69,186,-70,190,-63,195,-64,199,-65,205,-66,210,-54,217,-55,226,-56,227,-67,233});
    states[180] = new State(new int[]{181,181});
    states[181] = new State(new int[]{40,182});
    states[182] = new State(new int[]{131,68,197,92,198,95,43,97,45,99,182,108,183,109,184,110,185,111,186,112,187,113,126,117,33,119,40,122,194,-161},new int[]{-11,183,-12,61,-116,62,-9,65,-3,66,-4,58,-5,67,-14,69,-15,70,-16,168,-17,167,-18,166,-19,165,-20,164,-21,163,-22,160,-23,149,-24,144,-25,141,-28,91,-29,94,-30,101,-26,102,-27,105,-10,106,-1,107,-32,115,-33,116,-31,121});
    states[183] = new State(new int[]{41,184});
    states[184] = new State(new int[]{59,185});
    states[185] = new State(-116);
    states[186] = new State(-107);
    states[187] = new State(new int[]{131,177,59,-139},new int[]{-105,188});
    states[188] = new State(new int[]{59,189});
    states[189] = new State(-140);
    states[190] = new State(-108);
    states[191] = new State(new int[]{131,68,197,92,198,95,43,97,45,99,182,108,183,109,184,110,185,111,186,112,187,113,126,117,33,119,40,122,194,-161,59,-143},new int[]{-106,192,-11,194,-12,61,-116,62,-9,65,-3,66,-4,58,-5,67,-14,69,-15,70,-16,168,-17,167,-18,166,-19,165,-20,164,-21,163,-22,160,-23,149,-24,144,-25,141,-28,91,-29,94,-30,101,-26,102,-27,105,-10,106,-1,107,-32,115,-33,116,-31,121});
    states[192] = new State(new int[]{59,193});
    states[193] = new State(-141);
    states[194] = new State(-142);
    states[195] = new State(-109);
    states[196] = new State(new int[]{131,68,197,92,198,95,43,97,45,99,182,108,183,109,184,110,185,111,186,112,187,113,126,117,33,119,40,122,194,-161},new int[]{-11,197,-12,61,-116,62,-9,65,-3,66,-4,58,-5,67,-14,69,-15,70,-16,168,-17,167,-18,166,-19,165,-20,164,-21,163,-22,160,-23,149,-24,144,-25,141,-28,91,-29,94,-30,101,-26,102,-27,105,-10,106,-1,107,-32,115,-33,116,-31,121});
    states[197] = new State(new int[]{59,198});
    states[198] = new State(-117);
    states[199] = new State(-110);
    states[200] = new State(new int[]{40,201});
    states[201] = new State(new int[]{131,68,197,92,198,95,43,97,45,99,182,108,183,109,184,110,185,111,186,112,187,113,126,117,33,119,40,122,194,-161},new int[]{-11,202,-12,61,-116,62,-9,65,-3,66,-4,58,-5,67,-14,69,-15,70,-16,168,-17,167,-18,166,-19,165,-20,164,-21,163,-22,160,-23,149,-24,144,-25,141,-28,91,-29,94,-30,101,-26,102,-27,105,-10,106,-1,107,-32,115,-33,116,-31,121});
    states[202] = new State(new int[]{41,203});
    states[203] = new State(new int[]{123,27},new int[]{-50,204});
    states[204] = new State(-118);
    states[205] = new State(-111);
    states[206] = new State(new int[]{40,207});
    states[207] = new State(new int[]{131,68,197,92,198,95,43,97,45,99,182,108,183,109,184,110,185,111,186,112,187,113,126,117,33,119,40,122,194,-161},new int[]{-11,208,-12,61,-116,62,-9,65,-3,66,-4,58,-5,67,-14,69,-15,70,-16,168,-17,167,-18,166,-19,165,-20,164,-21,163,-22,160,-23,149,-24,144,-25,141,-28,91,-29,94,-30,101,-26,102,-27,105,-10,106,-1,107,-32,115,-33,116,-31,121});
    states[208] = new State(new int[]{41,209});
    states[209] = new State(-115);
    states[210] = new State(-112);
    states[211] = new State(new int[]{131,68,197,92,198,95,43,97,45,99,182,108,183,109,184,110,185,111,186,112,187,113,126,117,33,119,40,122,194,-161},new int[]{-11,212,-12,61,-116,62,-9,65,-3,66,-4,58,-5,67,-14,69,-15,70,-16,168,-17,167,-18,166,-19,165,-20,164,-21,163,-22,160,-23,149,-24,144,-25,141,-28,91,-29,94,-30,101,-26,102,-27,105,-10,106,-1,107,-32,115,-33,116,-31,121});
    states[212] = new State(new int[]{59,213,58,214});
    states[213] = new State(-113);
    states[214] = new State(new int[]{131,68,197,92,198,95,43,97,45,99,182,108,183,109,184,110,185,111,186,112,187,113,126,117,33,119,40,122,194,-161},new int[]{-11,215,-12,61,-116,62,-9,65,-3,66,-4,58,-5,67,-14,69,-15,70,-16,168,-17,167,-18,166,-19,165,-20,164,-21,163,-22,160,-23,149,-24,144,-25,141,-28,91,-29,94,-30,101,-26,102,-27,105,-10,106,-1,107,-32,115,-33,116,-31,121});
    states[215] = new State(new int[]{59,216});
    states[216] = new State(-114);
    states[217] = new State(-97);
    states[218] = new State(new int[]{40,219});
    states[219] = new State(new int[]{131,68,197,92,198,95,43,97,45,99,182,108,183,109,184,110,185,111,186,112,187,113,126,117,33,119,40,122,194,-161},new int[]{-11,220,-12,61,-116,62,-9,65,-3,66,-4,58,-5,67,-14,69,-15,70,-16,168,-17,167,-18,166,-19,165,-20,164,-21,163,-22,160,-23,149,-24,144,-25,141,-28,91,-29,94,-30,101,-26,102,-27,105,-10,106,-1,107,-32,115,-33,116,-31,121});
    states[220] = new State(new int[]{41,221});
    states[221] = new State(new int[]{131,171,123,27,147,174,143,179,133,187,160,191,151,196,141,200,136,206,137,211,139,235,181,228},new int[]{-34,222,-52,223,-41,234,-40,54,-2,55,-3,57,-4,58,-5,170,-50,172,-68,173,-62,178,-69,186,-70,190,-63,195,-64,199,-65,205,-66,210,-54,217,-55,226,-56,227,-67,233,-53,242});
    states[222] = new State(-121);
    states[223] = new State(new int[]{153,224});
    states[224] = new State(new int[]{131,171,123,27,147,174,143,179,133,187,160,191,151,196,141,200,136,206,137,211,139,218,181,228},new int[]{-34,225,-41,53,-40,54,-2,55,-3,57,-4,58,-5,170,-50,172,-68,173,-62,178,-69,186,-70,190,-63,195,-64,199,-65,205,-66,210,-54,217,-55,226,-56,227,-67,233});
    states[225] = new State(-122);
    states[226] = new State(-98);
    states[227] = new State(-99);
    states[228] = new State(new int[]{40,229});
    states[229] = new State(new int[]{131,68,197,92,198,95,43,97,45,99,182,108,183,109,184,110,185,111,186,112,187,113,126,117,33,119,40,122,194,-161},new int[]{-11,230,-12,61,-116,62,-9,65,-3,66,-4,58,-5,67,-14,69,-15,70,-16,168,-17,167,-18,166,-19,165,-20,164,-21,163,-22,160,-23,149,-24,144,-25,141,-28,91,-29,94,-30,101,-26,102,-27,105,-10,106,-1,107,-32,115,-33,116,-31,121});
    states[230] = new State(new int[]{41,231});
    states[231] = new State(new int[]{131,171,123,27,147,174,143,179,133,187,160,191,151,196,141,200,136,206,137,211,139,218,181,228},new int[]{-34,232,-41,53,-40,54,-2,55,-3,57,-4,58,-5,170,-50,172,-68,173,-62,178,-69,186,-70,190,-63,195,-64,199,-65,205,-66,210,-54,217,-55,226,-56,227,-67,233});
    states[232] = new State(-124);
    states[233] = new State(-100);
    states[234] = new State(new int[]{131,-96,152,-96,165,-96,164,-96,174,-96,167,-96,178,-96,148,-96,142,-96,123,-96,147,-96,143,-96,133,-96,160,-96,151,-96,141,-96,136,-96,137,-96,139,-96,181,-96,125,-96,153,-101});
    states[235] = new State(new int[]{40,236});
    states[236] = new State(new int[]{131,68,197,92,198,95,43,97,45,99,182,108,183,109,184,110,185,111,186,112,187,113,126,117,33,119,40,122,194,-161},new int[]{-11,237,-12,61,-116,62,-9,65,-3,66,-4,58,-5,67,-14,69,-15,70,-16,168,-17,167,-18,166,-19,165,-20,164,-21,163,-22,160,-23,149,-24,144,-25,141,-28,91,-29,94,-30,101,-26,102,-27,105,-10,106,-1,107,-32,115,-33,116,-31,121});
    states[237] = new State(new int[]{41,238});
    states[238] = new State(new int[]{131,171,123,27,147,174,143,179,133,187,160,191,151,196,141,200,136,206,137,211,139,235,181,228},new int[]{-34,222,-52,239,-41,234,-40,54,-2,55,-3,57,-4,58,-5,170,-50,172,-68,173,-62,178,-69,186,-70,190,-63,195,-64,199,-65,205,-66,210,-54,217,-55,226,-56,227,-67,233,-53,242});
    states[239] = new State(new int[]{153,240});
    states[240] = new State(new int[]{131,171,123,27,147,174,143,179,133,187,160,191,151,196,141,200,136,206,137,211,139,235,181,228},new int[]{-34,225,-52,241,-41,234,-40,54,-2,55,-3,57,-4,58,-5,170,-50,172,-68,173,-62,178,-69,186,-70,190,-63,195,-64,199,-65,205,-66,210,-54,217,-55,226,-56,227,-67,233,-53,242});
    states[241] = new State(-123);
    states[242] = new State(-102);
    states[243] = new State(-62);
    states[244] = new State(-63);
    states[245] = new State(-64);
    states[246] = new State(-89);
    states[247] = new State(-86);
    states[248] = new State(-82);
    states[249] = new State(-40);
    states[250] = new State(new int[]{131,254},new int[]{-103,251});
    states[251] = new State(-3,new int[]{-45,252,-111,253});
    states[252] = new State(-44);
    states[253] = new State(-47);
    states[254] = new State(new int[]{40,255});
    states[255] = new State(new int[]{131,-56,152,-56,165,-56,164,-56,174,-56,167,-56,178,-56,148,-56,142,-56,168,-56,41,-50},new int[]{-81,256,-80,259,-79,260,-48,269,-99,263});
    states[256] = new State(new int[]{41,257});
    states[257] = new State(new int[]{91,43,123,-59,59,-59},new int[]{-112,258,-113,42});
    states[258] = new State(-48);
    states[259] = new State(-49);
    states[260] = new State(new int[]{44,261,41,-51});
    states[261] = new State(-56,new int[]{-48,262,-99,263});
    states[262] = new State(-53);
    states[263] = new State(new int[]{131,267,152,128,165,129,164,130,174,131,167,132,178,134,148,135,142,245,168,268},new int[]{-87,264,-96,266,-89,46,-90,47,-91,48,-88,243,-86,244,-85,127,-84,133});
    states[264] = new State(new int[]{131,40},new int[]{-100,265});
    states[265] = new State(-54);
    states[266] = new State(-55);
    states[267] = new State(-80);
    states[268] = new State(-57);
    states[269] = new State(-52);
    states[270] = new State(-45);
    states[271] = new State(-46);
    states[272] = new State(-42);
    states[273] = new State(-43);
    states[274] = new State(-22);
    states[275] = new State(-24);
    states[276] = new State(-25);
    states[277] = new State(-26);
    states[278] = new State(-27);
    states[279] = new State(-28);
    states[280] = new State(-29);
    states[281] = new State(-30);
    states[282] = new State(-7);
    states[283] = new State(-9);
    states[284] = new State(new int[]{131,292},new int[]{-107,285,-108,287});
    states[285] = new State(new int[]{59,286});
    states[286] = new State(-11);
    states[287] = new State(new int[]{46,288});
    states[288] = new State(new int[]{42,289,131,291});
    states[289] = new State(new int[]{59,290});
    states[290] = new State(-12);
    states[291] = new State(new int[]{59,-14,46,-16});
    states[292] = new State(new int[]{59,-13,46,-15});
    states[293] = new State(-10);
    states[294] = new State(-6);

    for (int sNo = 0; sNo < states.Length; sNo++) states[sNo].number = sNo;

    rules[1] = new Rule(-110, new int[]{-109,129});
    rules[2] = new Rule(-109, new int[]{-35});
    rules[3] = new Rule(-111, new int[]{});
    rules[4] = new Rule(-35, new int[]{-49,-82,-74});
    rules[5] = new Rule(-49, new int[]{});
    rules[6] = new Rule(-82, new int[]{-71});
    rules[7] = new Rule(-82, new int[]{-82,-71});
    rules[8] = new Rule(-82, new int[]{});
    rules[9] = new Rule(-71, new int[]{-72});
    rules[10] = new Rule(-71, new int[]{-73});
    rules[11] = new Rule(-72, new int[]{154,-107,59});
    rules[12] = new Rule(-73, new int[]{154,-108,46,42,59});
    rules[13] = new Rule(-107, new int[]{131});
    rules[14] = new Rule(-107, new int[]{-108,46,131});
    rules[15] = new Rule(-108, new int[]{131});
    rules[16] = new Rule(-108, new int[]{-108,46,131});
    rules[17] = new Rule(-74, new int[]{-74,-36});
    rules[18] = new Rule(-74, new int[]{});
    rules[19] = new Rule(-36, new int[]{-37});
    rules[20] = new Rule(-37, new int[]{-38});
    rules[21] = new Rule(-38, new int[]{-97,172,131,-6,-7,-8,-75});
    rules[22] = new Rule(-97, new int[]{-97,-94});
    rules[23] = new Rule(-97, new int[]{});
    rules[24] = new Rule(-94, new int[]{155});
    rules[25] = new Rule(-94, new int[]{150});
    rules[26] = new Rule(-94, new int[]{145});
    rules[27] = new Rule(-94, new int[]{132});
    rules[28] = new Rule(-94, new int[]{170});
    rules[29] = new Rule(-94, new int[]{168});
    rules[30] = new Rule(-94, new int[]{175});
    rules[31] = new Rule(-6, new int[]{});
    rules[32] = new Rule(-7, new int[]{});
    rules[33] = new Rule(-8, new int[]{});
    rules[34] = new Rule(-75, new int[]{123,-76,125});
    rules[35] = new Rule(-76, new int[]{-76,-39});
    rules[36] = new Rule(-76, new int[]{});
    rules[37] = new Rule(-39, new int[]{-46});
    rules[38] = new Rule(-46, new int[]{-47});
    rules[39] = new Rule(-47, new int[]{-98,-102,-51});
    rules[40] = new Rule(-98, new int[]{-98,-95});
    rules[41] = new Rule(-98, new int[]{});
    rules[42] = new Rule(-95, new int[]{155});
    rules[43] = new Rule(-95, new int[]{170});
    rules[44] = new Rule(-102, new int[]{-83,-103,-45});
    rules[45] = new Rule(-83, new int[]{171});
    rules[46] = new Rule(-83, new int[]{-87});
    rules[47] = new Rule(-45, new int[]{-111});
    rules[48] = new Rule(-103, new int[]{131,40,-81,41,-112});
    rules[49] = new Rule(-81, new int[]{-80});
    rules[50] = new Rule(-81, new int[]{});
    rules[51] = new Rule(-80, new int[]{-79});
    rules[52] = new Rule(-79, new int[]{-48});
    rules[53] = new Rule(-79, new int[]{-79,44,-48});
    rules[54] = new Rule(-48, new int[]{-99,-87,-100});
    rules[55] = new Rule(-99, new int[]{-99,-96});
    rules[56] = new Rule(-99, new int[]{});
    rules[57] = new Rule(-96, new int[]{168});
    rules[58] = new Rule(-112, new int[]{-113});
    rules[59] = new Rule(-112, new int[]{});
    rules[60] = new Rule(-113, new int[]{91,93});
    rules[61] = new Rule(-87, new int[]{-89});
    rules[62] = new Rule(-87, new int[]{-88});
    rules[63] = new Rule(-88, new int[]{-86});
    rules[64] = new Rule(-88, new int[]{142});
    rules[65] = new Rule(-93, new int[]{-86});
    rules[66] = new Rule(-93, new int[]{142});
    rules[67] = new Rule(-92, new int[]{-114});
    rules[68] = new Rule(-114, new int[]{131});
    rules[69] = new Rule(-86, new int[]{-85});
    rules[70] = new Rule(-86, new int[]{-84});
    rules[71] = new Rule(-85, new int[]{152});
    rules[72] = new Rule(-85, new int[]{165});
    rules[73] = new Rule(-85, new int[]{164});
    rules[74] = new Rule(-85, new int[]{174});
    rules[75] = new Rule(-85, new int[]{167});
    rules[76] = new Rule(-84, new int[]{178});
    rules[77] = new Rule(-84, new int[]{148});
    rules[78] = new Rule(-89, new int[]{-90});
    rules[79] = new Rule(-90, new int[]{-91,-113});
    rules[80] = new Rule(-91, new int[]{131});
    rules[81] = new Rule(-51, new int[]{-50});
    rules[82] = new Rule(-51, new int[]{59});
    rules[83] = new Rule(-50, new int[]{123,-78,125});
    rules[84] = new Rule(-78, new int[]{-77});
    rules[85] = new Rule(-78, new int[]{});
    rules[86] = new Rule(-77, new int[]{-44});
    rules[87] = new Rule(-77, new int[]{-77,-44});
    rules[88] = new Rule(-44, new int[]{-43});
    rules[89] = new Rule(-44, new int[]{-34});
    rules[90] = new Rule(-43, new int[]{-42,59});
    rules[91] = new Rule(-42, new int[]{-87,-104});
    rules[92] = new Rule(-104, new int[]{-101});
    rules[93] = new Rule(-104, new int[]{-104,44,-101});
    rules[94] = new Rule(-101, new int[]{-100});
    rules[95] = new Rule(-100, new int[]{131,-112});
    rules[96] = new Rule(-34, new int[]{-41});
    rules[97] = new Rule(-34, new int[]{-54});
    rules[98] = new Rule(-34, new int[]{-55});
    rules[99] = new Rule(-34, new int[]{-56});
    rules[100] = new Rule(-34, new int[]{-67});
    rules[101] = new Rule(-52, new int[]{-41});
    rules[102] = new Rule(-52, new int[]{-53});
    rules[103] = new Rule(-41, new int[]{-40});
    rules[104] = new Rule(-41, new int[]{-50});
    rules[105] = new Rule(-41, new int[]{-68});
    rules[106] = new Rule(-41, new int[]{-62});
    rules[107] = new Rule(-41, new int[]{-69});
    rules[108] = new Rule(-41, new int[]{-70});
    rules[109] = new Rule(-41, new int[]{-63});
    rules[110] = new Rule(-41, new int[]{-64});
    rules[111] = new Rule(-41, new int[]{-65});
    rules[112] = new Rule(-41, new int[]{-66});
    rules[113] = new Rule(-66, new int[]{137,-11,59});
    rules[114] = new Rule(-66, new int[]{137,-11,58,-11,59});
    rules[115] = new Rule(-65, new int[]{136,40,-11,41});
    rules[116] = new Rule(-62, new int[]{143,-34,181,40,-11,41,59});
    rules[117] = new Rule(-63, new int[]{151,-11,59});
    rules[118] = new Rule(-64, new int[]{141,40,-11,41,-50});
    rules[119] = new Rule(-40, new int[]{-2,59});
    rules[120] = new Rule(-2, new int[]{-3});
    rules[121] = new Rule(-54, new int[]{139,40,-11,41,-34});
    rules[122] = new Rule(-55, new int[]{139,40,-11,41,-52,153,-34});
    rules[123] = new Rule(-53, new int[]{139,40,-11,41,-52,153,-52});
    rules[124] = new Rule(-56, new int[]{181,40,-11,41,-34});
    rules[125] = new Rule(-57, new int[]{166,-50,-58});
    rules[126] = new Rule(-57, new int[]{166,-50,-59,-61});
    rules[127] = new Rule(-59, new int[]{-58});
    rules[128] = new Rule(-59, new int[]{});
    rules[129] = new Rule(-58, new int[]{-60});
    rules[130] = new Rule(-60, new int[]{162,40,41,-50});
    rules[131] = new Rule(-61, new int[]{173,-50});
    rules[132] = new Rule(-54, new int[]{139,40,-11,41,-34});
    rules[133] = new Rule(-55, new int[]{139,40,-11,41,-52,153,-34});
    rules[134] = new Rule(-53, new int[]{139,40,-11,41,-52,153,-52});
    rules[135] = new Rule(-56, new int[]{181,40,-11,41,-34});
    rules[136] = new Rule(-67, new int[]{131,58,-34});
    rules[137] = new Rule(-68, new int[]{147,-105,59});
    rules[138] = new Rule(-105, new int[]{131});
    rules[139] = new Rule(-105, new int[]{});
    rules[140] = new Rule(-69, new int[]{133,-105,59});
    rules[141] = new Rule(-70, new int[]{160,-106,59});
    rules[142] = new Rule(-106, new int[]{-11});
    rules[143] = new Rule(-106, new int[]{});
    rules[144] = new Rule(-3, new int[]{-4,-115,-11});
    rules[145] = new Rule(-4, new int[]{-5});
    rules[146] = new Rule(-5, new int[]{131});
    rules[147] = new Rule(-115, new int[]{61});
    rules[148] = new Rule(-9, new int[]{-3});
    rules[149] = new Rule(-9, new int[]{-14});
    rules[150] = new Rule(-27, new int[]{-10});
    rules[151] = new Rule(-10, new int[]{-1});
    rules[152] = new Rule(-1, new int[]{182});
    rules[153] = new Rule(-1, new int[]{183});
    rules[154] = new Rule(-1, new int[]{184});
    rules[155] = new Rule(-1, new int[]{185});
    rules[156] = new Rule(-1, new int[]{186});
    rules[157] = new Rule(-1, new int[]{187});
    rules[158] = new Rule(-11, new int[]{-12});
    rules[159] = new Rule(-11, new int[]{-9});
    rules[160] = new Rule(-12, new int[]{-116,194,-13});
    rules[161] = new Rule(-116, new int[]{});
    rules[162] = new Rule(-13, new int[]{});
    rules[163] = new Rule(-14, new int[]{-15});
    rules[164] = new Rule(-15, new int[]{-16});
    rules[165] = new Rule(-15, new int[]{-15,196,-16});
    rules[166] = new Rule(-16, new int[]{-17});
    rules[167] = new Rule(-16, new int[]{-16,195,-17});
    rules[168] = new Rule(-17, new int[]{-18});
    rules[169] = new Rule(-17, new int[]{-17,124,-18});
    rules[170] = new Rule(-18, new int[]{-19});
    rules[171] = new Rule(-18, new int[]{-18,94,-19});
    rules[172] = new Rule(-19, new int[]{-20});
    rules[173] = new Rule(-19, new int[]{-19,38,-20});
    rules[174] = new Rule(-20, new int[]{-21});
    rules[175] = new Rule(-20, new int[]{-20,190,-21});
    rules[176] = new Rule(-20, new int[]{-20,193,-21});
    rules[177] = new Rule(-21, new int[]{-22});
    rules[178] = new Rule(-21, new int[]{-21,60,-22});
    rules[179] = new Rule(-21, new int[]{-21,62,-22});
    rules[180] = new Rule(-21, new int[]{-21,192,-22});
    rules[181] = new Rule(-21, new int[]{-21,191,-22});
    rules[182] = new Rule(-21, new int[]{-21,159,-92});
    rules[183] = new Rule(-22, new int[]{-23});
    rules[184] = new Rule(-22, new int[]{-22,199,-23});
    rules[185] = new Rule(-22, new int[]{-22,200,-23});
    rules[186] = new Rule(-22, new int[]{-22,201,-23});
    rules[187] = new Rule(-23, new int[]{-24});
    rules[188] = new Rule(-23, new int[]{-23,43,-24});
    rules[189] = new Rule(-23, new int[]{-23,45,-24});
    rules[190] = new Rule(-24, new int[]{-25});
    rules[191] = new Rule(-24, new int[]{-24,42,-25});
    rules[192] = new Rule(-24, new int[]{-24,47,-25});
    rules[193] = new Rule(-24, new int[]{-24,37,-25});
    rules[194] = new Rule(-25, new int[]{-28});
    rules[195] = new Rule(-25, new int[]{-29});
    rules[196] = new Rule(-25, new int[]{43,-25});
    rules[197] = new Rule(-25, new int[]{45,-25});
    rules[198] = new Rule(-25, new int[]{-30});
    rules[199] = new Rule(-28, new int[]{197,-25});
    rules[200] = new Rule(-29, new int[]{198,-25});
    rules[201] = new Rule(-30, new int[]{-26});
    rules[202] = new Rule(-30, new int[]{126,-25});
    rules[203] = new Rule(-30, new int[]{33,-25});
    rules[204] = new Rule(-30, new int[]{-31});
    rules[205] = new Rule(-26, new int[]{-27});
    rules[206] = new Rule(-26, new int[]{-5});
    rules[207] = new Rule(-26, new int[]{-32});
    rules[208] = new Rule(-26, new int[]{-33});
    rules[209] = new Rule(-32, new int[]{-26,197});
    rules[210] = new Rule(-33, new int[]{-26,198});
    rules[211] = new Rule(-31, new int[]{40,-93,41,-25});
    rules[212] = new Rule(-117, new int[]{-117,-118});
    rules[213] = new Rule(-117, new int[]{});
    rules[214] = new Rule(-118, new int[]{38});
    rules[215] = new Rule(-119, new int[]{-11});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
#pragma warning disable 162, 1522
    switch (action)
    {
      case 2: // Program -> CompilationUnit
#line 123 "parser.y"
                                   {root = ValueStack[ValueStack.Depth-1].stmt;}
#line default
        break;
      case 4: // CompilationUnit -> PackageDeclaration_opt, ImportDeclarations, TypeDeclarations
#line 131 "parser.y"
                                                               { CurrentSemanticValue.stmt = new CompilationUnitDeclaration(ValueStack[ValueStack.Depth-3].stmt,ValueStack[ValueStack.Depth-2].stmts,ValueStack[ValueStack.Depth-1].stmts);  }
#line default
        break;
      case 6: // ImportDeclarations -> ImportDeclaration
#line 140 "parser.y"
                                 { CurrentSemanticValue.stmts = new List<Statement> {ValueStack[ValueStack.Depth-1].stmt};}
#line default
        break;
      case 7: // ImportDeclarations -> ImportDeclarations, ImportDeclaration
#line 141 "parser.y"
                                                  { CurrentSemanticValue.stmts = ValueStack[ValueStack.Depth-2].stmts; CurrentSemanticValue.stmts.Add(ValueStack[ValueStack.Depth-1].stmt);}
#line default
        break;
      case 9: // ImportDeclaration -> SingleTypeImportDeclaration
#line 146 "parser.y"
                                        { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt;}
#line default
        break;
      case 10: // ImportDeclaration -> TypeImportOnDemandDeclaration
#line 147 "parser.y"
                                          { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt;}
#line default
        break;
      case 11: // SingleTypeImportDeclaration -> IMPORT, TypeName, ';'
#line 151 "parser.y"
                                  { CurrentSemanticValue.stmt = new SingleTypeImportDeclaration(ValueStack[ValueStack.Depth-2].name); }
#line default
        break;
      case 12: // TypeImportOnDemandDeclaration -> IMPORT, PackageOrTypeName, '.', '*', ';'
#line 155 "parser.y"
                                                 { CurrentSemanticValue.stmt = new TypeImportOnDemandDeclaration(ValueStack[ValueStack.Depth-4].name); }
#line default
        break;
      case 17: // TypeDeclarations -> TypeDeclarations, TypeDeclaration
#line 169 "parser.y"
                                          { CurrentSemanticValue.stmts = ValueStack[ValueStack.Depth-2].stmts; CurrentSemanticValue.stmts.Add(ValueStack[ValueStack.Depth-1].stmt); }
#line default
        break;
      case 18: // TypeDeclarations -> /* empty */
#line 170 "parser.y"
                          { CurrentSemanticValue.stmts = new List<Statement>();}
#line default
        break;
      case 19: // TypeDeclaration -> ClassDeclaration
#line 174 "parser.y"
                                                            { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 20: // ClassDeclaration -> NormalClassDeclaration
#line 178 "parser.y"
                                                             { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 21: // NormalClassDeclaration -> ClassModifiers, CLASS, IDENTIFIER, TypeParameters_opt, 
               //                           Superclass_opt, Superinterfaces_opt, ClassBody
#line 182 "parser.y"
                                                                                                    {  CurrentSemanticValue.stmt = new ClassDeclaration(ValueStack[ValueStack.Depth-5].name,ValueStack[ValueStack.Depth-7].modfs,ValueStack[ValueStack.Depth-1].stmts); }
#line default
        break;
      case 22: // ClassModifiers -> ClassModifiers, ClassModifier
#line 186 "parser.y"
                                       { CurrentSemanticValue.modfs = ValueStack[ValueStack.Depth-2].modfs; CurrentSemanticValue.modfs.Add(ValueStack[ValueStack.Depth-1].modf); }
#line default
        break;
      case 23: // ClassModifiers -> /* empty */
#line 187 "parser.y"
                          { CurrentSemanticValue.modfs = new List<Modifier>(); }
#line default
        break;
      case 24: // ClassModifier -> PUBLIC
#line 191 "parser.y"
                      { CurrentSemanticValue.modf = Modifier.PUBLIC; }
#line default
        break;
      case 25: // ClassModifier -> PROTECTED
#line 192 "parser.y"
                         { CurrentSemanticValue.modf = Modifier.PROTECTED; }
#line default
        break;
      case 26: // ClassModifier -> PRIVATE
#line 193 "parser.y"
                        { CurrentSemanticValue.modf = Modifier.PRIVATE; }
#line default
        break;
      case 27: // ClassModifier -> ABSTRACT
#line 194 "parser.y"
                         { CurrentSemanticValue.modf = Modifier.ABSTRACT; }
#line default
        break;
      case 28: // ClassModifier -> STATIC
#line 195 "parser.y"
                       { CurrentSemanticValue.modf = Modifier.STATIC; }
#line default
        break;
      case 29: // ClassModifier -> FINAL
#line 196 "parser.y"
                      { CurrentSemanticValue.modf = Modifier.FINAL; }
#line default
        break;
      case 30: // ClassModifier -> STRICTFP
#line 197 "parser.y"
                         { CurrentSemanticValue.modf = Modifier.STRICTFP; }
#line default
        break;
      case 31: // TypeParameters_opt -> /* empty */
#line 202 "parser.y"
                                        { CurrentSemanticValue.expr = null; }
#line default
        break;
      case 32: // Superclass_opt -> /* empty */
#line 205 "parser.y"
                                     { CurrentSemanticValue.expr = null; }
#line default
        break;
      case 33: // Superinterfaces_opt -> /* empty */
#line 208 "parser.y"
                                         { CurrentSemanticValue.expr = null; }
#line default
        break;
      case 34: // ClassBody -> '{', ClassBodyDeclarations, '}'
#line 212 "parser.y"
                                        { CurrentSemanticValue.stmts = ValueStack[ValueStack.Depth-2].stmts; }
#line default
        break;
      case 35: // ClassBodyDeclarations -> ClassBodyDeclarations, ClassBodyDeclaration
#line 219 "parser.y"
                                                 { CurrentSemanticValue.stmts = ValueStack[ValueStack.Depth-2].stmts; CurrentSemanticValue.stmts.Add(ValueStack[ValueStack.Depth-1].stmt); }
#line default
        break;
      case 36: // ClassBodyDeclarations -> /* empty */
#line 220 "parser.y"
                          { CurrentSemanticValue.stmts = new List<Statement>(); }
#line default
        break;
      case 37: // ClassBodyDeclaration -> ClassMemberDeclaration
#line 224 "parser.y"
                                  { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 38: // ClassMemberDeclaration -> MethodDeclaration
#line 229 "parser.y"
                               { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 39: // MethodDeclaration -> MethodModifiers, MethodHeader, MethodBody
#line 234 "parser.y"
                                               { CurrentSemanticValue.stmt = new MethodDeclaration( (string)((ArrayList)ValueStack[ValueStack.Depth-2].arrlst[1])[0], ValueStack[ValueStack.Depth-3].modfs, ValueStack[ValueStack.Depth-1].stmt, (AST.Type)ValueStack[ValueStack.Depth-2].arrlst[0], (List<Statement>)((ArrayList)ValueStack[ValueStack.Depth-2].arrlst[1])[1]); }
#line default
        break;
      case 40: // MethodModifiers -> MethodModifiers, MethodModifier
#line 238 "parser.y"
                                              { CurrentSemanticValue.modfs = ValueStack[ValueStack.Depth-2].modfs; CurrentSemanticValue.modfs.Add(ValueStack[ValueStack.Depth-1].modf); }
#line default
        break;
      case 41: // MethodModifiers -> /* empty */
#line 239 "parser.y"
                          { CurrentSemanticValue.modfs = new List<Modifier>(); }
#line default
        break;
      case 42: // MethodModifier -> PUBLIC
#line 243 "parser.y"
                      { CurrentSemanticValue.modf = Modifier.PUBLIC; }
#line default
        break;
      case 43: // MethodModifier -> STATIC
#line 244 "parser.y"
                            { CurrentSemanticValue.modf = Modifier.STATIC; }
#line default
        break;
      case 44: // MethodHeader -> Result, MethodDeclarator, Throws_opt
#line 248 "parser.y"
                                           {CurrentSemanticValue.arrlst = new ArrayList() { ValueStack[ValueStack.Depth-3].type, ValueStack[ValueStack.Depth-2].arrlst, ValueStack[ValueStack.Depth-1].stmt } ; }
#line default
        break;
      case 45: // Result -> VOID
#line 256 "parser.y"
                     {CurrentSemanticValue.type = new NamedType("VOID"); }
#line default
        break;
      case 46: // Result -> UnannType
#line 257 "parser.y"
                         {CurrentSemanticValue.type = ValueStack[ValueStack.Depth-1].type; }
#line default
        break;
      case 47: // Throws_opt -> Empty
#line 261 "parser.y"
                      {CurrentSemanticValue.stmt = null; }
#line default
        break;
      case 48: // MethodDeclarator -> IDENTIFIER, '(', FormalParameterList_Opt, ')', Dims_Opt
#line 266 "parser.y"
                                                        {CurrentSemanticValue.arrlst =  new ArrayList() { ValueStack[ValueStack.Depth-5].name, ValueStack[ValueStack.Depth-3].stmts, ValueStack[ValueStack.Depth-1] };}
#line default
        break;
      case 49: // FormalParameterList_Opt -> FormalParameterList
#line 271 "parser.y"
                                { CurrentSemanticValue.stmts = ValueStack[ValueStack.Depth-1].stmts; }
#line default
        break;
      case 50: // FormalParameterList_Opt -> /* empty */
#line 272 "parser.y"
                          { CurrentSemanticValue.stmts = null; }
#line default
        break;
      case 51: // FormalParameterList -> FormalParameters
#line 279 "parser.y"
                               { CurrentSemanticValue.stmts = ValueStack[ValueStack.Depth-1].stmts; }
#line default
        break;
      case 52: // FormalParameters -> FormalParameter
#line 283 "parser.y"
                              { CurrentSemanticValue.stmts = new List<Statement> { ValueStack[ValueStack.Depth-1].stmt }; }
#line default
        break;
      case 53: // FormalParameters -> FormalParameters, ',', FormalParameter
#line 284 "parser.y"
                                             { CurrentSemanticValue.stmts = ValueStack[ValueStack.Depth-3].stmts; CurrentSemanticValue.stmts.Add(ValueStack[ValueStack.Depth-1].stmt); }
#line default
        break;
      case 54: // FormalParameter -> VariableModifiers, UnannType, VariableDeclaratorId
#line 288 "parser.y"
                                                       { CurrentSemanticValue.stmt = new VariableDeclaration(ValueStack[ValueStack.Depth-2].type, ValueStack[ValueStack.Depth-1].name); }
#line default
        break;
      case 55: // VariableModifiers -> VariableModifiers, VariableModifier
#line 291 "parser.y"
                                           { CurrentSemanticValue.modfs = ValueStack[ValueStack.Depth-2].modfs; CurrentSemanticValue.modfs.Add(ValueStack[ValueStack.Depth-1].modf); }
#line default
        break;
      case 56: // VariableModifiers -> /* empty */
#line 292 "parser.y"
                          { CurrentSemanticValue.modfs = new List<Modifier>(); }
#line default
        break;
      case 57: // VariableModifier -> FINAL
#line 296 "parser.y"
                      { CurrentSemanticValue.modf = Modifier.FINAL; }
#line default
        break;
      case 58: // Dims_Opt -> Dims
#line 302 "parser.y"
                     { CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
#line default
        break;
      case 59: // Dims_Opt -> /* empty */
#line 303 "parser.y"
                          { }
#line default
        break;
      case 61: // UnannType -> UnannReferenceType
#line 312 "parser.y"
                               { CurrentSemanticValue.type = ValueStack[ValueStack.Depth-1].type; }
#line default
        break;
      case 62: // UnannType -> UnannPrimitiveType
#line 313 "parser.y"
                               { CurrentSemanticValue.type = ValueStack[ValueStack.Depth-1].type; }
#line default
        break;
      case 63: // UnannPrimitiveType -> NumericType
#line 317 "parser.y"
                          { CurrentSemanticValue.type = ValueStack[ValueStack.Depth-1].type; }
#line default
        break;
      case 64: // UnannPrimitiveType -> BOOLEAN
#line 318 "parser.y"
                       { CurrentSemanticValue.type = new NamedType("BOOLEAN"); }
#line default
        break;
      case 69: // NumericType -> IntegralType
#line 338 "parser.y"
                           { CurrentSemanticValue.type = ValueStack[ValueStack.Depth-1].type; }
#line default
        break;
      case 70: // NumericType -> FloatingPointType
#line 339 "parser.y"
                               { CurrentSemanticValue.type = ValueStack[ValueStack.Depth-1].type; }
#line default
        break;
      case 71: // IntegralType -> BYTE
#line 343 "parser.y"
                     { CurrentSemanticValue.type = new NamedType("BYTE");  }
#line default
        break;
      case 72: // IntegralType -> SHORT
#line 344 "parser.y"
                      { CurrentSemanticValue.type = new NamedType("SHORT");  }
#line default
        break;
      case 73: // IntegralType -> INT
#line 345 "parser.y"
                    { CurrentSemanticValue.type = new NamedType("INT");}
#line default
        break;
      case 74: // IntegralType -> LONG
#line 346 "parser.y"
                     { CurrentSemanticValue.type = new NamedType("LONG"); }
#line default
        break;
      case 75: // IntegralType -> CHAR
#line 347 "parser.y"
                     { CurrentSemanticValue.type = new NamedType("CHAR"); }
#line default
        break;
      case 76: // FloatingPointType -> FLOAT
#line 351 "parser.y"
                      { CurrentSemanticValue.type = new NamedType("FLOAT"); }
#line default
        break;
      case 77: // FloatingPointType -> DOUBLE
#line 352 "parser.y"
                      { CurrentSemanticValue.type = new NamedType("DOUBLE"); }
#line default
        break;
      case 78: // UnannReferenceType -> UnannArrayType
#line 356 "parser.y"
                            { CurrentSemanticValue.type = ValueStack[ValueStack.Depth-1].type; }
#line default
        break;
      case 79: // UnannArrayType -> UnannTypeVariable, Dims
#line 362 "parser.y"
                                  { CurrentSemanticValue.type = new ArrayType(ValueStack[ValueStack.Depth-2].type); }
#line default
        break;
      case 80: // UnannTypeVariable -> IDENTIFIER
#line 366 "parser.y"
                         { CurrentSemanticValue.type = new NamedType(ValueStack[ValueStack.Depth-1].name); }
#line default
        break;
      case 81: // MethodBody -> Block
#line 371 "parser.y"
                       { CurrentSemanticValue.stmt= ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 82: // MethodBody -> ';'
#line 372 "parser.y"
                    { CurrentSemanticValue.stmt= null;}
#line default
        break;
      case 83: // Block -> '{', BlockStatements_Opt, '}'
#line 382 "parser.y"
                                      { CurrentSemanticValue.stmt = new BlockStatement(ValueStack[ValueStack.Depth-2].stmts); }
#line default
        break;
      case 84: // BlockStatements_Opt -> BlockStatements
#line 386 "parser.y"
                             { CurrentSemanticValue.stmts = ValueStack[ValueStack.Depth-1].stmts; }
#line default
        break;
      case 85: // BlockStatements_Opt -> /* empty */
#line 387 "parser.y"
                          { CurrentSemanticValue.stmts = null; }
#line default
        break;
      case 86: // BlockStatements -> BlockStatement
#line 391 "parser.y"
                            { CurrentSemanticValue.stmts = new List<Statement> { ValueStack[ValueStack.Depth-1].stmt }; }
#line default
        break;
      case 87: // BlockStatements -> BlockStatements, BlockStatement
#line 392 "parser.y"
                                        { CurrentSemanticValue.stmts = ValueStack[ValueStack.Depth-2].stmts; CurrentSemanticValue.stmts.Add(ValueStack[ValueStack.Depth-1].stmt); }
#line default
        break;
      case 88: // BlockStatement -> LocalVariableDeclarationStatement
#line 396 "parser.y"
                                           { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 89: // BlockStatement -> Statement
#line 397 "parser.y"
                         { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 90: // LocalVariableDeclarationStatement -> LocalVariableDeclaration, ';'
#line 401 "parser.y"
                                       { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-2].stmt; }
#line default
        break;
      case 91: // LocalVariableDeclaration -> UnannType, VariableDeclaratorList
#line 405 "parser.y"
                                          { CurrentSemanticValue.stmt = new VariableDeclarationList(ValueStack[ValueStack.Depth-2].type, ValueStack[ValueStack.Depth-1].strlst); }
#line default
        break;
      case 92: // VariableDeclaratorList -> VariableDeclarator
#line 411 "parser.y"
                               { CurrentSemanticValue.strlst = new List<string> { ValueStack[ValueStack.Depth-1].name }; }
#line default
        break;
      case 93: // VariableDeclaratorList -> VariableDeclaratorList, ',', VariableDeclarator
#line 412 "parser.y"
                                                    { CurrentSemanticValue.strlst = ValueStack[ValueStack.Depth-3].strlst; CurrentSemanticValue.strlst.Add(ValueStack[ValueStack.Depth-1].name); }
#line default
        break;
      case 94: // VariableDeclarator -> VariableDeclaratorId
#line 416 "parser.y"
                                 { CurrentSemanticValue.name = ValueStack[ValueStack.Depth-1].name; }
#line default
        break;
      case 95: // VariableDeclaratorId -> IDENTIFIER, Dims_Opt
#line 420 "parser.y"
                                { CurrentSemanticValue.name = ValueStack[ValueStack.Depth-2].name; }
#line default
        break;
      case 96: // Statement -> StatementWithoutTrailingSubstatement
#line 424 "parser.y"
                                             { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 97: // Statement -> IfThenStatement
#line 425 "parser.y"
                             {CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 98: // Statement -> IfThenElseStatement
#line 426 "parser.y"
                                {CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 99: // Statement -> WhileStatement
#line 427 "parser.y"
                            { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 100: // Statement -> LabeledStatement
#line 428 "parser.y"
                               { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt;}
#line default
        break;
      case 101: // StatementNoShortIf -> StatementWithoutTrailingSubstatement
#line 432 "parser.y"
                                             {CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 102: // StatementNoShortIf -> IfThenElseStatementNoShortIf
#line 433 "parser.y"
                                       {CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 103: // StatementWithoutTrailingSubstatement -> ExpressionStatement
#line 438 "parser.y"
                                 { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 104: // StatementWithoutTrailingSubstatement -> Block
#line 439 "parser.y"
                      { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 105: // StatementWithoutTrailingSubstatement -> BreakStatement
#line 440 "parser.y"
                            { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt;}
#line default
        break;
      case 106: // StatementWithoutTrailingSubstatement -> DoStatement
#line 441 "parser.y"
                          { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 107: // StatementWithoutTrailingSubstatement -> ContinueStatement
#line 442 "parser.y"
                               { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt;}
#line default
        break;
      case 108: // StatementWithoutTrailingSubstatement -> ReturnStatement
#line 443 "parser.y"
                             { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt;}
#line default
        break;
      case 109: // StatementWithoutTrailingSubstatement -> ThrowStatement
#line 444 "parser.y"
                            { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt;}
#line default
        break;
      case 110: // StatementWithoutTrailingSubstatement -> SynchronizedStatement
#line 445 "parser.y"
                                  { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt;}
#line default
        break;
      case 111: // StatementWithoutTrailingSubstatement -> SwitchStatement
#line 446 "parser.y"
                             { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt;}
#line default
        break;
      case 112: // StatementWithoutTrailingSubstatement -> AssertStatement
#line 447 "parser.y"
                             { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt;}
#line default
        break;
      case 113: // AssertStatement -> ASSERT, Expression, ';'
#line 451 "parser.y"
                                  { CurrentSemanticValue.stmt = new AssertStatement(ValueStack[ValueStack.Depth-2].expr);}
#line default
        break;
      case 114: // AssertStatement -> ASSERT, Expression, ':', Expression, ';'
#line 452 "parser.y"
                                             { CurrentSemanticValue.stmt = new AssertStatement(ValueStack[ValueStack.Depth-4].expr, ValueStack[ValueStack.Depth-2].expr);}
#line default
        break;
      case 115: // SwitchStatement -> SWITCH, '(', Expression, ')'
#line 456 "parser.y"
                                     { CurrentSemanticValue.stmt = new SwitchStatement(ValueStack[ValueStack.Depth-2].expr); }
#line default
        break;
      case 116: // DoStatement -> DO, Statement, WHILE, '(', Expression, ')', ';'
#line 460 "parser.y"
                                                 { CurrentSemanticValue.stmt = new DoStatement(ValueStack[ValueStack.Depth-6].stmt, ValueStack[ValueStack.Depth-3].expr); }
#line default
        break;
      case 117: // ThrowStatement -> THROW, Expression, ';'
#line 464 "parser.y"
                                 { CurrentSemanticValue.stmt = new ThrowStatement(ValueStack[ValueStack.Depth-2].expr); }
#line default
        break;
      case 118: // SynchronizedStatement -> SYNCHRONIZED, '(', Expression, ')', Block
#line 468 "parser.y"
                                              { CurrentSemanticValue.stmt = new SynchronizedStatement(ValueStack[ValueStack.Depth-3].expr, ValueStack[ValueStack.Depth-1].stmt); }
#line default
        break;
      case 119: // ExpressionStatement -> StatementExpression, ';'
#line 472 "parser.y"
                                   { CurrentSemanticValue.stmt = new ExpressionStatement(ValueStack[ValueStack.Depth-2].expr); }
#line default
        break;
      case 120: // StatementExpression -> Assignment
#line 476 "parser.y"
                         { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 121: // IfThenStatement -> IF, '(', Expression, ')', Statement
#line 480 "parser.y"
                                         { CurrentSemanticValue.stmt = new IfStatement(ValueStack[ValueStack.Depth-3].expr, ValueStack[ValueStack.Depth-1].stmt,null); }
#line default
        break;
      case 122: // IfThenElseStatement -> IF, '(', Expression, ')', StatementNoShortIf, ELSE, 
                //                        Statement
#line 485 "parser.y"
                                                               { CurrentSemanticValue.stmt = new IfStatement(ValueStack[ValueStack.Depth-5].expr, ValueStack[ValueStack.Depth-3].stmt, ValueStack[ValueStack.Depth-1].stmt); }
#line default
        break;
      case 123: // IfThenElseStatementNoShortIf -> IF, '(', Expression, ')', StatementNoShortIf, 
                //                                 ELSE, StatementNoShortIf
#line 489 "parser.y"
                                                                      { CurrentSemanticValue.stmt = new IfStatement(ValueStack[ValueStack.Depth-5].expr, ValueStack[ValueStack.Depth-3].stmt, ValueStack[ValueStack.Depth-1].stmt); }
#line default
        break;
      case 124: // WhileStatement -> WHILE, '(', Expression, ')', Statement
#line 493 "parser.y"
                                           { CurrentSemanticValue.stmt = new WhileStatement(ValueStack[ValueStack.Depth-3].expr, ValueStack[ValueStack.Depth-1].stmt); }
#line default
        break;
      case 125: // TryStatement -> TRY, Block, Catches
#line 497 "parser.y"
                               { CurrentSemanticValue.stmt = new TryStatement(ValueStack[ValueStack.Depth-2].stmt, ValueStack[ValueStack.Depth-1].stmt, null); }
#line default
        break;
      case 126: // TryStatement -> TRY, Block, Catches_opt, Finally
#line 498 "parser.y"
                                        { CurrentSemanticValue.stmt = new TryStatement(ValueStack[ValueStack.Depth-3].stmt, ValueStack[ValueStack.Depth-2].stmt, ValueStack[ValueStack.Depth-1].stmt); }
#line default
        break;
      case 127: // Catches_opt -> Catches
#line 503 "parser.y"
                       { CurrentSemanticValue.stmt =  ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 128: // Catches_opt -> /* empty */
#line 504 "parser.y"
                          { }
#line default
        break;
      case 129: // Catches -> CatchClause
#line 508 "parser.y"
                          { CurrentSemanticValue.stmt =  ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 130: // CatchClause -> CATCH, '(', ')', Block
#line 515 "parser.y"
                                 { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 131: // Finally -> FINALLY, Block
#line 533 "parser.y"
                            { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 132: // IfThenStatement -> IF, '(', Expression, ')', Statement
#line 541 "parser.y"
                                         { CurrentSemanticValue.stmt = new IfStatement(ValueStack[ValueStack.Depth-3].expr, ValueStack[ValueStack.Depth-1].stmt,null); }
#line default
        break;
      case 133: // IfThenElseStatement -> IF, '(', Expression, ')', StatementNoShortIf, ELSE, 
                //                        Statement
#line 546 "parser.y"
                                                               { CurrentSemanticValue.stmt = new IfStatement(ValueStack[ValueStack.Depth-5].expr, ValueStack[ValueStack.Depth-3].stmt, ValueStack[ValueStack.Depth-1].stmt); }
#line default
        break;
      case 134: // IfThenElseStatementNoShortIf -> IF, '(', Expression, ')', StatementNoShortIf, 
                //                                 ELSE, StatementNoShortIf
#line 550 "parser.y"
                                                                      { CurrentSemanticValue.stmt = new IfStatement(ValueStack[ValueStack.Depth-5].expr, ValueStack[ValueStack.Depth-3].stmt, ValueStack[ValueStack.Depth-1].stmt); }
#line default
        break;
      case 135: // WhileStatement -> WHILE, '(', Expression, ')', Statement
#line 554 "parser.y"
                                           { CurrentSemanticValue.stmt = new WhileStatement(ValueStack[ValueStack.Depth-3].expr, ValueStack[ValueStack.Depth-1].stmt); }
#line default
        break;
      case 136: // LabeledStatement -> IDENTIFIER, ':', Statement
#line 559 "parser.y"
                                    { CurrentSemanticValue.stmt = new LabeledStatement(ValueStack[ValueStack.Depth-3].name,ValueStack[ValueStack.Depth-1].stmt);}
#line default
        break;
      case 137: // BreakStatement -> BREAK, Identifier_opt, ';'
#line 564 "parser.y"
                                     { if(ValueStack[ValueStack.Depth-2].name == null){CurrentSemanticValue.stmt = new BreakStatement();} else {CurrentSemanticValue.stmt = new BreakStatement(ValueStack[ValueStack.Depth-2].name);} }
#line default
        break;
      case 140: // ContinueStatement -> CONTINUE, Identifier_opt, ';'
#line 575 "parser.y"
                                        { if(ValueStack[ValueStack.Depth-2].name == null){CurrentSemanticValue.stmt = new ContinueStatement();} else {CurrentSemanticValue.stmt = new ContinueStatement(ValueStack[ValueStack.Depth-2].name);} }
#line default
        break;
      case 141: // ReturnStatement -> RETURN, Expression_opt, ';'
#line 580 "parser.y"
                                      { if(ValueStack[ValueStack.Depth-2].expr == null){CurrentSemanticValue.stmt = new ReturnStatement();} else {CurrentSemanticValue.stmt = new ReturnStatement(ValueStack[ValueStack.Depth-2].expr);} }
#line default
        break;
      case 142: // Expression_opt -> Expression
#line 585 "parser.y"
                          { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 144: // Assignment -> LeftHandSide, AssignmentOperator, Expression
#line 593 "parser.y"
                                                 { CurrentSemanticValue.expr = new AssignmentExpression(ValueStack[ValueStack.Depth-3].expr, ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 145: // LeftHandSide -> ExpressionName
#line 597 "parser.y"
                            { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 146: // ExpressionName -> IDENTIFIER
#line 601 "parser.y"
                         { CurrentSemanticValue.expr = new VariableExpression(ValueStack[ValueStack.Depth-1].name);  }
#line default
        break;
      case 148: // AssignmentExpression -> Assignment
#line 609 "parser.y"
                         { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 149: // AssignmentExpression -> ConditionalExpression
#line 610 "parser.y"
                                  { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 150: // Primary -> PrimaryNoNewArray
#line 614 "parser.y"
                               { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 151: // PrimaryNoNewArray -> Literal
#line 618 "parser.y"
                       { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 152: // Literal -> IntegerLiteral
#line 622 "parser.y"
                            { CurrentSemanticValue.expr = new IntegerLiteralExpression(ValueStack[ValueStack.Depth-1].num); }
#line default
        break;
      case 153: // Literal -> FloatingPointLiteral
#line 623 "parser.y"
                                 { CurrentSemanticValue.expr = new FloatingPointLiteralExpression(ValueStack[ValueStack.Depth-1].floatnum); }
#line default
        break;
      case 154: // Literal -> BooleanLiteral
#line 624 "parser.y"
                            { CurrentSemanticValue.expr = new BooleanLiteralExpression(ValueStack[ValueStack.Depth-1].boolval); }
#line default
        break;
      case 155: // Literal -> CharacterLiteral
#line 625 "parser.y"
                              { CurrentSemanticValue.expr = new CharacterLiteralExpression(ValueStack[ValueStack.Depth-1].charval); }
#line default
        break;
      case 156: // Literal -> StringLiteral
#line 626 "parser.y"
                            { CurrentSemanticValue.expr = new StringLiteralExpression(ValueStack[ValueStack.Depth-1].name); }
#line default
        break;
      case 157: // Literal -> NullLiteral
#line 627 "parser.y"
                          { CurrentSemanticValue.expr = new NullLiteralExpression(); }
#line default
        break;
      case 158: // Expression -> LambdaExpression
#line 633 "parser.y"
                              { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 159: // Expression -> AssignmentExpression
#line 634 "parser.y"
                                 { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 160: // LambdaExpression -> LambdaParameters, ARROW, LambdaBody
#line 638 "parser.y"
                                           { }
#line default
        break;
      case 161: // LambdaParameters -> /* empty */
#line 642 "parser.y"
                          { }
#line default
        break;
      case 162: // LambdaBody -> /* empty */
#line 646 "parser.y"
                          { }
#line default
        break;
      case 163: // ConditionalExpression -> ConditionalOrExpression
#line 650 "parser.y"
                                       { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 164: // ConditionalOrExpression -> ConditionalAndExpression
#line 656 "parser.y"
                                      { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 165: // ConditionalOrExpression -> ConditionalOrExpression, LOGICAL_OR, 
                //                            ConditionalAndExpression
#line 657 "parser.y"
                                                                { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, "||", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 166: // ConditionalAndExpression -> InclusiveOrExpression
#line 661 "parser.y"
                                    { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 167: // ConditionalAndExpression -> ConditionalAndExpression, LOGICAL_AND, 
                //                             InclusiveOrExpression
#line 662 "parser.y"
                                                               { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, "&&", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 168: // InclusiveOrExpression -> ExclusiveOrExpression
#line 666 "parser.y"
                                    { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 169: // InclusiveOrExpression -> InclusiveOrExpression, '|', ExclusiveOrExpression
#line 667 "parser.y"
                                                       { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, "|", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 170: // ExclusiveOrExpression -> AndExpression
#line 671 "parser.y"
                              { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 171: // ExclusiveOrExpression -> ExclusiveOrExpression, '^', AndExpression
#line 672 "parser.y"
                                                 { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, "^", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 172: // AndExpression -> EqualityExpression
#line 676 "parser.y"
                                 { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 173: // AndExpression -> AndExpression, '&', EqualityExpression
#line 677 "parser.y"
                                               { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, "&", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 174: // EqualityExpression -> RelationalExpression
#line 681 "parser.y"
                                   { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 175: // EqualityExpression -> EqualityExpression, EQUAL, RelationalExpression
#line 682 "parser.y"
                                                      { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, "==", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 176: // EqualityExpression -> EqualityExpression, NOT_EQUAL, RelationalExpression
#line 683 "parser.y"
                                                         { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, "!=", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 177: // RelationalExpression -> ShiftExpression
#line 687 "parser.y"
                               { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 178: // RelationalExpression -> RelationalExpression, '<', ShiftExpression
#line 688 "parser.y"
                                                  { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, "<", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 179: // RelationalExpression -> RelationalExpression, '>', ShiftExpression
#line 689 "parser.y"
                                                  { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, ">", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 180: // RelationalExpression -> RelationalExpression, LESS_THAN_OR_EQUAL, 
                //                         ShiftExpression
#line 690 "parser.y"
                                                             { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, "<=", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 181: // RelationalExpression -> RelationalExpression, GREATER_OR_EQUAL, ShiftExpression
#line 691 "parser.y"
                                                            { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, ">=", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 182: // RelationalExpression -> RelationalExpression, INSTANCEOF, ReferenceType
#line 692 "parser.y"
                                                      { CurrentSemanticValue.expr = new InstanceOfExpression(ValueStack[ValueStack.Depth-3].expr, ValueStack[ValueStack.Depth-1].type); }
#line default
        break;
      case 183: // ShiftExpression -> AdditiveExpression
#line 696 "parser.y"
                                 { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 184: // ShiftExpression -> ShiftExpression, LEFT_SHIFT, AdditiveExpression
#line 697 "parser.y"
                                                      { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, "<<", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 185: // ShiftExpression -> ShiftExpression, SIGNED_RIGHT_SHIFT, AdditiveExpression
#line 698 "parser.y"
                                                            { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, ">>", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 186: // ShiftExpression -> ShiftExpression, UNSIGNED_RIGHT_SHIFT, AdditiveExpression
#line 699 "parser.y"
                                                             { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, ">>>", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 187: // AdditiveExpression -> MultiplicativeExpression
#line 703 "parser.y"
                                     { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 188: // AdditiveExpression -> AdditiveExpression, '+', MultiplicativeExpression
#line 704 "parser.y"
                                                      { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, "+", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 189: // AdditiveExpression -> AdditiveExpression, '-', MultiplicativeExpression
#line 705 "parser.y"
                                                      { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, "-", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 190: // MultiplicativeExpression -> UnaryExpression
#line 709 "parser.y"
                               { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 191: // MultiplicativeExpression -> MultiplicativeExpression, '*', UnaryExpression
#line 710 "parser.y"
                                                     { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, "*", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 192: // MultiplicativeExpression -> MultiplicativeExpression, '/', UnaryExpression
#line 711 "parser.y"
                                                     { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, "/", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 193: // MultiplicativeExpression -> MultiplicativeExpression, '%', UnaryExpression
#line 712 "parser.y"
                                                     { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, "%", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 194: // UnaryExpression -> PreIncrementExpression
#line 716 "parser.y"
                                    { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 195: // UnaryExpression -> PreDecrementExpression
#line 717 "parser.y"
                                   { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 196: // UnaryExpression -> '+', UnaryExpression
#line 718 "parser.y"
                                 { CurrentSemanticValue.expr = new PreUnaryExpression("+", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 197: // UnaryExpression -> '-', UnaryExpression
#line 719 "parser.y"
                                 { CurrentSemanticValue.expr = new PreUnaryExpression("-", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 198: // UnaryExpression -> UnaryExpressionNotPlusMinus
#line 720 "parser.y"
                                       { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 199: // PreIncrementExpression -> INCREMENT, UnaryExpression
#line 728 "parser.y"
                                      { CurrentSemanticValue.expr = new PreUnaryExpression("++", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 200: // PreDecrementExpression -> DECREMENT, UnaryExpression
#line 732 "parser.y"
                                      { CurrentSemanticValue.expr = new PreUnaryExpression("--", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 201: // UnaryExpressionNotPlusMinus -> PostfixExpression
#line 736 "parser.y"
                                { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr;}
#line default
        break;
      case 202: // UnaryExpressionNotPlusMinus -> '~', UnaryExpression
#line 737 "parser.y"
                                 { CurrentSemanticValue.expr = new PreUnaryExpression("~", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 203: // UnaryExpressionNotPlusMinus -> '!', UnaryExpression
#line 738 "parser.y"
                                 { CurrentSemanticValue.expr = new PreUnaryExpression("!", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 204: // UnaryExpressionNotPlusMinus -> CastExpression
#line 739 "parser.y"
                             { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr;}
#line default
        break;
      case 205: // PostfixExpression -> Primary
#line 743 "parser.y"
                        { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 206: // PostfixExpression -> ExpressionName
#line 744 "parser.y"
                             { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 207: // PostfixExpression -> PostIncrementExpression
#line 745 "parser.y"
                                    { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 208: // PostfixExpression -> PostDecrementExpression
#line 746 "parser.y"
                                    { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 209: // PostIncrementExpression -> PostfixExpression, INCREMENT
#line 750 "parser.y"
                                        { CurrentSemanticValue.expr = new PostUnaryExpression(ValueStack[ValueStack.Depth-2].expr, "++"); }
#line default
        break;
      case 210: // PostDecrementExpression -> PostfixExpression, DECREMENT
#line 754 "parser.y"
                                        { CurrentSemanticValue.expr = new PostUnaryExpression(ValueStack[ValueStack.Depth-2].expr, "--"); }
#line default
        break;
      case 211: // CastExpression -> '(', PrimitiveType, ')', UnaryExpression
#line 758 "parser.y"
                                                   { CurrentSemanticValue.expr = new CastExpression(ValueStack[ValueStack.Depth-3].type, ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
    }
#pragma warning restore 162, 1522
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliases != null && aliases.ContainsKey(terminal))
        return aliases[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }

#line 777 "parser.y"

public Parser(Scanner scanner) : base(scanner)
{
}
#line default
}
}
