// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, John Gough, QUT 2005-2014
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.5.2
// Machine:  VDI-VL17-043
// DateTime: 13/05/2017 4:42:49 PM
// UserName: n9540377
// Input file <parser.y - 13/05/2017 4:42:45 PM>

// options: conflicts lines gplex conflicts

using System;
using System.Collections.Generic;
using System.CodeDom.Compiler;
using System.Globalization;
using System.Text;
using QUT.Gppg;
using System.Collections;
using IFN660_Java_ECMAScript.AST;

namespace IFN660_Java_ECMAScript
{
public enum Tokens {error=128,EOF=129,NUMBER=130,IDENTIFIER=131,ABSTRACT=132,
    CONTINUE=133,FOR=134,NEW=135,SWITCH=136,ASSERT=137,DEFAULT=138,
    IF=139,PACKAGE=140,SYNCHRONIZED=141,BOOLEAN=142,DO=143,GOTO=144,
    PRIVATE=145,THIS=146,BREAK=147,DOUBLE=148,IMPLEMENTS=149,PROTECTED=150,
    THROW=151,BYTE=152,ELSE=153,IMPORT=154,PUBLIC=155,THROWS=156,
    CASE=157,ENUM=158,INSTANCEOF=159,RETURN=160,TRANSIENT=161,CATCH=162,
    EXTENDS=163,INT=164,SHORT=165,TRY=166,CHAR=167,FINAL=168,
    INTERFACE=169,STATIC=170,VOID=171,CLASS=172,FINALLY=173,LONG=174,
    STRICTFP=175,VOLATILE=176,CONST=177,FLOAT=178,NATIVE=179,SUPER=180,
    WHILE=181,IntegerLiteral=182,FloatingPointLiteral=183,BooleanLiteral=184,CharacterLiteral=185,StringLiteral=186,
    NullLiteral=187,ELLIPSIS=188,DOUBLE_COLON=189,EQUAL=190,GREATER_OR_EQUAL=191,LESS_THAN_OR_EQUAL=192,
    NOT_EQUAL=193,ARROW=194,LOGICAL_AND=195,LOGICAL_OR=196,INCREMENT=197,DECREMENT=198,
    LEFT_SHIFT=199,SIGNED_RIGHT_SHIFT=200,UNSIGNED_RIGHT_SHIFT=201,ADDITION_ASSIGNMENT=202,SUBTRACTION_ASSIGNMENT=203,MULTIPLICATION_ASSIGNMENT=204,
    DIVISION_ASSIGNMENT=205,MODULUS_ASSIGNMENT=206,BITWISE_AND_ASSIGNMENT=207,BITWISE_OR_ASSIGNMENT=208,BITWISE_XOR_ASSIGNMENT=209,LEFT_SHIFT_ASSIGNMENT=210,
    UNSIGNED_RIGHT_SHIFT_ASSIGNMENT=211,SIGNED_RIGHT_SHIFT_ASSIGNMENT=212};

public struct ValueType
#line 11 "parser.y"
{
    public long num;
	public double floatnum;
	public bool boolval;
	public char charval;
    public string name;
	public Statement stmt;
	public List<Statement> stmts;
	public Expression expr;
	public AST.Type type;
	public Modifier modf;
	public List<Modifier> modfs;
	public ArrayList arrlst;
	public List<string> strlst;
}
#line default
// Abstract base class for GPLEX scanners
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public abstract class ScanBase : AbstractScanner<ValueType,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

// Utility class for encapsulating token information
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public class ScanObj {
  public int token;
  public ValueType yylval;
  public LexLocation yylloc;
  public ScanObj( int t, ValueType val, LexLocation loc ) {
    this.token = t; this.yylval = val; this.yylloc = loc;
  }
}

[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public class Parser: ShiftReduceParser<ValueType, LexLocation>
{
  // Verbatim content from parser.y - 13/05/2017 4:42:45 PM
#line 7 "parser.y"
public static Statement root;
#line default
  // End verbatim content from parser.y - 13/05/2017 4:42:45 PM

#pragma warning disable 649
  private static Dictionary<int, string> aliases;
#pragma warning restore 649
  private static Rule[] rules = new Rule[192];
  private static State[] states = new State[271];
  private static string[] nonTerms = new string[] {
      "Literal", "StatementExpression", "Assignment", "LeftHandSide", "ExpressionName", 
      "TypeParameters_opt", "Superclass_opt", "Superinterfaces_opt", "AssignmentExpression", 
      "PrimaryNoNewArray", "Expression", "LambdaExpression", "LambdaBody", "ConditionalExpression", 
      "ConditionalOrExpression", "ConditionalAndExpression", "InclusiveOrExpression", 
      "ExclusiveOrExpression", "AndExpression", "EqualityExpression", "RelationalExpression", 
      "ShiftExpression", "AdditiveExpression", "MultiplicativeExpression", "UnaryExpression", 
      "PostfixExpression", "Primary", "PreIncrementExpression", "PreDecrementExpression", 
      "UnaryExpressionNotPlusMinus", "CastExpression", "PostIncrementExpression", 
      "PostDecrementExpression", "ConstantExpression", "Statement", "CompilationUnit", 
      "TypeDeclaration", "ClassDeclaration", "NormalClassDeclaration", "ClassBodyDeclaration", 
      "ExpressionStatement", "StatementWithoutTrailingSubstatement", "LocalVariableDeclaration", 
      "LocalVariableDeclarationStatement", "BlockStatement", "Throws_opt", "ClassMemberDeclaration", 
      "MethodDeclaration", "FormalParameter", "SwitchStatement", "ThrowStatement", 
      "SynchronizedStatement", "SwitchBlockStatementGroups", "SwitchBlockStatementGroup", 
      "SwitchLabels", "SwitchLabel", "BreakStatement", "ContinueStatement", "ReturnStatement", 
      "PackageDeclaration_opt", "Block", "MethodBody", "StatementNoShortIf", 
      "WhileStatement", "IfThenStatement", "IfThenElseStatement", "IfThenElseStatementNoShortIf", 
      "TypeDeclarations", "ClassBody", "ClassBodyDeclarations", "BlockStatements", 
      "BlockStatements_Opt", "FormalParameters", "FormalParameterList", "FormalParameterList_Opt", 
      "ImportDeclarations", "Result", "FloatingPointType", "IntegralType", "NumericType", 
      "UnannType", "UnannPrimitiveType", "UnannReferenceType", "UnannArrayType", 
      "UnannTypeVariable", "ReferenceType", "ClassModifier", "MethodModifier", 
      "VariableModifier", "ClassModifiers", "MethodModifiers", "VariableModifiers", 
      "VariableDeclaratorId", "VariableDeclarator", "MethodHeader", "MethodDeclarator", 
      "VariableDeclaratorList", "Program", "$accept", "Empty", "Dims_Opt", "Dims", 
      "PrimitiveType", "TypeVariable", "SwitchBlock", "Identifier_opt", "Expression_opt", 
      "AssignmentOperator", "LambdaParameters", "AdditionalBounds", "AdditionalBound", 
      };

  static Parser() {
    states[0] = new State(-5,new int[]{-98,1,-36,3,-60,4});
    states[1] = new State(new int[]{129,2});
    states[2] = new State(-1);
    states[3] = new State(-2);
    states[4] = new State(-6,new int[]{-76,5});
    states[5] = new State(-8,new int[]{-68,6});
    states[6] = new State(new int[]{129,-4,172,-13,155,-13,150,-13,145,-13,132,-13,170,-13,168,-13,175,-13},new int[]{-37,7,-38,8,-39,9,-90,10});
    states[7] = new State(-7);
    states[8] = new State(-9);
    states[9] = new State(-10);
    states[10] = new State(new int[]{172,11,155,264,150,265,145,266,132,267,170,268,168,269,175,270},new int[]{-87,263});
    states[11] = new State(new int[]{131,12});
    states[12] = new State(-21,new int[]{-6,13});
    states[13] = new State(-22,new int[]{-7,14});
    states[14] = new State(-23,new int[]{-8,15});
    states[15] = new State(new int[]{123,17},new int[]{-69,16});
    states[16] = new State(-11);
    states[17] = new State(-26,new int[]{-70,18});
    states[18] = new State(new int[]{125,19,171,-31,131,-31,152,-31,165,-31,164,-31,174,-31,167,-31,178,-31,148,-31,142,-31,155,-31,170,-31},new int[]{-40,20,-47,21,-48,22,-91,23});
    states[19] = new State(-24);
    states[20] = new State(-25);
    states[21] = new State(-27);
    states[22] = new State(-28);
    states[23] = new State(new int[]{171,259,131,256,152,54,165,55,164,56,174,57,167,58,178,60,148,61,142,62,155,261,170,262},new int[]{-95,24,-88,238,-77,239,-81,260,-83,46,-84,47,-85,48,-82,51,-80,52,-79,53,-78,59});
    states[24] = new State(new int[]{123,27,59,237},new int[]{-62,25,-61,26});
    states[25] = new State(-29);
    states[26] = new State(-71);
    states[27] = new State(new int[]{131,50,152,54,165,55,164,56,174,57,167,58,178,60,148,61,142,62,136,179,147,191,133,196,160,200,139,205,181,215,125,-75},new int[]{-72,28,-71,30,-45,230,-44,32,-43,33,-81,35,-83,46,-84,47,-85,48,-82,51,-80,52,-79,53,-78,59,-35,63,-42,64,-41,65,-2,66,-3,68,-4,69,-5,177,-50,178,-57,190,-58,195,-59,199,-65,204,-66,213,-64,214});
    states[28] = new State(new int[]{125,29});
    states[29] = new State(-73);
    states[30] = new State(new int[]{131,50,152,54,165,55,164,56,174,57,167,58,178,60,148,61,142,62,136,179,147,191,133,196,160,200,139,205,181,215,125,-74},new int[]{-45,31,-44,32,-43,33,-81,35,-83,46,-84,47,-85,48,-82,51,-80,52,-79,53,-78,59,-35,63,-42,64,-41,65,-2,66,-3,68,-4,69,-5,177,-50,178,-57,190,-58,195,-59,199,-65,204,-66,213,-64,214});
    states[31] = new State(-77);
    states[32] = new State(-78);
    states[33] = new State(new int[]{59,34});
    states[34] = new State(-80);
    states[35] = new State(new int[]{131,40},new int[]{-97,36,-94,45,-93,39});
    states[36] = new State(new int[]{44,37,59,-81});
    states[37] = new State(new int[]{131,40},new int[]{-94,38,-93,39});
    states[38] = new State(-83);
    states[39] = new State(-84);
    states[40] = new State(new int[]{91,43,44,-49,59,-49,41,-49},new int[]{-101,41,-102,42});
    states[41] = new State(-85);
    states[42] = new State(-48);
    states[43] = new State(new int[]{93,44});
    states[44] = new State(-50);
    states[45] = new State(-82);
    states[46] = new State(-51);
    states[47] = new State(-68);
    states[48] = new State(new int[]{91,43},new int[]{-102,49});
    states[49] = new State(-69);
    states[50] = new State(new int[]{91,-70,61,-122});
    states[51] = new State(-52);
    states[52] = new State(-53);
    states[53] = new State(-59);
    states[54] = new State(-61);
    states[55] = new State(-62);
    states[56] = new State(-63);
    states[57] = new State(-64);
    states[58] = new State(-65);
    states[59] = new State(-60);
    states[60] = new State(-66);
    states[61] = new State(-67);
    states[62] = new State(-54);
    states[63] = new State(-79);
    states[64] = new State(-86);
    states[65] = new State(-92);
    states[66] = new State(new int[]{59,67});
    states[67] = new State(-114);
    states[68] = new State(-115);
    states[69] = new State(new int[]{61,176},new int[]{-108,70});
    states[70] = new State(new int[]{131,79,197,103,198,106,43,108,45,110,182,119,183,120,184,121,185,122,126,126,33,128,40,131,194,-135},new int[]{-11,71,-12,72,-109,73,-9,76,-3,77,-4,69,-5,78,-14,80,-15,81,-16,175,-17,174,-18,173,-19,172,-20,171,-21,170,-22,167,-23,158,-24,153,-25,150,-28,102,-29,105,-30,112,-26,113,-27,116,-10,117,-1,118,-32,124,-33,125,-31,130});
    states[71] = new State(-120);
    states[72] = new State(-132);
    states[73] = new State(new int[]{194,74});
    states[74] = new State(-136,new int[]{-13,75});
    states[75] = new State(-134);
    states[76] = new State(-133);
    states[77] = new State(-124);
    states[78] = new State(new int[]{61,-121,197,-180,198,-180,42,-180,47,-180,37,-180,43,-180,45,-180,199,-180,200,-180,201,-180,60,-180,62,-180,192,-180,191,-180,159,-180,190,-180,193,-180,38,-180,94,-180,124,-180,195,-180,196,-180,59,-180,41,-180,58,-180});
    states[79] = new State(-122);
    states[80] = new State(-125);
    states[81] = new State(new int[]{196,82,59,-137,41,-137,58,-137});
    states[82] = new State(new int[]{197,103,198,106,43,108,45,110,182,119,183,120,184,121,185,122,131,79,126,126,33,128,40,131},new int[]{-16,83,-17,174,-18,173,-19,172,-20,171,-21,170,-22,167,-23,158,-24,153,-25,150,-28,102,-29,105,-30,112,-26,113,-27,116,-10,117,-1,118,-5,123,-32,124,-33,125,-31,130});
    states[83] = new State(new int[]{195,84,196,-139,59,-139,41,-139,58,-139});
    states[84] = new State(new int[]{197,103,198,106,43,108,45,110,182,119,183,120,184,121,185,122,131,79,126,126,33,128,40,131},new int[]{-17,85,-18,173,-19,172,-20,171,-21,170,-22,167,-23,158,-24,153,-25,150,-28,102,-29,105,-30,112,-26,113,-27,116,-10,117,-1,118,-5,123,-32,124,-33,125,-31,130});
    states[85] = new State(new int[]{124,86,195,-141,196,-141,59,-141,41,-141,58,-141});
    states[86] = new State(new int[]{197,103,198,106,43,108,45,110,182,119,183,120,184,121,185,122,131,79,126,126,33,128,40,131},new int[]{-18,87,-19,172,-20,171,-21,170,-22,167,-23,158,-24,153,-25,150,-28,102,-29,105,-30,112,-26,113,-27,116,-10,117,-1,118,-5,123,-32,124,-33,125,-31,130});
    states[87] = new State(new int[]{94,88,124,-143,195,-143,196,-143,59,-143,41,-143,58,-143});
    states[88] = new State(new int[]{197,103,198,106,43,108,45,110,182,119,183,120,184,121,185,122,131,79,126,126,33,128,40,131},new int[]{-19,89,-20,171,-21,170,-22,167,-23,158,-24,153,-25,150,-28,102,-29,105,-30,112,-26,113,-27,116,-10,117,-1,118,-5,123,-32,124,-33,125,-31,130});
    states[89] = new State(new int[]{38,90,94,-145,124,-145,195,-145,196,-145,59,-145,41,-145,58,-145});
    states[90] = new State(new int[]{197,103,198,106,43,108,45,110,182,119,183,120,184,121,185,122,131,79,126,126,33,128,40,131},new int[]{-20,91,-21,170,-22,167,-23,158,-24,153,-25,150,-28,102,-29,105,-30,112,-26,113,-27,116,-10,117,-1,118,-5,123,-32,124,-33,125,-31,130});
    states[91] = new State(new int[]{190,92,193,168,38,-147,94,-147,124,-147,195,-147,196,-147,59,-147,41,-147,58,-147});
    states[92] = new State(new int[]{197,103,198,106,43,108,45,110,182,119,183,120,184,121,185,122,131,79,126,126,33,128,40,131},new int[]{-21,93,-22,167,-23,158,-24,153,-25,150,-28,102,-29,105,-30,112,-26,113,-27,116,-10,117,-1,118,-5,123,-32,124,-33,125,-31,130});
    states[93] = new State(new int[]{60,94,62,159,192,161,191,163,159,165,190,-149,193,-149,38,-149,94,-149,124,-149,195,-149,196,-149,59,-149,41,-149,58,-149});
    states[94] = new State(new int[]{197,103,198,106,43,108,45,110,182,119,183,120,184,121,185,122,131,79,126,126,33,128,40,131},new int[]{-22,95,-23,158,-24,153,-25,150,-28,102,-29,105,-30,112,-26,113,-27,116,-10,117,-1,118,-5,123,-32,124,-33,125,-31,130});
    states[95] = new State(new int[]{199,96,200,154,201,156,60,-152,62,-152,192,-152,191,-152,159,-152,190,-152,193,-152,38,-152,94,-152,124,-152,195,-152,196,-152,59,-152,41,-152,58,-152});
    states[96] = new State(new int[]{197,103,198,106,43,108,45,110,182,119,183,120,184,121,185,122,131,79,126,126,33,128,40,131},new int[]{-23,97,-24,153,-25,150,-28,102,-29,105,-30,112,-26,113,-27,116,-10,117,-1,118,-5,123,-32,124,-33,125,-31,130});
    states[97] = new State(new int[]{43,98,45,151,199,-158,200,-158,201,-158,60,-158,62,-158,192,-158,191,-158,159,-158,190,-158,193,-158,38,-158,94,-158,124,-158,195,-158,196,-158,59,-158,41,-158,58,-158});
    states[98] = new State(new int[]{197,103,198,106,43,108,45,110,182,119,183,120,184,121,185,122,131,79,126,126,33,128,40,131},new int[]{-24,99,-25,150,-28,102,-29,105,-30,112,-26,113,-27,116,-10,117,-1,118,-5,123,-32,124,-33,125,-31,130});
    states[99] = new State(new int[]{42,100,47,146,37,148,43,-162,45,-162,199,-162,200,-162,201,-162,60,-162,62,-162,192,-162,191,-162,159,-162,190,-162,193,-162,38,-162,94,-162,124,-162,195,-162,196,-162,59,-162,41,-162,58,-162});
    states[100] = new State(new int[]{197,103,198,106,43,108,45,110,182,119,183,120,184,121,185,122,131,79,126,126,33,128,40,131},new int[]{-25,101,-28,102,-29,105,-30,112,-26,113,-27,116,-10,117,-1,118,-5,123,-32,124,-33,125,-31,130});
    states[101] = new State(-165);
    states[102] = new State(-168);
    states[103] = new State(new int[]{197,103,198,106,43,108,45,110,182,119,183,120,184,121,185,122,131,79,126,126,33,128,40,131},new int[]{-25,104,-28,102,-29,105,-30,112,-26,113,-27,116,-10,117,-1,118,-5,123,-32,124,-33,125,-31,130});
    states[104] = new State(-173);
    states[105] = new State(-169);
    states[106] = new State(new int[]{197,103,198,106,43,108,45,110,182,119,183,120,184,121,185,122,131,79,126,126,33,128,40,131},new int[]{-25,107,-28,102,-29,105,-30,112,-26,113,-27,116,-10,117,-1,118,-5,123,-32,124,-33,125,-31,130});
    states[107] = new State(-174);
    states[108] = new State(new int[]{197,103,198,106,43,108,45,110,182,119,183,120,184,121,185,122,131,79,126,126,33,128,40,131},new int[]{-25,109,-28,102,-29,105,-30,112,-26,113,-27,116,-10,117,-1,118,-5,123,-32,124,-33,125,-31,130});
    states[109] = new State(-170);
    states[110] = new State(new int[]{197,103,198,106,43,108,45,110,182,119,183,120,184,121,185,122,131,79,126,126,33,128,40,131},new int[]{-25,111,-28,102,-29,105,-30,112,-26,113,-27,116,-10,117,-1,118,-5,123,-32,124,-33,125,-31,130});
    states[111] = new State(-171);
    states[112] = new State(-172);
    states[113] = new State(new int[]{197,114,198,115,42,-175,47,-175,37,-175,43,-175,45,-175,199,-175,200,-175,201,-175,60,-175,62,-175,192,-175,191,-175,159,-175,190,-175,193,-175,38,-175,94,-175,124,-175,195,-175,196,-175,59,-175,41,-175,58,-175});
    states[114] = new State(-183);
    states[115] = new State(-184);
    states[116] = new State(-179);
    states[117] = new State(-126);
    states[118] = new State(-127);
    states[119] = new State(-128);
    states[120] = new State(-129);
    states[121] = new State(-130);
    states[122] = new State(-131);
    states[123] = new State(-180);
    states[124] = new State(-181);
    states[125] = new State(-182);
    states[126] = new State(new int[]{197,103,198,106,43,108,45,110,182,119,183,120,184,121,185,122,131,79,126,126,33,128,40,131},new int[]{-25,127,-28,102,-29,105,-30,112,-26,113,-27,116,-10,117,-1,118,-5,123,-32,124,-33,125,-31,130});
    states[127] = new State(-176);
    states[128] = new State(new int[]{197,103,198,106,43,108,45,110,182,119,183,120,184,121,185,122,131,79,126,126,33,128,40,131},new int[]{-25,129,-28,102,-29,105,-30,112,-26,113,-27,116,-10,117,-1,118,-5,123,-32,124,-33,125,-31,130});
    states[129] = new State(-177);
    states[130] = new State(-178);
    states[131] = new State(new int[]{152,54,165,55,164,56,174,57,167,58,178,60,148,61,142,143,131,145},new int[]{-103,132,-86,135,-80,142,-79,53,-78,59,-104,144});
    states[132] = new State(new int[]{41,133});
    states[133] = new State(new int[]{197,103,198,106,43,108,45,110,182,119,183,120,184,121,185,122,131,79,126,126,33,128,40,131},new int[]{-25,134,-28,102,-29,105,-30,112,-26,113,-27,116,-10,117,-1,118,-5,123,-32,124,-33,125,-31,130});
    states[134] = new State(-185);
    states[135] = new State(-189,new int[]{-110,136});
    states[136] = new State(new int[]{41,137,38,141},new int[]{-111,140});
    states[137] = new State(new int[]{182,119,183,120,184,121,185,122,131,79,126,126,33,128,40,131,194,-135},new int[]{-30,138,-12,139,-26,113,-27,116,-10,117,-1,118,-5,123,-32,124,-33,125,-31,130,-109,73});
    states[138] = new State(-186);
    states[139] = new State(-187);
    states[140] = new State(-188);
    states[141] = new State(-190);
    states[142] = new State(-55);
    states[143] = new State(-56);
    states[144] = new State(-57);
    states[145] = new State(-58);
    states[146] = new State(new int[]{197,103,198,106,43,108,45,110,182,119,183,120,184,121,185,122,131,79,126,126,33,128,40,131},new int[]{-25,147,-28,102,-29,105,-30,112,-26,113,-27,116,-10,117,-1,118,-5,123,-32,124,-33,125,-31,130});
    states[147] = new State(-166);
    states[148] = new State(new int[]{197,103,198,106,43,108,45,110,182,119,183,120,184,121,185,122,131,79,126,126,33,128,40,131},new int[]{-25,149,-28,102,-29,105,-30,112,-26,113,-27,116,-10,117,-1,118,-5,123,-32,124,-33,125,-31,130});
    states[149] = new State(-167);
    states[150] = new State(-164);
    states[151] = new State(new int[]{197,103,198,106,43,108,45,110,182,119,183,120,184,121,185,122,131,79,126,126,33,128,40,131},new int[]{-24,152,-25,150,-28,102,-29,105,-30,112,-26,113,-27,116,-10,117,-1,118,-5,123,-32,124,-33,125,-31,130});
    states[152] = new State(new int[]{42,100,47,146,37,148,43,-163,45,-163,199,-163,200,-163,201,-163,60,-163,62,-163,192,-163,191,-163,159,-163,190,-163,193,-163,38,-163,94,-163,124,-163,195,-163,196,-163,59,-163,41,-163,58,-163});
    states[153] = new State(new int[]{42,100,47,146,37,148,43,-161,45,-161,199,-161,200,-161,201,-161,60,-161,62,-161,192,-161,191,-161,159,-161,190,-161,193,-161,38,-161,94,-161,124,-161,195,-161,196,-161,59,-161,41,-161,58,-161});
    states[154] = new State(new int[]{197,103,198,106,43,108,45,110,182,119,183,120,184,121,185,122,131,79,126,126,33,128,40,131},new int[]{-23,155,-24,153,-25,150,-28,102,-29,105,-30,112,-26,113,-27,116,-10,117,-1,118,-5,123,-32,124,-33,125,-31,130});
    states[155] = new State(new int[]{43,98,45,151,199,-159,200,-159,201,-159,60,-159,62,-159,192,-159,191,-159,159,-159,190,-159,193,-159,38,-159,94,-159,124,-159,195,-159,196,-159,59,-159,41,-159,58,-159});
    states[156] = new State(new int[]{197,103,198,106,43,108,45,110,182,119,183,120,184,121,185,122,131,79,126,126,33,128,40,131},new int[]{-23,157,-24,153,-25,150,-28,102,-29,105,-30,112,-26,113,-27,116,-10,117,-1,118,-5,123,-32,124,-33,125,-31,130});
    states[157] = new State(new int[]{43,98,45,151,199,-160,200,-160,201,-160,60,-160,62,-160,192,-160,191,-160,159,-160,190,-160,193,-160,38,-160,94,-160,124,-160,195,-160,196,-160,59,-160,41,-160,58,-160});
    states[158] = new State(new int[]{43,98,45,151,199,-157,200,-157,201,-157,60,-157,62,-157,192,-157,191,-157,159,-157,190,-157,193,-157,38,-157,94,-157,124,-157,195,-157,196,-157,59,-157,41,-157,58,-157});
    states[159] = new State(new int[]{197,103,198,106,43,108,45,110,182,119,183,120,184,121,185,122,131,79,126,126,33,128,40,131},new int[]{-22,160,-23,158,-24,153,-25,150,-28,102,-29,105,-30,112,-26,113,-27,116,-10,117,-1,118,-5,123,-32,124,-33,125,-31,130});
    states[160] = new State(new int[]{199,96,200,154,201,156,60,-153,62,-153,192,-153,191,-153,159,-153,190,-153,193,-153,38,-153,94,-153,124,-153,195,-153,196,-153,59,-153,41,-153,58,-153});
    states[161] = new State(new int[]{197,103,198,106,43,108,45,110,182,119,183,120,184,121,185,122,131,79,126,126,33,128,40,131},new int[]{-22,162,-23,158,-24,153,-25,150,-28,102,-29,105,-30,112,-26,113,-27,116,-10,117,-1,118,-5,123,-32,124,-33,125,-31,130});
    states[162] = new State(new int[]{199,96,200,154,201,156,60,-154,62,-154,192,-154,191,-154,159,-154,190,-154,193,-154,38,-154,94,-154,124,-154,195,-154,196,-154,59,-154,41,-154,58,-154});
    states[163] = new State(new int[]{197,103,198,106,43,108,45,110,182,119,183,120,184,121,185,122,131,79,126,126,33,128,40,131},new int[]{-22,164,-23,158,-24,153,-25,150,-28,102,-29,105,-30,112,-26,113,-27,116,-10,117,-1,118,-5,123,-32,124,-33,125,-31,130});
    states[164] = new State(new int[]{199,96,200,154,201,156,60,-155,62,-155,192,-155,191,-155,159,-155,190,-155,193,-155,38,-155,94,-155,124,-155,195,-155,196,-155,59,-155,41,-155,58,-155});
    states[165] = new State(new int[]{131,145},new int[]{-86,166,-104,144});
    states[166] = new State(-156);
    states[167] = new State(new int[]{199,96,200,154,201,156,60,-151,62,-151,192,-151,191,-151,159,-151,190,-151,193,-151,38,-151,94,-151,124,-151,195,-151,196,-151,59,-151,41,-151,58,-151});
    states[168] = new State(new int[]{197,103,198,106,43,108,45,110,182,119,183,120,184,121,185,122,131,79,126,126,33,128,40,131},new int[]{-21,169,-22,167,-23,158,-24,153,-25,150,-28,102,-29,105,-30,112,-26,113,-27,116,-10,117,-1,118,-5,123,-32,124,-33,125,-31,130});
    states[169] = new State(new int[]{60,94,62,159,192,161,191,163,159,165,190,-150,193,-150,38,-150,94,-150,124,-150,195,-150,196,-150,59,-150,41,-150,58,-150});
    states[170] = new State(new int[]{60,94,62,159,192,161,191,163,159,165,190,-148,193,-148,38,-148,94,-148,124,-148,195,-148,196,-148,59,-148,41,-148,58,-148});
    states[171] = new State(new int[]{190,92,193,168,38,-146,94,-146,124,-146,195,-146,196,-146,59,-146,41,-146,58,-146});
    states[172] = new State(new int[]{38,90,94,-144,124,-144,195,-144,196,-144,59,-144,41,-144,58,-144});
    states[173] = new State(new int[]{94,88,124,-142,195,-142,196,-142,59,-142,41,-142,58,-142});
    states[174] = new State(new int[]{124,86,195,-140,196,-140,59,-140,41,-140,58,-140});
    states[175] = new State(new int[]{195,84,196,-138,59,-138,41,-138,58,-138});
    states[176] = new State(-123);
    states[177] = new State(-121);
    states[178] = new State(-93);
    states[179] = new State(new int[]{40,180});
    states[180] = new State(new int[]{131,79,197,103,198,106,43,108,45,110,182,119,183,120,184,121,185,122,126,126,33,128,40,131,194,-135},new int[]{-11,181,-12,72,-109,73,-9,76,-3,77,-4,69,-5,78,-14,80,-15,81,-16,175,-17,174,-18,173,-19,172,-20,171,-21,170,-22,167,-23,158,-24,153,-25,150,-28,102,-29,105,-30,112,-26,113,-27,116,-10,117,-1,118,-32,124,-33,125,-31,130});
    states[181] = new State(new int[]{41,182});
    states[182] = new State(new int[]{123,184},new int[]{-105,183});
    states[183] = new State(-97);
    states[184] = new State(new int[]{157,231},new int[]{-53,185,-54,236,-55,188,-56,235});
    states[185] = new State(new int[]{125,186,157,231},new int[]{-54,187,-55,188,-56,235});
    states[186] = new State(-98);
    states[187] = new State(-100);
    states[188] = new State(new int[]{131,50,152,54,165,55,164,56,174,57,167,58,178,60,148,61,142,62,136,179,147,191,133,196,160,200,139,205,181,215,157,231},new int[]{-71,189,-56,229,-45,230,-44,32,-43,33,-81,35,-83,46,-84,47,-85,48,-82,51,-80,52,-79,53,-78,59,-35,63,-42,64,-41,65,-2,66,-3,68,-4,69,-5,177,-50,178,-57,190,-58,195,-59,199,-65,204,-66,213,-64,214});
    states[189] = new State(new int[]{131,50,152,54,165,55,164,56,174,57,167,58,178,60,148,61,142,62,136,179,147,191,133,196,160,200,139,205,181,215,125,-101,157,-101},new int[]{-45,31,-44,32,-43,33,-81,35,-83,46,-84,47,-85,48,-82,51,-80,52,-79,53,-78,59,-35,63,-42,64,-41,65,-2,66,-3,68,-4,69,-5,177,-50,178,-57,190,-58,195,-59,199,-65,204,-66,213,-64,214});
    states[190] = new State(-94);
    states[191] = new State(new int[]{131,194,59,-108},new int[]{-106,192});
    states[192] = new State(new int[]{59,193});
    states[193] = new State(-105);
    states[194] = new State(-107);
    states[195] = new State(-95);
    states[196] = new State(new int[]{131,194,59,-108},new int[]{-106,197});
    states[197] = new State(new int[]{59,198});
    states[198] = new State(-106);
    states[199] = new State(-96);
    states[200] = new State(new int[]{131,79,197,103,198,106,43,108,45,110,182,119,183,120,184,121,185,122,126,126,33,128,40,131,194,-135,59,-111},new int[]{-107,201,-11,203,-12,72,-109,73,-9,76,-3,77,-4,69,-5,78,-14,80,-15,81,-16,175,-17,174,-18,173,-19,172,-20,171,-21,170,-22,167,-23,158,-24,153,-25,150,-28,102,-29,105,-30,112,-26,113,-27,116,-10,117,-1,118,-32,124,-33,125,-31,130});
    states[201] = new State(new int[]{59,202});
    states[202] = new State(-109);
    states[203] = new State(-110);
    states[204] = new State(-87);
    states[205] = new State(new int[]{40,206});
    states[206] = new State(new int[]{131,79,197,103,198,106,43,108,45,110,182,119,183,120,184,121,185,122,126,126,33,128,40,131,194,-135},new int[]{-11,207,-12,72,-109,73,-9,76,-3,77,-4,69,-5,78,-14,80,-15,81,-16,175,-17,174,-18,173,-19,172,-20,171,-21,170,-22,167,-23,158,-24,153,-25,150,-28,102,-29,105,-30,112,-26,113,-27,116,-10,117,-1,118,-32,124,-33,125,-31,130});
    states[207] = new State(new int[]{41,208});
    states[208] = new State(new int[]{131,79,136,179,147,191,133,196,160,200,139,221,181,215},new int[]{-35,209,-63,210,-42,220,-41,65,-2,66,-3,68,-4,69,-5,177,-50,178,-57,190,-58,195,-59,199,-65,204,-66,213,-64,214,-67,228});
    states[209] = new State(-116);
    states[210] = new State(new int[]{153,211});
    states[211] = new State(new int[]{131,79,136,179,147,191,133,196,160,200,139,205,181,215},new int[]{-35,212,-42,64,-41,65,-2,66,-3,68,-4,69,-5,177,-50,178,-57,190,-58,195,-59,199,-65,204,-66,213,-64,214});
    states[212] = new State(-117);
    states[213] = new State(-88);
    states[214] = new State(-89);
    states[215] = new State(new int[]{40,216});
    states[216] = new State(new int[]{131,79,197,103,198,106,43,108,45,110,182,119,183,120,184,121,185,122,126,126,33,128,40,131,194,-135},new int[]{-11,217,-12,72,-109,73,-9,76,-3,77,-4,69,-5,78,-14,80,-15,81,-16,175,-17,174,-18,173,-19,172,-20,171,-21,170,-22,167,-23,158,-24,153,-25,150,-28,102,-29,105,-30,112,-26,113,-27,116,-10,117,-1,118,-32,124,-33,125,-31,130});
    states[217] = new State(new int[]{41,218});
    states[218] = new State(new int[]{131,79,136,179,147,191,133,196,160,200,139,205,181,215},new int[]{-35,219,-42,64,-41,65,-2,66,-3,68,-4,69,-5,177,-50,178,-57,190,-58,195,-59,199,-65,204,-66,213,-64,214});
    states[219] = new State(-119);
    states[220] = new State(new int[]{131,-86,152,-86,165,-86,164,-86,174,-86,167,-86,178,-86,148,-86,142,-86,136,-86,147,-86,133,-86,160,-86,139,-86,181,-86,125,-86,157,-86,153,-90});
    states[221] = new State(new int[]{40,222});
    states[222] = new State(new int[]{131,79,197,103,198,106,43,108,45,110,182,119,183,120,184,121,185,122,126,126,33,128,40,131,194,-135},new int[]{-11,223,-12,72,-109,73,-9,76,-3,77,-4,69,-5,78,-14,80,-15,81,-16,175,-17,174,-18,173,-19,172,-20,171,-21,170,-22,167,-23,158,-24,153,-25,150,-28,102,-29,105,-30,112,-26,113,-27,116,-10,117,-1,118,-32,124,-33,125,-31,130});
    states[223] = new State(new int[]{41,224});
    states[224] = new State(new int[]{131,79,136,179,147,191,133,196,160,200,139,221,181,215},new int[]{-35,209,-63,225,-42,220,-41,65,-2,66,-3,68,-4,69,-5,177,-50,178,-57,190,-58,195,-59,199,-65,204,-66,213,-64,214,-67,228});
    states[225] = new State(new int[]{153,226});
    states[226] = new State(new int[]{131,79,136,179,147,191,133,196,160,200,139,221,181,215},new int[]{-35,212,-63,227,-42,220,-41,65,-2,66,-3,68,-4,69,-5,177,-50,178,-57,190,-58,195,-59,199,-65,204,-66,213,-64,214,-67,228});
    states[227] = new State(-118);
    states[228] = new State(-91);
    states[229] = new State(-103);
    states[230] = new State(-76);
    states[231] = new State(new int[]{131,79,197,103,198,106,43,108,45,110,182,119,183,120,184,121,185,122,126,126,33,128,40,131,194,-135},new int[]{-34,232,-11,234,-12,72,-109,73,-9,76,-3,77,-4,69,-5,78,-14,80,-15,81,-16,175,-17,174,-18,173,-19,172,-20,171,-21,170,-22,167,-23,158,-24,153,-25,150,-28,102,-29,105,-30,112,-26,113,-27,116,-10,117,-1,118,-32,124,-33,125,-31,130});
    states[232] = new State(new int[]{58,233});
    states[233] = new State(-104);
    states[234] = new State(-191);
    states[235] = new State(-102);
    states[236] = new State(-99);
    states[237] = new State(-72);
    states[238] = new State(-30);
    states[239] = new State(new int[]{131,243},new int[]{-96,240});
    states[240] = new State(-3,new int[]{-46,241,-100,242});
    states[241] = new State(-34);
    states[242] = new State(-37);
    states[243] = new State(new int[]{40,244});
    states[244] = new State(new int[]{131,-46,152,-46,165,-46,164,-46,174,-46,167,-46,178,-46,148,-46,142,-46,168,-46,41,-40},new int[]{-75,245,-74,248,-73,249,-49,258,-92,252});
    states[245] = new State(new int[]{41,246});
    states[246] = new State(new int[]{91,43,123,-49,59,-49},new int[]{-101,247,-102,42});
    states[247] = new State(-38);
    states[248] = new State(-39);
    states[249] = new State(new int[]{44,250,41,-41});
    states[250] = new State(-46,new int[]{-49,251,-92,252});
    states[251] = new State(-43);
    states[252] = new State(new int[]{131,256,152,54,165,55,164,56,174,57,167,58,178,60,148,61,142,62,168,257},new int[]{-81,253,-89,255,-83,46,-84,47,-85,48,-82,51,-80,52,-79,53,-78,59});
    states[253] = new State(new int[]{131,40},new int[]{-93,254});
    states[254] = new State(-44);
    states[255] = new State(-45);
    states[256] = new State(-70);
    states[257] = new State(-47);
    states[258] = new State(-42);
    states[259] = new State(-35);
    states[260] = new State(-36);
    states[261] = new State(-32);
    states[262] = new State(-33);
    states[263] = new State(-12);
    states[264] = new State(-14);
    states[265] = new State(-15);
    states[266] = new State(-16);
    states[267] = new State(-17);
    states[268] = new State(-18);
    states[269] = new State(-19);
    states[270] = new State(-20);

    for (int sNo = 0; sNo < states.Length; sNo++) states[sNo].number = sNo;

    rules[1] = new Rule(-99, new int[]{-98,129});
    rules[2] = new Rule(-98, new int[]{-36});
    rules[3] = new Rule(-100, new int[]{});
    rules[4] = new Rule(-36, new int[]{-60,-76,-68});
    rules[5] = new Rule(-60, new int[]{});
    rules[6] = new Rule(-76, new int[]{});
    rules[7] = new Rule(-68, new int[]{-68,-37});
    rules[8] = new Rule(-68, new int[]{});
    rules[9] = new Rule(-37, new int[]{-38});
    rules[10] = new Rule(-38, new int[]{-39});
    rules[11] = new Rule(-39, new int[]{-90,172,131,-6,-7,-8,-69});
    rules[12] = new Rule(-90, new int[]{-90,-87});
    rules[13] = new Rule(-90, new int[]{});
    rules[14] = new Rule(-87, new int[]{155});
    rules[15] = new Rule(-87, new int[]{150});
    rules[16] = new Rule(-87, new int[]{145});
    rules[17] = new Rule(-87, new int[]{132});
    rules[18] = new Rule(-87, new int[]{170});
    rules[19] = new Rule(-87, new int[]{168});
    rules[20] = new Rule(-87, new int[]{175});
    rules[21] = new Rule(-6, new int[]{});
    rules[22] = new Rule(-7, new int[]{});
    rules[23] = new Rule(-8, new int[]{});
    rules[24] = new Rule(-69, new int[]{123,-70,125});
    rules[25] = new Rule(-70, new int[]{-70,-40});
    rules[26] = new Rule(-70, new int[]{});
    rules[27] = new Rule(-40, new int[]{-47});
    rules[28] = new Rule(-47, new int[]{-48});
    rules[29] = new Rule(-48, new int[]{-91,-95,-62});
    rules[30] = new Rule(-91, new int[]{-91,-88});
    rules[31] = new Rule(-91, new int[]{});
    rules[32] = new Rule(-88, new int[]{155});
    rules[33] = new Rule(-88, new int[]{170});
    rules[34] = new Rule(-95, new int[]{-77,-96,-46});
    rules[35] = new Rule(-77, new int[]{171});
    rules[36] = new Rule(-77, new int[]{-81});
    rules[37] = new Rule(-46, new int[]{-100});
    rules[38] = new Rule(-96, new int[]{131,40,-75,41,-101});
    rules[39] = new Rule(-75, new int[]{-74});
    rules[40] = new Rule(-75, new int[]{});
    rules[41] = new Rule(-74, new int[]{-73});
    rules[42] = new Rule(-73, new int[]{-49});
    rules[43] = new Rule(-73, new int[]{-73,44,-49});
    rules[44] = new Rule(-49, new int[]{-92,-81,-93});
    rules[45] = new Rule(-92, new int[]{-92,-89});
    rules[46] = new Rule(-92, new int[]{});
    rules[47] = new Rule(-89, new int[]{168});
    rules[48] = new Rule(-101, new int[]{-102});
    rules[49] = new Rule(-101, new int[]{});
    rules[50] = new Rule(-102, new int[]{91,93});
    rules[51] = new Rule(-81, new int[]{-83});
    rules[52] = new Rule(-81, new int[]{-82});
    rules[53] = new Rule(-82, new int[]{-80});
    rules[54] = new Rule(-82, new int[]{142});
    rules[55] = new Rule(-103, new int[]{-80});
    rules[56] = new Rule(-103, new int[]{142});
    rules[57] = new Rule(-86, new int[]{-104});
    rules[58] = new Rule(-104, new int[]{131});
    rules[59] = new Rule(-80, new int[]{-79});
    rules[60] = new Rule(-80, new int[]{-78});
    rules[61] = new Rule(-79, new int[]{152});
    rules[62] = new Rule(-79, new int[]{165});
    rules[63] = new Rule(-79, new int[]{164});
    rules[64] = new Rule(-79, new int[]{174});
    rules[65] = new Rule(-79, new int[]{167});
    rules[66] = new Rule(-78, new int[]{178});
    rules[67] = new Rule(-78, new int[]{148});
    rules[68] = new Rule(-83, new int[]{-84});
    rules[69] = new Rule(-84, new int[]{-85,-102});
    rules[70] = new Rule(-85, new int[]{131});
    rules[71] = new Rule(-62, new int[]{-61});
    rules[72] = new Rule(-62, new int[]{59});
    rules[73] = new Rule(-61, new int[]{123,-72,125});
    rules[74] = new Rule(-72, new int[]{-71});
    rules[75] = new Rule(-72, new int[]{});
    rules[76] = new Rule(-71, new int[]{-45});
    rules[77] = new Rule(-71, new int[]{-71,-45});
    rules[78] = new Rule(-45, new int[]{-44});
    rules[79] = new Rule(-45, new int[]{-35});
    rules[80] = new Rule(-44, new int[]{-43,59});
    rules[81] = new Rule(-43, new int[]{-81,-97});
    rules[82] = new Rule(-97, new int[]{-94});
    rules[83] = new Rule(-97, new int[]{-97,44,-94});
    rules[84] = new Rule(-94, new int[]{-93});
    rules[85] = new Rule(-93, new int[]{131,-101});
    rules[86] = new Rule(-35, new int[]{-42});
    rules[87] = new Rule(-35, new int[]{-65});
    rules[88] = new Rule(-35, new int[]{-66});
    rules[89] = new Rule(-35, new int[]{-64});
    rules[90] = new Rule(-63, new int[]{-42});
    rules[91] = new Rule(-63, new int[]{-67});
    rules[92] = new Rule(-42, new int[]{-41});
    rules[93] = new Rule(-42, new int[]{-50});
    rules[94] = new Rule(-42, new int[]{-57});
    rules[95] = new Rule(-42, new int[]{-58});
    rules[96] = new Rule(-42, new int[]{-59});
    rules[97] = new Rule(-50, new int[]{136,40,-11,41,-105});
    rules[98] = new Rule(-105, new int[]{123,-53,125});
    rules[99] = new Rule(-53, new int[]{-54});
    rules[100] = new Rule(-53, new int[]{-53,-54});
    rules[101] = new Rule(-54, new int[]{-55,-71});
    rules[102] = new Rule(-55, new int[]{-56});
    rules[103] = new Rule(-55, new int[]{-55,-56});
    rules[104] = new Rule(-56, new int[]{157,-34,58});
    rules[105] = new Rule(-57, new int[]{147,-106,59});
    rules[106] = new Rule(-58, new int[]{133,-106,59});
    rules[107] = new Rule(-106, new int[]{131});
    rules[108] = new Rule(-106, new int[]{});
    rules[109] = new Rule(-59, new int[]{160,-107,59});
    rules[110] = new Rule(-107, new int[]{-11});
    rules[111] = new Rule(-107, new int[]{});
    rules[112] = new Rule(-51, new int[]{151,-11,59});
    rules[113] = new Rule(-52, new int[]{141,40,-11,41,-61});
    rules[114] = new Rule(-41, new int[]{-2,59});
    rules[115] = new Rule(-2, new int[]{-3});
    rules[116] = new Rule(-65, new int[]{139,40,-11,41,-35});
    rules[117] = new Rule(-66, new int[]{139,40,-11,41,-63,153,-35});
    rules[118] = new Rule(-67, new int[]{139,40,-11,41,-63,153,-63});
    rules[119] = new Rule(-64, new int[]{181,40,-11,41,-35});
    rules[120] = new Rule(-3, new int[]{-4,-108,-11});
    rules[121] = new Rule(-4, new int[]{-5});
    rules[122] = new Rule(-5, new int[]{131});
    rules[123] = new Rule(-108, new int[]{61});
    rules[124] = new Rule(-9, new int[]{-3});
    rules[125] = new Rule(-9, new int[]{-14});
    rules[126] = new Rule(-27, new int[]{-10});
    rules[127] = new Rule(-10, new int[]{-1});
    rules[128] = new Rule(-1, new int[]{182});
    rules[129] = new Rule(-1, new int[]{183});
    rules[130] = new Rule(-1, new int[]{184});
    rules[131] = new Rule(-1, new int[]{185});
    rules[132] = new Rule(-11, new int[]{-12});
    rules[133] = new Rule(-11, new int[]{-9});
    rules[134] = new Rule(-12, new int[]{-109,194,-13});
    rules[135] = new Rule(-109, new int[]{});
    rules[136] = new Rule(-13, new int[]{});
    rules[137] = new Rule(-14, new int[]{-15});
    rules[138] = new Rule(-15, new int[]{-16});
    rules[139] = new Rule(-15, new int[]{-15,196,-16});
    rules[140] = new Rule(-16, new int[]{-17});
    rules[141] = new Rule(-16, new int[]{-16,195,-17});
    rules[142] = new Rule(-17, new int[]{-18});
    rules[143] = new Rule(-17, new int[]{-17,124,-18});
    rules[144] = new Rule(-18, new int[]{-19});
    rules[145] = new Rule(-18, new int[]{-18,94,-19});
    rules[146] = new Rule(-19, new int[]{-20});
    rules[147] = new Rule(-19, new int[]{-19,38,-20});
    rules[148] = new Rule(-20, new int[]{-21});
    rules[149] = new Rule(-20, new int[]{-20,190,-21});
    rules[150] = new Rule(-20, new int[]{-20,193,-21});
    rules[151] = new Rule(-21, new int[]{-22});
    rules[152] = new Rule(-21, new int[]{-21,60,-22});
    rules[153] = new Rule(-21, new int[]{-21,62,-22});
    rules[154] = new Rule(-21, new int[]{-21,192,-22});
    rules[155] = new Rule(-21, new int[]{-21,191,-22});
    rules[156] = new Rule(-21, new int[]{-21,159,-86});
    rules[157] = new Rule(-22, new int[]{-23});
    rules[158] = new Rule(-22, new int[]{-22,199,-23});
    rules[159] = new Rule(-22, new int[]{-22,200,-23});
    rules[160] = new Rule(-22, new int[]{-22,201,-23});
    rules[161] = new Rule(-23, new int[]{-24});
    rules[162] = new Rule(-23, new int[]{-23,43,-24});
    rules[163] = new Rule(-23, new int[]{-23,45,-24});
    rules[164] = new Rule(-24, new int[]{-25});
    rules[165] = new Rule(-24, new int[]{-24,42,-25});
    rules[166] = new Rule(-24, new int[]{-24,47,-25});
    rules[167] = new Rule(-24, new int[]{-24,37,-25});
    rules[168] = new Rule(-25, new int[]{-28});
    rules[169] = new Rule(-25, new int[]{-29});
    rules[170] = new Rule(-25, new int[]{43,-25});
    rules[171] = new Rule(-25, new int[]{45,-25});
    rules[172] = new Rule(-25, new int[]{-30});
    rules[173] = new Rule(-28, new int[]{197,-25});
    rules[174] = new Rule(-29, new int[]{198,-25});
    rules[175] = new Rule(-30, new int[]{-26});
    rules[176] = new Rule(-30, new int[]{126,-25});
    rules[177] = new Rule(-30, new int[]{33,-25});
    rules[178] = new Rule(-30, new int[]{-31});
    rules[179] = new Rule(-26, new int[]{-27});
    rules[180] = new Rule(-26, new int[]{-5});
    rules[181] = new Rule(-26, new int[]{-32});
    rules[182] = new Rule(-26, new int[]{-33});
    rules[183] = new Rule(-32, new int[]{-26,197});
    rules[184] = new Rule(-33, new int[]{-26,198});
    rules[185] = new Rule(-31, new int[]{40,-103,41,-25});
    rules[186] = new Rule(-31, new int[]{40,-86,-110,41,-30});
    rules[187] = new Rule(-31, new int[]{40,-86,-110,41,-12});
    rules[188] = new Rule(-110, new int[]{-110,-111});
    rules[189] = new Rule(-110, new int[]{});
    rules[190] = new Rule(-111, new int[]{38});
    rules[191] = new Rule(-34, new int[]{-11});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
#pragma warning disable 162, 1522
    switch (action)
    {
      case 2: // Program -> CompilationUnit
#line 115 "parser.y"
                                   {root = ValueStack[ValueStack.Depth-1].stmt;}
#line default
        break;
      case 4: // CompilationUnit -> PackageDeclaration_opt, ImportDeclarations, TypeDeclarations
#line 123 "parser.y"
                                                               { CurrentSemanticValue.stmt = new CompilationUnitDeclaration(ValueStack[ValueStack.Depth-3].stmt,ValueStack[ValueStack.Depth-2].stmts,ValueStack[ValueStack.Depth-1].stmts);  }
#line default
        break;
      case 7: // TypeDeclarations -> TypeDeclarations, TypeDeclaration
#line 135 "parser.y"
                                          { CurrentSemanticValue.stmts = ValueStack[ValueStack.Depth-2].stmts; CurrentSemanticValue.stmts.Add(ValueStack[ValueStack.Depth-1].stmt); }
#line default
        break;
      case 8: // TypeDeclarations -> /* empty */
#line 136 "parser.y"
                          { CurrentSemanticValue.stmts = new List<Statement>();}
#line default
        break;
      case 9: // TypeDeclaration -> ClassDeclaration
#line 140 "parser.y"
                                                            { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 10: // ClassDeclaration -> NormalClassDeclaration
#line 144 "parser.y"
                                                             { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 11: // NormalClassDeclaration -> ClassModifiers, CLASS, IDENTIFIER, TypeParameters_opt, 
               //                           Superclass_opt, Superinterfaces_opt, ClassBody
#line 148 "parser.y"
                                                                                                    {  CurrentSemanticValue.stmt = new ClassDeclaration(ValueStack[ValueStack.Depth-5].name,ValueStack[ValueStack.Depth-7].modfs,ValueStack[ValueStack.Depth-1].stmts); }
#line default
        break;
      case 12: // ClassModifiers -> ClassModifiers, ClassModifier
#line 152 "parser.y"
                                       { CurrentSemanticValue.modfs = ValueStack[ValueStack.Depth-2].modfs; CurrentSemanticValue.modfs.Add(ValueStack[ValueStack.Depth-1].modf); }
#line default
        break;
      case 13: // ClassModifiers -> /* empty */
#line 153 "parser.y"
                          { CurrentSemanticValue.modfs = new List<Modifier>(); }
#line default
        break;
      case 14: // ClassModifier -> PUBLIC
#line 157 "parser.y"
                      { CurrentSemanticValue.modf = Modifier.PUBLIC; }
#line default
        break;
      case 15: // ClassModifier -> PROTECTED
#line 158 "parser.y"
                         { CurrentSemanticValue.modf = Modifier.PROTECTED; }
#line default
        break;
      case 16: // ClassModifier -> PRIVATE
#line 159 "parser.y"
                        { CurrentSemanticValue.modf = Modifier.PRIVATE; }
#line default
        break;
      case 17: // ClassModifier -> ABSTRACT
#line 160 "parser.y"
                         { CurrentSemanticValue.modf = Modifier.ABSTRACT; }
#line default
        break;
      case 18: // ClassModifier -> STATIC
#line 161 "parser.y"
                       { CurrentSemanticValue.modf = Modifier.STATIC; }
#line default
        break;
      case 19: // ClassModifier -> FINAL
#line 162 "parser.y"
                      { CurrentSemanticValue.modf = Modifier.FINAL; }
#line default
        break;
      case 20: // ClassModifier -> STRICTFP
#line 163 "parser.y"
                         { CurrentSemanticValue.modf = Modifier.STRICTFP; }
#line default
        break;
      case 21: // TypeParameters_opt -> /* empty */
#line 168 "parser.y"
                                        { CurrentSemanticValue.expr = null; }
#line default
        break;
      case 22: // Superclass_opt -> /* empty */
#line 171 "parser.y"
                                     { CurrentSemanticValue.expr = null; }
#line default
        break;
      case 23: // Superinterfaces_opt -> /* empty */
#line 174 "parser.y"
                                         { CurrentSemanticValue.expr = null; }
#line default
        break;
      case 24: // ClassBody -> '{', ClassBodyDeclarations, '}'
#line 178 "parser.y"
                                        { CurrentSemanticValue.stmts = ValueStack[ValueStack.Depth-2].stmts; }
#line default
        break;
      case 25: // ClassBodyDeclarations -> ClassBodyDeclarations, ClassBodyDeclaration
#line 185 "parser.y"
                                                 { CurrentSemanticValue.stmts = ValueStack[ValueStack.Depth-2].stmts; CurrentSemanticValue.stmts.Add(ValueStack[ValueStack.Depth-1].stmt); }
#line default
        break;
      case 26: // ClassBodyDeclarations -> /* empty */
#line 186 "parser.y"
                          { CurrentSemanticValue.stmts = new List<Statement>(); }
#line default
        break;
      case 27: // ClassBodyDeclaration -> ClassMemberDeclaration
#line 190 "parser.y"
                                  { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 28: // ClassMemberDeclaration -> MethodDeclaration
#line 195 "parser.y"
                               { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 29: // MethodDeclaration -> MethodModifiers, MethodHeader, MethodBody
#line 200 "parser.y"
                                               { CurrentSemanticValue.stmt = new MethodDeclaration( (string)((ArrayList)ValueStack[ValueStack.Depth-2].arrlst[1])[0], ValueStack[ValueStack.Depth-3].modfs, ValueStack[ValueStack.Depth-1].stmt, (AST.Type)ValueStack[ValueStack.Depth-2].arrlst[0], (List<Statement>)((ArrayList)ValueStack[ValueStack.Depth-2].arrlst[1])[1]); }
#line default
        break;
      case 30: // MethodModifiers -> MethodModifiers, MethodModifier
#line 204 "parser.y"
                                              { CurrentSemanticValue.modfs = ValueStack[ValueStack.Depth-2].modfs; CurrentSemanticValue.modfs.Add(ValueStack[ValueStack.Depth-1].modf); }
#line default
        break;
      case 31: // MethodModifiers -> /* empty */
#line 205 "parser.y"
                          { CurrentSemanticValue.modfs = new List<Modifier>(); }
#line default
        break;
      case 32: // MethodModifier -> PUBLIC
#line 209 "parser.y"
                      { CurrentSemanticValue.modf = Modifier.PUBLIC; }
#line default
        break;
      case 33: // MethodModifier -> STATIC
#line 210 "parser.y"
                            { CurrentSemanticValue.modf = Modifier.STATIC; }
#line default
        break;
      case 34: // MethodHeader -> Result, MethodDeclarator, Throws_opt
#line 214 "parser.y"
                                           {CurrentSemanticValue.arrlst = new ArrayList() { ValueStack[ValueStack.Depth-3].type, ValueStack[ValueStack.Depth-2].arrlst, ValueStack[ValueStack.Depth-1].stmt } ; }
#line default
        break;
      case 35: // Result -> VOID
#line 222 "parser.y"
                     {CurrentSemanticValue.type = new NamedType("VOID"); }
#line default
        break;
      case 36: // Result -> UnannType
#line 223 "parser.y"
                         {CurrentSemanticValue.type = ValueStack[ValueStack.Depth-1].type; }
#line default
        break;
      case 37: // Throws_opt -> Empty
#line 227 "parser.y"
                      {CurrentSemanticValue.stmt = null; }
#line default
        break;
      case 38: // MethodDeclarator -> IDENTIFIER, '(', FormalParameterList_Opt, ')', Dims_Opt
#line 232 "parser.y"
                                                        {CurrentSemanticValue.arrlst =  new ArrayList() { ValueStack[ValueStack.Depth-5].name, ValueStack[ValueStack.Depth-3].stmts, ValueStack[ValueStack.Depth-1] };}
#line default
        break;
      case 39: // FormalParameterList_Opt -> FormalParameterList
#line 237 "parser.y"
                                { CurrentSemanticValue.stmts = ValueStack[ValueStack.Depth-1].stmts; }
#line default
        break;
      case 40: // FormalParameterList_Opt -> /* empty */
#line 238 "parser.y"
                          { CurrentSemanticValue.stmts = null; }
#line default
        break;
      case 41: // FormalParameterList -> FormalParameters
#line 245 "parser.y"
                               { CurrentSemanticValue.stmts = ValueStack[ValueStack.Depth-1].stmts; }
#line default
        break;
      case 42: // FormalParameters -> FormalParameter
#line 249 "parser.y"
                              { CurrentSemanticValue.stmts = new List<Statement> { ValueStack[ValueStack.Depth-1].stmt }; }
#line default
        break;
      case 43: // FormalParameters -> FormalParameters, ',', FormalParameter
#line 250 "parser.y"
                                             { CurrentSemanticValue.stmts = ValueStack[ValueStack.Depth-3].stmts; CurrentSemanticValue.stmts.Add(ValueStack[ValueStack.Depth-1].stmt); }
#line default
        break;
      case 44: // FormalParameter -> VariableModifiers, UnannType, VariableDeclaratorId
#line 254 "parser.y"
                                                       { CurrentSemanticValue.stmt = new VariableDeclaration(ValueStack[ValueStack.Depth-2].type, ValueStack[ValueStack.Depth-1].name); }
#line default
        break;
      case 45: // VariableModifiers -> VariableModifiers, VariableModifier
#line 257 "parser.y"
                                           { CurrentSemanticValue.modfs = ValueStack[ValueStack.Depth-2].modfs; CurrentSemanticValue.modfs.Add(ValueStack[ValueStack.Depth-1].modf); }
#line default
        break;
      case 46: // VariableModifiers -> /* empty */
#line 258 "parser.y"
                          { CurrentSemanticValue.modfs = new List<Modifier>(); }
#line default
        break;
      case 47: // VariableModifier -> FINAL
#line 262 "parser.y"
                      { CurrentSemanticValue.modf = Modifier.FINAL; }
#line default
        break;
      case 48: // Dims_Opt -> Dims
#line 268 "parser.y"
                     { CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
#line default
        break;
      case 49: // Dims_Opt -> /* empty */
#line 269 "parser.y"
                          { }
#line default
        break;
      case 51: // UnannType -> UnannReferenceType
#line 278 "parser.y"
                               { CurrentSemanticValue.type = ValueStack[ValueStack.Depth-1].type; }
#line default
        break;
      case 52: // UnannType -> UnannPrimitiveType
#line 279 "parser.y"
                               { CurrentSemanticValue.type = ValueStack[ValueStack.Depth-1].type; }
#line default
        break;
      case 53: // UnannPrimitiveType -> NumericType
#line 283 "parser.y"
                          { CurrentSemanticValue.type = ValueStack[ValueStack.Depth-1].type; }
#line default
        break;
      case 54: // UnannPrimitiveType -> BOOLEAN
#line 284 "parser.y"
                       { CurrentSemanticValue.type = new NamedType("BOOLEAN"); }
#line default
        break;
      case 59: // NumericType -> IntegralType
#line 304 "parser.y"
                           { CurrentSemanticValue.type = ValueStack[ValueStack.Depth-1].type; }
#line default
        break;
      case 60: // NumericType -> FloatingPointType
#line 305 "parser.y"
                               { CurrentSemanticValue.type = ValueStack[ValueStack.Depth-1].type; }
#line default
        break;
      case 61: // IntegralType -> BYTE
#line 309 "parser.y"
                     { CurrentSemanticValue.type = new NamedType("BYTE");  }
#line default
        break;
      case 62: // IntegralType -> SHORT
#line 310 "parser.y"
                      { CurrentSemanticValue.type = new NamedType("SHORT");  }
#line default
        break;
      case 63: // IntegralType -> INT
#line 311 "parser.y"
                    { CurrentSemanticValue.type = new NamedType("INT");}
#line default
        break;
      case 64: // IntegralType -> LONG
#line 312 "parser.y"
                     { CurrentSemanticValue.type = new NamedType("LONG"); }
#line default
        break;
      case 65: // IntegralType -> CHAR
#line 313 "parser.y"
                     { CurrentSemanticValue.type = new NamedType("CHAR"); }
#line default
        break;
      case 66: // FloatingPointType -> FLOAT
#line 317 "parser.y"
                      { CurrentSemanticValue.type = new NamedType("FLOAT"); }
#line default
        break;
      case 67: // FloatingPointType -> DOUBLE
#line 318 "parser.y"
                      { CurrentSemanticValue.type = new NamedType("DOUBLE"); }
#line default
        break;
      case 68: // UnannReferenceType -> UnannArrayType
#line 322 "parser.y"
                            { CurrentSemanticValue.type = ValueStack[ValueStack.Depth-1].type; }
#line default
        break;
      case 69: // UnannArrayType -> UnannTypeVariable, Dims
#line 328 "parser.y"
                                  { CurrentSemanticValue.type = new ArrayType(ValueStack[ValueStack.Depth-2].type); }
#line default
        break;
      case 70: // UnannTypeVariable -> IDENTIFIER
#line 332 "parser.y"
                         { CurrentSemanticValue.type = new NamedType(ValueStack[ValueStack.Depth-1].name); }
#line default
        break;
      case 71: // MethodBody -> Block
#line 337 "parser.y"
                       { CurrentSemanticValue.stmt= ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 72: // MethodBody -> ';'
#line 338 "parser.y"
                    { CurrentSemanticValue.stmt= null;}
#line default
        break;
      case 73: // Block -> '{', BlockStatements_Opt, '}'
#line 348 "parser.y"
                                      { CurrentSemanticValue.stmt = new BlockStatement(ValueStack[ValueStack.Depth-2].stmts); }
#line default
        break;
      case 74: // BlockStatements_Opt -> BlockStatements
#line 352 "parser.y"
                             { CurrentSemanticValue.stmts = ValueStack[ValueStack.Depth-1].stmts; }
#line default
        break;
      case 75: // BlockStatements_Opt -> /* empty */
#line 353 "parser.y"
                          { CurrentSemanticValue.stmts = null; }
#line default
        break;
      case 76: // BlockStatements -> BlockStatement
#line 357 "parser.y"
                            { CurrentSemanticValue.stmts = new List<Statement> { ValueStack[ValueStack.Depth-1].stmt }; }
#line default
        break;
      case 77: // BlockStatements -> BlockStatements, BlockStatement
#line 358 "parser.y"
                                        { CurrentSemanticValue.stmts = ValueStack[ValueStack.Depth-2].stmts; CurrentSemanticValue.stmts.Add(ValueStack[ValueStack.Depth-1].stmt); }
#line default
        break;
      case 78: // BlockStatement -> LocalVariableDeclarationStatement
#line 362 "parser.y"
                                           { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 79: // BlockStatement -> Statement
#line 363 "parser.y"
                         { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 80: // LocalVariableDeclarationStatement -> LocalVariableDeclaration, ';'
#line 367 "parser.y"
                                       { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-2].stmt; }
#line default
        break;
      case 81: // LocalVariableDeclaration -> UnannType, VariableDeclaratorList
#line 371 "parser.y"
                                          { CurrentSemanticValue.stmt = new VariableDeclarationList(ValueStack[ValueStack.Depth-2].type, ValueStack[ValueStack.Depth-1].strlst); }
#line default
        break;
      case 82: // VariableDeclaratorList -> VariableDeclarator
#line 377 "parser.y"
                               { CurrentSemanticValue.strlst = new List<string> { ValueStack[ValueStack.Depth-1].name }; }
#line default
        break;
      case 83: // VariableDeclaratorList -> VariableDeclaratorList, ',', VariableDeclarator
#line 378 "parser.y"
                                                    { CurrentSemanticValue.strlst = ValueStack[ValueStack.Depth-3].strlst; CurrentSemanticValue.strlst.Add(ValueStack[ValueStack.Depth-1].name); }
#line default
        break;
      case 84: // VariableDeclarator -> VariableDeclaratorId
#line 382 "parser.y"
                                 { CurrentSemanticValue.name = ValueStack[ValueStack.Depth-1].name; }
#line default
        break;
      case 85: // VariableDeclaratorId -> IDENTIFIER, Dims_Opt
#line 386 "parser.y"
                                { CurrentSemanticValue.name = ValueStack[ValueStack.Depth-2].name; }
#line default
        break;
      case 86: // Statement -> StatementWithoutTrailingSubstatement
#line 390 "parser.y"
                                             { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 87: // Statement -> IfThenStatement
#line 391 "parser.y"
                             {CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 88: // Statement -> IfThenElseStatement
#line 392 "parser.y"
                                {CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 89: // Statement -> WhileStatement
#line 393 "parser.y"
                            { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 90: // StatementNoShortIf -> StatementWithoutTrailingSubstatement
#line 397 "parser.y"
                                             {CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 91: // StatementNoShortIf -> IfThenElseStatementNoShortIf
#line 398 "parser.y"
                                       {CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 92: // StatementWithoutTrailingSubstatement -> ExpressionStatement
#line 403 "parser.y"
                                  { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 93: // StatementWithoutTrailingSubstatement -> SwitchStatement
#line 404 "parser.y"
                              { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 94: // StatementWithoutTrailingSubstatement -> BreakStatement
#line 405 "parser.y"
                             { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 95: // StatementWithoutTrailingSubstatement -> ContinueStatement
#line 406 "parser.y"
                                { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 96: // StatementWithoutTrailingSubstatement -> ReturnStatement
#line 407 "parser.y"
                              { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 97: // SwitchStatement -> SWITCH, '(', Expression, ')', SwitchBlock
#line 411 "parser.y"
                                               { CurrentSemanticValue.stmt = new SwitchStatement(ValueStack[ValueStack.Depth-3].expr, ValueStack[ValueStack.Depth-1]); }
#line default
        break;
      case 98: // SwitchBlock -> '{', SwitchBlockStatementGroups, '}'
#line 416 "parser.y"
                                              { CurrentSemanticValue = ValueStack[ValueStack.Depth-2].stmt;}
#line default
        break;
      case 99: // SwitchBlockStatementGroups -> SwitchBlockStatementGroup
#line 420 "parser.y"
                                      { CurrentSemanticValue.stmt = new List<SwitchBlockStatementGroup>(); }
#line default
        break;
      case 100: // SwitchBlockStatementGroups -> SwitchBlockStatementGroups, 
                //                               SwitchBlockStatementGroup
#line 421 "parser.y"
                                                          { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-2].stmt; CurrentSemanticValue.stmt.Add(ValueStack[ValueStack.Depth-1].stmt); }
#line default
        break;
      case 101: // SwitchBlockStatementGroup -> SwitchLabels, BlockStatements
#line 425 "parser.y"
                                        { CurrentSemanticValue.stmt = new SwitchBlockStatementGroup(ValueStack[ValueStack.Depth-2].stmt, ValueStack[ValueStack.Depth-1].stmts); }
#line default
        break;
      case 102: // SwitchLabels -> SwitchLabel
#line 434 "parser.y"
                           { CurrentSemanticValue.stmt = new List<SwitchLabelStatement>(); }
#line default
        break;
      case 103: // SwitchLabels -> SwitchLabels, SwitchLabel
#line 435 "parser.y"
                                     { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-2].stmt; CurrentSemanticValue.stmt.Add(ValueStack[ValueStack.Depth-1].stmt);}
#line default
        break;
      case 104: // SwitchLabel -> CASE, ConstantExpression, ':'
#line 439 "parser.y"
                                      { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-2].expr; }
#line default
        break;
      case 109: // ReturnStatement -> RETURN, Expression_opt, ';'
#line 462 "parser.y"
                                     {}
#line default
        break;
      case 112: // ThrowStatement -> THROW, Expression, ';'
#line 471 "parser.y"
                                 { CurrentSemanticValue.stmt = new ThrowStatement(ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-2].expr); }
#line default
        break;
      case 113: // SynchronizedStatement -> SYNCHRONIZED, '(', Expression, ')', Block
#line 475 "parser.y"
                                              { CurrentSemanticValue.stmt = new SynchronizedStatement(ValueStack[ValueStack.Depth-3].expr, ValueStack[ValueStack.Depth-1].stmt); }
#line default
        break;
      case 114: // ExpressionStatement -> StatementExpression, ';'
#line 479 "parser.y"
                                   { CurrentSemanticValue.stmt = new ExpressionStatement(ValueStack[ValueStack.Depth-2].expr); }
#line default
        break;
      case 115: // StatementExpression -> Assignment
#line 483 "parser.y"
                         { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 116: // IfThenStatement -> IF, '(', Expression, ')', Statement
#line 487 "parser.y"
                                         { CurrentSemanticValue.stmt = new IfStatement(ValueStack[ValueStack.Depth-3].expr, ValueStack[ValueStack.Depth-1].stmt,null); }
#line default
        break;
      case 117: // IfThenElseStatement -> IF, '(', Expression, ')', StatementNoShortIf, ELSE, 
                //                        Statement
#line 492 "parser.y"
                                                               { CurrentSemanticValue.stmt = new IfStatement(ValueStack[ValueStack.Depth-5].expr, ValueStack[ValueStack.Depth-3].stmt, ValueStack[ValueStack.Depth-1].stmt); }
#line default
        break;
      case 118: // IfThenElseStatementNoShortIf -> IF, '(', Expression, ')', StatementNoShortIf, 
                //                                 ELSE, StatementNoShortIf
#line 496 "parser.y"
                                                                      { CurrentSemanticValue.stmt = new IfStatement(ValueStack[ValueStack.Depth-5].expr, ValueStack[ValueStack.Depth-3].stmt, ValueStack[ValueStack.Depth-1].stmt); }
#line default
        break;
      case 119: // WhileStatement -> WHILE, '(', Expression, ')', Statement
#line 500 "parser.y"
                                           { CurrentSemanticValue.stmt = new WhileStatement(ValueStack[ValueStack.Depth-3].expr, ValueStack[ValueStack.Depth-1].stmt); }
#line default
        break;
      case 120: // Assignment -> LeftHandSide, AssignmentOperator, Expression
#line 507 "parser.y"
                                                 { CurrentSemanticValue.expr = new AssignmentExpression(ValueStack[ValueStack.Depth-3].expr, ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 121: // LeftHandSide -> ExpressionName
#line 511 "parser.y"
                            { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 122: // ExpressionName -> IDENTIFIER
#line 515 "parser.y"
                         { CurrentSemanticValue.expr = new VariableExpression(ValueStack[ValueStack.Depth-1].name);  }
#line default
        break;
      case 124: // AssignmentExpression -> Assignment
#line 523 "parser.y"
                         { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 125: // AssignmentExpression -> ConditionalExpression
#line 524 "parser.y"
                                  { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 126: // Primary -> PrimaryNoNewArray
#line 528 "parser.y"
                               { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 127: // PrimaryNoNewArray -> Literal
#line 532 "parser.y"
                       { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 128: // Literal -> IntegerLiteral
#line 536 "parser.y"
                            { CurrentSemanticValue.expr = new IntegerLiteralExpression(ValueStack[ValueStack.Depth-1].num); }
#line default
        break;
      case 129: // Literal -> FloatingPointLiteral
#line 537 "parser.y"
                                 { CurrentSemanticValue.expr = new FloatingPointLiteralExpression(ValueStack[ValueStack.Depth-1].floatnum); }
#line default
        break;
      case 130: // Literal -> BooleanLiteral
#line 538 "parser.y"
                            { CurrentSemanticValue.expr = new BooleanLiteralExpression(ValueStack[ValueStack.Depth-1].boolval); }
#line default
        break;
      case 131: // Literal -> CharacterLiteral
#line 539 "parser.y"
                              { CurrentSemanticValue.expr = new CharacterLiteralExpression(ValueStack[ValueStack.Depth-1].charval); }
#line default
        break;
      case 132: // Expression -> LambdaExpression
#line 545 "parser.y"
                              { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 133: // Expression -> AssignmentExpression
#line 546 "parser.y"
                                 { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 134: // LambdaExpression -> LambdaParameters, ARROW, LambdaBody
#line 550 "parser.y"
                                           { }
#line default
        break;
      case 135: // LambdaParameters -> /* empty */
#line 554 "parser.y"
                          { }
#line default
        break;
      case 136: // LambdaBody -> /* empty */
#line 558 "parser.y"
                          { }
#line default
        break;
      case 137: // ConditionalExpression -> ConditionalOrExpression
#line 562 "parser.y"
                                       { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 138: // ConditionalOrExpression -> ConditionalAndExpression
#line 568 "parser.y"
                                      { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 139: // ConditionalOrExpression -> ConditionalOrExpression, LOGICAL_OR, 
                //                            ConditionalAndExpression
#line 569 "parser.y"
                                                                { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, "||", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 140: // ConditionalAndExpression -> InclusiveOrExpression
#line 573 "parser.y"
                                    { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 141: // ConditionalAndExpression -> ConditionalAndExpression, LOGICAL_AND, 
                //                             InclusiveOrExpression
#line 574 "parser.y"
                                                               { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, "&&", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 142: // InclusiveOrExpression -> ExclusiveOrExpression
#line 578 "parser.y"
                                    { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 143: // InclusiveOrExpression -> InclusiveOrExpression, '|', ExclusiveOrExpression
#line 579 "parser.y"
                                                       { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, "|", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 144: // ExclusiveOrExpression -> AndExpression
#line 583 "parser.y"
                              { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 145: // ExclusiveOrExpression -> ExclusiveOrExpression, '^', AndExpression
#line 584 "parser.y"
                                                 { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, "^", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 146: // AndExpression -> EqualityExpression
#line 588 "parser.y"
                                 { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 147: // AndExpression -> AndExpression, '&', EqualityExpression
#line 589 "parser.y"
                                               { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, "&", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 148: // EqualityExpression -> RelationalExpression
#line 593 "parser.y"
                                   { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 149: // EqualityExpression -> EqualityExpression, EQUAL, RelationalExpression
#line 594 "parser.y"
                                                      { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, "==", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 150: // EqualityExpression -> EqualityExpression, NOT_EQUAL, RelationalExpression
#line 595 "parser.y"
                                                         { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, "!=", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 151: // RelationalExpression -> ShiftExpression
#line 599 "parser.y"
                               { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 152: // RelationalExpression -> RelationalExpression, '<', ShiftExpression
#line 600 "parser.y"
                                                  { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, "<", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 153: // RelationalExpression -> RelationalExpression, '>', ShiftExpression
#line 601 "parser.y"
                                                  { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, ">", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 154: // RelationalExpression -> RelationalExpression, LESS_THAN_OR_EQUAL, 
                //                         ShiftExpression
#line 602 "parser.y"
                                                             { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, "<=", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 155: // RelationalExpression -> RelationalExpression, GREATER_OR_EQUAL, ShiftExpression
#line 603 "parser.y"
                                                            { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, ">=", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 156: // RelationalExpression -> RelationalExpression, INSTANCEOF, ReferenceType
#line 604 "parser.y"
                                                      { CurrentSemanticValue.expr = new InstanceOfExpression(ValueStack[ValueStack.Depth-3].expr, ValueStack[ValueStack.Depth-1].type); }
#line default
        break;
      case 157: // ShiftExpression -> AdditiveExpression
#line 608 "parser.y"
                                 { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 158: // ShiftExpression -> ShiftExpression, LEFT_SHIFT, AdditiveExpression
#line 609 "parser.y"
                                                      { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, "<<", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 159: // ShiftExpression -> ShiftExpression, SIGNED_RIGHT_SHIFT, AdditiveExpression
#line 610 "parser.y"
                                                            { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, ">>", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 160: // ShiftExpression -> ShiftExpression, UNSIGNED_RIGHT_SHIFT, AdditiveExpression
#line 611 "parser.y"
                                                             { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, ">>>", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 161: // AdditiveExpression -> MultiplicativeExpression
#line 615 "parser.y"
                                      { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 162: // AdditiveExpression -> AdditiveExpression, '+', MultiplicativeExpression
#line 616 "parser.y"
                                                       { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, "+", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 163: // AdditiveExpression -> AdditiveExpression, '-', MultiplicativeExpression
#line 617 "parser.y"
                                                       { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, "-", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 164: // MultiplicativeExpression -> UnaryExpression
#line 621 "parser.y"
                               { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 165: // MultiplicativeExpression -> MultiplicativeExpression, '*', UnaryExpression
#line 622 "parser.y"
                                                     { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, "*", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 166: // MultiplicativeExpression -> MultiplicativeExpression, '/', UnaryExpression
#line 623 "parser.y"
                                                     { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, "/", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 167: // MultiplicativeExpression -> MultiplicativeExpression, '%', UnaryExpression
#line 624 "parser.y"
                                                     { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, "%", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 168: // UnaryExpression -> PreIncrementExpression
#line 628 "parser.y"
                                    { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 169: // UnaryExpression -> PreDecrementExpression
#line 629 "parser.y"
                                   { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 170: // UnaryExpression -> '+', UnaryExpression
#line 630 "parser.y"
                                 { CurrentSemanticValue.expr = new PreUnaryExpression("+", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 171: // UnaryExpression -> '-', UnaryExpression
#line 631 "parser.y"
                                 { CurrentSemanticValue.expr = new PreUnaryExpression("-", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 172: // UnaryExpression -> UnaryExpressionNotPlusMinus
#line 632 "parser.y"
                                       { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 173: // PreIncrementExpression -> INCREMENT, UnaryExpression
#line 640 "parser.y"
                                      { CurrentSemanticValue.expr = new PreUnaryExpression("++", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 174: // PreDecrementExpression -> DECREMENT, UnaryExpression
#line 644 "parser.y"
                                      { CurrentSemanticValue.expr = new PreUnaryExpression("--", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 175: // UnaryExpressionNotPlusMinus -> PostfixExpression
#line 648 "parser.y"
                                { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr;}
#line default
        break;
      case 176: // UnaryExpressionNotPlusMinus -> '~', UnaryExpression
#line 649 "parser.y"
                                 { CurrentSemanticValue.expr = new PreUnaryExpression("~", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 177: // UnaryExpressionNotPlusMinus -> '!', UnaryExpression
#line 650 "parser.y"
                                 { CurrentSemanticValue.expr = new PreUnaryExpression("!", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 178: // UnaryExpressionNotPlusMinus -> CastExpression
#line 651 "parser.y"
                             { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr;}
#line default
        break;
      case 179: // PostfixExpression -> Primary
#line 655 "parser.y"
                        { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 180: // PostfixExpression -> ExpressionName
#line 656 "parser.y"
                             { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 181: // PostfixExpression -> PostIncrementExpression
#line 657 "parser.y"
                                    { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 182: // PostfixExpression -> PostDecrementExpression
#line 658 "parser.y"
                                    { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 183: // PostIncrementExpression -> PostfixExpression, INCREMENT
#line 662 "parser.y"
                                        { CurrentSemanticValue.expr = new PostUnaryExpression(ValueStack[ValueStack.Depth-2].expr, "++"); }
#line default
        break;
      case 184: // PostDecrementExpression -> PostfixExpression, DECREMENT
#line 666 "parser.y"
                                        { CurrentSemanticValue.expr = new PostUnaryExpression(ValueStack[ValueStack.Depth-2].expr, "--"); }
#line default
        break;
      case 185: // CastExpression -> '(', PrimitiveType, ')', UnaryExpression
#line 670 "parser.y"
                                                   { CurrentSemanticValue.expr = new CastExpression(ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 191: // ConstantExpression -> Expression
#line 685 "parser.y"
                           { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
    }
#pragma warning restore 162, 1522
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliases != null && aliases.ContainsKey(terminal))
        return aliases[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }

#line 689 "parser.y"

public Parser(Scanner scanner) : base(scanner)
{
}
#line default
}
}
