// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, John Gough, QUT 2005-2014
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.5.2
// Machine:  VDI-VL17-061
// DateTime: 9/05/2017 5:27:10 PM
// UserName: n9768653
// Input file <parser.y - 9/05/2017 5:22:40 PM>

// options: conflicts lines gplex conflicts

using System;
using System.Collections.Generic;
using System.CodeDom.Compiler;
using System.Globalization;
using System.Text;
using QUT.Gppg;
using System.Collections;
using IFN660_Java_ECMAScript.AST;

namespace IFN660_Java_ECMAScript
{
public enum Tokens {error=128,EOF=129,NUMBER=130,IDENTIFIER=131,ABSTRACT=132,
    CONTINUE=133,FOR=134,NEW=135,SWITCH=136,ASSERT=137,DEFAULT=138,
    IF=139,PACKAGE=140,SYNCHRONIZED=141,BOOLEAN=142,DO=143,GOTO=144,
    PRIVATE=145,THIS=146,BREAK=147,DOUBLE=148,IMPLEMENTS=149,PROTECTED=150,
    THROW=151,BYTE=152,ELSE=153,IMPORT=154,PUBLIC=155,THROWS=156,
    CASE=157,ENUM=158,INSTANCEOF=159,RETURN=160,TRANSIENT=161,CATCH=162,
    EXTENDS=163,INT=164,SHORT=165,TRY=166,CHAR=167,FINAL=168,
    INTERFACE=169,STATIC=170,VOID=171,CLASS=172,FINALLY=173,LONG=174,
    STRICTFP=175,VOLATILE=176,CONST=177,FLOAT=178,NATIVE=179,SUPER=180,
    WHILE=181,IntegerLiteral=182,FloatingPointLiteral=183,BooleanLiteral=184,CharacterLiteral=185,StringLiteral=186,
    NullLiteral=187,ELLIPSIS=188,DOUBLE_COLON=189,EQUAL=190,GREATER_OR_EQUAL=191,LESS_THAN_OR_EQUAL=192,
    NOT_EQUAL=193,ARROW=194,LOGICAL_AND=195,LOGICAL_OR=196,INCREMENT=197,DECREMENT=198,
    LEFT_SHIFT=199,SIGNED_RIGHT_SHIFT=200,UNSIGNED_RIGHT_SHIFT=201,ADDITION_ASSIGNMENT=202,SUBTRACTION_ASSIGNMENT=203,MULTIPLICATION_ASSIGNMENT=204,
    DIVISION_ASSIGNMENT=205,MODULUS_ASSIGNMENT=206,BITWISE_AND_ASSIGNMENT=207,BITWISE_OR_ASSIGNMENT=208,BITWISE_XOR_ASSIGNMENT=209,LEFT_SHIFT_ASSIGNMENT=210,
    UNSIGNED_RIGHT_SHIFT_ASSIGNMENT=211,SIGNED_RIGHT_SHIFT_ASSIGNMENT=212};

public struct ValueType
#line 11 "parser.y"
{
    public long num;
	public double floatnum;
	public bool boolval;
	public char charval;
    public string name;
	public Statement stmt;
	public List<Statement> stmts;
	public Expression expr;
	public AST.Type type;
	public Modifier modf;
	public List<Modifier> modfs;
	public ArrayList arrlst;
	public List<string> strlst;
}
#line default
// Abstract base class for GPLEX scanners
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public abstract class ScanBase : AbstractScanner<ValueType,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

// Utility class for encapsulating token information
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public class ScanObj {
  public int token;
  public ValueType yylval;
  public LexLocation yylloc;
  public ScanObj( int t, ValueType val, LexLocation loc ) {
    this.token = t; this.yylval = val; this.yylloc = loc;
  }
}

[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public class Parser: ShiftReduceParser<ValueType, LexLocation>
{
  // Verbatim content from parser.y - 9/05/2017 5:22:40 PM
#line 7 "parser.y"
public static Statement root;
#line default
  // End verbatim content from parser.y - 9/05/2017 5:22:40 PM

#pragma warning disable 649
  private static Dictionary<int, string> aliases;
#pragma warning restore 649
  private static Rule[] rules = new Rule[120];
  private static State[] states = new State[145];
  private static string[] nonTerms = new string[] {
      "Literal", "StatementExpression", "Assignment", "LeftHandSide", "ExpressionName", 
      "TypeParameters_opt", "Superclass_opt", "Superinterfaces_opt", "AssignmentExpression", 
      "PrimaryNoNewArray", "Expression", "LambdaExpression", "LambdaBody", "ConditionalExpression", 
      "ConditionalOrExpression", "ConditionalAndExpression", "InclusiveOrExpression", 
      "ExclusiveOrExpression", "AndExpression", "EqualityExpression", "RelationalExpression", 
      "ShiftExpression", "AdditiveExpression", "MultiplicativeExpression", "UnaryExpression", 
      "PostfixExpression", "Primary", "Statement", "CompilationUnit", "TypeDeclaration", 
      "ClassDeclaration", "NormalClassDeclaration", "ClassBodyDeclaration", "ExpressionStatement", 
      "StatementWithoutTrailingSubstatement", "LocalVariableDeclaration", "LocalVariableDeclarationStatement", 
      "BlockStatement", "Throws_opt", "ClassMemberDeclaration", "MethodDeclaration", 
      "FormalParameter", "PackageDeclaration_opt", "Block", "MethodBody", "TypeDeclarations", 
      "ClassBody", "ClassBodyDeclarations", "BlockStatements", "BlockStatements_Opt", 
      "FormalParameters", "FormalParameterList", "FormalParameterList_Opt", "ImportDeclarations", 
      "Result", "FloatingPointType", "IntegralType", "NumericType", "UnannType", 
      "UnannPrimitiveType", "UnannReferenceType", "UnannArrayType", "UnannTypeVariable", 
      "ClassModifier", "MethodModifier", "VariableModifier", "ClassModifiers", 
      "MethodModifiers", "VariableModifiers", "VariableDeclaratorId", "VariableDeclarator", 
      "MethodHeader", "MethodDeclarator", "VariableDeclaratorList", "Program", 
      "$accept", "Empty", "Dims_Opt", "Dims", "AssignmentOperator", "LambdaParameters", 
      };

  static Parser() {
    states[0] = new State(-5,new int[]{-75,1,-29,3,-43,4});
    states[1] = new State(new int[]{129,2});
    states[2] = new State(-1);
    states[3] = new State(-2);
    states[4] = new State(-6,new int[]{-54,5});
    states[5] = new State(-8,new int[]{-46,6});
    states[6] = new State(new int[]{129,-4,172,-13,155,-13,150,-13,145,-13,132,-13,170,-13,168,-13,175,-13},new int[]{-30,7,-31,8,-32,9,-67,10});
    states[7] = new State(-7);
    states[8] = new State(-9);
    states[9] = new State(-10);
    states[10] = new State(new int[]{172,11,155,138,150,139,145,140,132,141,170,142,168,143,175,144},new int[]{-64,137});
    states[11] = new State(new int[]{131,12});
    states[12] = new State(-21,new int[]{-6,13});
    states[13] = new State(-22,new int[]{-7,14});
    states[14] = new State(-23,new int[]{-8,15});
    states[15] = new State(new int[]{123,17},new int[]{-47,16});
    states[16] = new State(-11);
    states[17] = new State(-26,new int[]{-48,18});
    states[18] = new State(new int[]{125,19,171,-31,131,-31,152,-31,165,-31,164,-31,174,-31,167,-31,178,-31,148,-31,142,-31,155,-31,170,-31},new int[]{-33,20,-40,21,-41,22,-68,23});
    states[19] = new State(-24);
    states[20] = new State(-25);
    states[21] = new State(-27);
    states[22] = new State(-28);
    states[23] = new State(new int[]{171,133,131,130,152,54,165,55,164,56,174,57,167,58,178,60,148,61,142,62,155,135,170,136},new int[]{-72,24,-65,112,-55,113,-59,134,-61,46,-62,47,-63,48,-60,51,-58,52,-57,53,-56,59});
    states[24] = new State(new int[]{123,27,59,111},new int[]{-45,25,-44,26});
    states[25] = new State(-29);
    states[26] = new State(-67);
    states[27] = new State(new int[]{131,50,152,54,165,55,164,56,174,57,167,58,178,60,148,61,142,62,125,-71},new int[]{-50,28,-49,30,-38,110,-37,32,-36,33,-59,35,-61,46,-62,47,-63,48,-60,51,-58,52,-57,53,-56,59,-28,63,-35,64,-34,65,-2,66,-3,68,-4,69,-5,109});
    states[28] = new State(new int[]{125,29});
    states[29] = new State(-69);
    states[30] = new State(new int[]{131,50,152,54,165,55,164,56,174,57,167,58,178,60,148,61,142,62,125,-70},new int[]{-38,31,-37,32,-36,33,-59,35,-61,46,-62,47,-63,48,-60,51,-58,52,-57,53,-56,59,-28,63,-35,64,-34,65,-2,66,-3,68,-4,69,-5,109});
    states[31] = new State(-73);
    states[32] = new State(-74);
    states[33] = new State(new int[]{59,34});
    states[34] = new State(-76);
    states[35] = new State(new int[]{131,40},new int[]{-74,36,-71,45,-70,39});
    states[36] = new State(new int[]{44,37,59,-77});
    states[37] = new State(new int[]{131,40},new int[]{-71,38,-70,39});
    states[38] = new State(-79);
    states[39] = new State(-80);
    states[40] = new State(new int[]{91,43,44,-49,59,-49,41,-49},new int[]{-78,41,-79,42});
    states[41] = new State(-81);
    states[42] = new State(-48);
    states[43] = new State(new int[]{93,44});
    states[44] = new State(-50);
    states[45] = new State(-78);
    states[46] = new State(-51);
    states[47] = new State(-64);
    states[48] = new State(new int[]{91,43},new int[]{-79,49});
    states[49] = new State(-65);
    states[50] = new State(new int[]{91,-66,61,-88});
    states[51] = new State(-52);
    states[52] = new State(-53);
    states[53] = new State(-55);
    states[54] = new State(-57);
    states[55] = new State(-58);
    states[56] = new State(-59);
    states[57] = new State(-60);
    states[58] = new State(-61);
    states[59] = new State(-56);
    states[60] = new State(-62);
    states[61] = new State(-63);
    states[62] = new State(-54);
    states[63] = new State(-75);
    states[64] = new State(-82);
    states[65] = new State(-83);
    states[66] = new State(new int[]{59,67});
    states[67] = new State(-84);
    states[68] = new State(-85);
    states[69] = new State(new int[]{61,108},new int[]{-80,70});
    states[70] = new State(new int[]{131,79,182,99,184,100,183,101,194,-100},new int[]{-11,71,-12,72,-81,73,-9,76,-3,77,-4,69,-5,78,-14,80,-15,81,-16,107,-17,106,-18,86,-19,87,-20,88,-21,89,-22,90,-23,91,-24,105,-25,94,-26,95,-27,96,-10,97,-1,98});
    states[71] = new State(-86);
    states[72] = new State(-97);
    states[73] = new State(new int[]{194,74});
    states[74] = new State(-101,new int[]{-13,75});
    states[75] = new State(-99);
    states[76] = new State(-98);
    states[77] = new State(-90);
    states[78] = new State(new int[]{61,-87,43,-119,45,-119,195,-119,196,-119,59,-119});
    states[79] = new State(-88);
    states[80] = new State(-91);
    states[81] = new State(new int[]{196,82,59,-102});
    states[82] = new State(new int[]{182,99,184,100,183,101,131,79},new int[]{-16,83,-17,106,-18,86,-19,87,-20,88,-21,89,-22,90,-23,91,-24,105,-25,94,-26,95,-27,96,-10,97,-1,98,-5,102});
    states[83] = new State(new int[]{195,84,196,-104,59,-104});
    states[84] = new State(new int[]{182,99,184,100,183,101,131,79},new int[]{-17,85,-18,86,-19,87,-20,88,-21,89,-22,90,-23,91,-24,105,-25,94,-26,95,-27,96,-10,97,-1,98,-5,102});
    states[85] = new State(-106);
    states[86] = new State(-107);
    states[87] = new State(-108);
    states[88] = new State(-109);
    states[89] = new State(-110);
    states[90] = new State(-111);
    states[91] = new State(new int[]{43,92,45,103,195,-112,196,-112,59,-112});
    states[92] = new State(new int[]{182,99,184,100,183,101,131,79},new int[]{-24,93,-25,94,-26,95,-27,96,-10,97,-1,98,-5,102});
    states[93] = new State(-114);
    states[94] = new State(-116);
    states[95] = new State(-117);
    states[96] = new State(-118);
    states[97] = new State(-92);
    states[98] = new State(-93);
    states[99] = new State(-94);
    states[100] = new State(-95);
    states[101] = new State(-96);
    states[102] = new State(-119);
    states[103] = new State(new int[]{182,99,184,100,183,101,131,79},new int[]{-24,104,-25,94,-26,95,-27,96,-10,97,-1,98,-5,102});
    states[104] = new State(-115);
    states[105] = new State(-113);
    states[106] = new State(-105);
    states[107] = new State(new int[]{195,84,196,-103,59,-103});
    states[108] = new State(-89);
    states[109] = new State(-87);
    states[110] = new State(-72);
    states[111] = new State(-68);
    states[112] = new State(-30);
    states[113] = new State(new int[]{131,117},new int[]{-73,114});
    states[114] = new State(-3,new int[]{-39,115,-77,116});
    states[115] = new State(-34);
    states[116] = new State(-37);
    states[117] = new State(new int[]{40,118});
    states[118] = new State(new int[]{131,-46,152,-46,165,-46,164,-46,174,-46,167,-46,178,-46,148,-46,142,-46,168,-46,41,-40},new int[]{-53,119,-52,122,-51,123,-42,132,-69,126});
    states[119] = new State(new int[]{41,120});
    states[120] = new State(new int[]{91,43,123,-49,59,-49},new int[]{-78,121,-79,42});
    states[121] = new State(-38);
    states[122] = new State(-39);
    states[123] = new State(new int[]{44,124,41,-41});
    states[124] = new State(-46,new int[]{-42,125,-69,126});
    states[125] = new State(-43);
    states[126] = new State(new int[]{131,130,152,54,165,55,164,56,174,57,167,58,178,60,148,61,142,62,168,131},new int[]{-59,127,-66,129,-61,46,-62,47,-63,48,-60,51,-58,52,-57,53,-56,59});
    states[127] = new State(new int[]{131,40},new int[]{-70,128});
    states[128] = new State(-44);
    states[129] = new State(-45);
    states[130] = new State(-66);
    states[131] = new State(-47);
    states[132] = new State(-42);
    states[133] = new State(-35);
    states[134] = new State(-36);
    states[135] = new State(-32);
    states[136] = new State(-33);
    states[137] = new State(-12);
    states[138] = new State(-14);
    states[139] = new State(-15);
    states[140] = new State(-16);
    states[141] = new State(-17);
    states[142] = new State(-18);
    states[143] = new State(-19);
    states[144] = new State(-20);

    for (int sNo = 0; sNo < states.Length; sNo++) states[sNo].number = sNo;

    rules[1] = new Rule(-76, new int[]{-75,129});
    rules[2] = new Rule(-75, new int[]{-29});
    rules[3] = new Rule(-77, new int[]{});
    rules[4] = new Rule(-29, new int[]{-43,-54,-46});
    rules[5] = new Rule(-43, new int[]{});
    rules[6] = new Rule(-54, new int[]{});
    rules[7] = new Rule(-46, new int[]{-46,-30});
    rules[8] = new Rule(-46, new int[]{});
    rules[9] = new Rule(-30, new int[]{-31});
    rules[10] = new Rule(-31, new int[]{-32});
    rules[11] = new Rule(-32, new int[]{-67,172,131,-6,-7,-8,-47});
    rules[12] = new Rule(-67, new int[]{-67,-64});
    rules[13] = new Rule(-67, new int[]{});
    rules[14] = new Rule(-64, new int[]{155});
    rules[15] = new Rule(-64, new int[]{150});
    rules[16] = new Rule(-64, new int[]{145});
    rules[17] = new Rule(-64, new int[]{132});
    rules[18] = new Rule(-64, new int[]{170});
    rules[19] = new Rule(-64, new int[]{168});
    rules[20] = new Rule(-64, new int[]{175});
    rules[21] = new Rule(-6, new int[]{});
    rules[22] = new Rule(-7, new int[]{});
    rules[23] = new Rule(-8, new int[]{});
    rules[24] = new Rule(-47, new int[]{123,-48,125});
    rules[25] = new Rule(-48, new int[]{-48,-33});
    rules[26] = new Rule(-48, new int[]{});
    rules[27] = new Rule(-33, new int[]{-40});
    rules[28] = new Rule(-40, new int[]{-41});
    rules[29] = new Rule(-41, new int[]{-68,-72,-45});
    rules[30] = new Rule(-68, new int[]{-68,-65});
    rules[31] = new Rule(-68, new int[]{});
    rules[32] = new Rule(-65, new int[]{155});
    rules[33] = new Rule(-65, new int[]{170});
    rules[34] = new Rule(-72, new int[]{-55,-73,-39});
    rules[35] = new Rule(-55, new int[]{171});
    rules[36] = new Rule(-55, new int[]{-59});
    rules[37] = new Rule(-39, new int[]{-77});
    rules[38] = new Rule(-73, new int[]{131,40,-53,41,-78});
    rules[39] = new Rule(-53, new int[]{-52});
    rules[40] = new Rule(-53, new int[]{});
    rules[41] = new Rule(-52, new int[]{-51});
    rules[42] = new Rule(-51, new int[]{-42});
    rules[43] = new Rule(-51, new int[]{-51,44,-42});
    rules[44] = new Rule(-42, new int[]{-69,-59,-70});
    rules[45] = new Rule(-69, new int[]{-69,-66});
    rules[46] = new Rule(-69, new int[]{});
    rules[47] = new Rule(-66, new int[]{168});
    rules[48] = new Rule(-78, new int[]{-79});
    rules[49] = new Rule(-78, new int[]{});
    rules[50] = new Rule(-79, new int[]{91,93});
    rules[51] = new Rule(-59, new int[]{-61});
    rules[52] = new Rule(-59, new int[]{-60});
    rules[53] = new Rule(-60, new int[]{-58});
    rules[54] = new Rule(-60, new int[]{142});
    rules[55] = new Rule(-58, new int[]{-57});
    rules[56] = new Rule(-58, new int[]{-56});
    rules[57] = new Rule(-57, new int[]{152});
    rules[58] = new Rule(-57, new int[]{165});
    rules[59] = new Rule(-57, new int[]{164});
    rules[60] = new Rule(-57, new int[]{174});
    rules[61] = new Rule(-57, new int[]{167});
    rules[62] = new Rule(-56, new int[]{178});
    rules[63] = new Rule(-56, new int[]{148});
    rules[64] = new Rule(-61, new int[]{-62});
    rules[65] = new Rule(-62, new int[]{-63,-79});
    rules[66] = new Rule(-63, new int[]{131});
    rules[67] = new Rule(-45, new int[]{-44});
    rules[68] = new Rule(-45, new int[]{59});
    rules[69] = new Rule(-44, new int[]{123,-50,125});
    rules[70] = new Rule(-50, new int[]{-49});
    rules[71] = new Rule(-50, new int[]{});
    rules[72] = new Rule(-49, new int[]{-38});
    rules[73] = new Rule(-49, new int[]{-49,-38});
    rules[74] = new Rule(-38, new int[]{-37});
    rules[75] = new Rule(-38, new int[]{-28});
    rules[76] = new Rule(-37, new int[]{-36,59});
    rules[77] = new Rule(-36, new int[]{-59,-74});
    rules[78] = new Rule(-74, new int[]{-71});
    rules[79] = new Rule(-74, new int[]{-74,44,-71});
    rules[80] = new Rule(-71, new int[]{-70});
    rules[81] = new Rule(-70, new int[]{131,-78});
    rules[82] = new Rule(-28, new int[]{-35});
    rules[83] = new Rule(-35, new int[]{-34});
    rules[84] = new Rule(-34, new int[]{-2,59});
    rules[85] = new Rule(-2, new int[]{-3});
    rules[86] = new Rule(-3, new int[]{-4,-80,-11});
    rules[87] = new Rule(-4, new int[]{-5});
    rules[88] = new Rule(-5, new int[]{131});
    rules[89] = new Rule(-80, new int[]{61});
    rules[90] = new Rule(-9, new int[]{-3});
    rules[91] = new Rule(-9, new int[]{-14});
    rules[92] = new Rule(-27, new int[]{-10});
    rules[93] = new Rule(-10, new int[]{-1});
    rules[94] = new Rule(-1, new int[]{182});
    rules[95] = new Rule(-1, new int[]{184});
    rules[96] = new Rule(-1, new int[]{183});
    rules[97] = new Rule(-11, new int[]{-12});
    rules[98] = new Rule(-11, new int[]{-9});
    rules[99] = new Rule(-12, new int[]{-81,194,-13});
    rules[100] = new Rule(-81, new int[]{});
    rules[101] = new Rule(-13, new int[]{});
    rules[102] = new Rule(-14, new int[]{-15});
    rules[103] = new Rule(-15, new int[]{-16});
    rules[104] = new Rule(-15, new int[]{-15,196,-16});
    rules[105] = new Rule(-16, new int[]{-17});
    rules[106] = new Rule(-16, new int[]{-16,195,-17});
    rules[107] = new Rule(-17, new int[]{-18});
    rules[108] = new Rule(-18, new int[]{-19});
    rules[109] = new Rule(-19, new int[]{-20});
    rules[110] = new Rule(-20, new int[]{-21});
    rules[111] = new Rule(-21, new int[]{-22});
    rules[112] = new Rule(-22, new int[]{-23});
    rules[113] = new Rule(-23, new int[]{-24});
    rules[114] = new Rule(-23, new int[]{-23,43,-24});
    rules[115] = new Rule(-23, new int[]{-23,45,-24});
    rules[116] = new Rule(-24, new int[]{-25});
    rules[117] = new Rule(-25, new int[]{-26});
    rules[118] = new Rule(-26, new int[]{-27});
    rules[119] = new Rule(-26, new int[]{-5});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
#pragma warning disable 162, 1522
    switch (action)
    {
      case 2: // Program -> CompilationUnit
#line 105 "parser.y"
                                   {root = ValueStack[ValueStack.Depth-1].stmt;}
#line default
        break;
      case 4: // CompilationUnit -> PackageDeclaration_opt, ImportDeclarations, TypeDeclarations
#line 113 "parser.y"
                                                               { CurrentSemanticValue.stmt = new CompilationUnitDeclaration(ValueStack[ValueStack.Depth-3].stmt,ValueStack[ValueStack.Depth-2].stmts,ValueStack[ValueStack.Depth-1].stmts);  }
#line default
        break;
      case 7: // TypeDeclarations -> TypeDeclarations, TypeDeclaration
#line 125 "parser.y"
                                          { CurrentSemanticValue.stmts = ValueStack[ValueStack.Depth-2].stmts; CurrentSemanticValue.stmts.Add(ValueStack[ValueStack.Depth-1].stmt); }
#line default
        break;
      case 8: // TypeDeclarations -> /* empty */
#line 126 "parser.y"
                          { CurrentSemanticValue.stmts = new List<Statement>();}
#line default
        break;
      case 9: // TypeDeclaration -> ClassDeclaration
#line 130 "parser.y"
                                                            { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 10: // ClassDeclaration -> NormalClassDeclaration
#line 134 "parser.y"
                                                             { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 11: // NormalClassDeclaration -> ClassModifiers, CLASS, IDENTIFIER, TypeParameters_opt, 
               //                           Superclass_opt, Superinterfaces_opt, ClassBody
#line 138 "parser.y"
                                                                                                    {  CurrentSemanticValue.stmt = new ClassDeclaration(ValueStack[ValueStack.Depth-5].name,ValueStack[ValueStack.Depth-7].modfs,ValueStack[ValueStack.Depth-1].stmts); }
#line default
        break;
      case 12: // ClassModifiers -> ClassModifiers, ClassModifier
#line 142 "parser.y"
                                       { CurrentSemanticValue.modfs = ValueStack[ValueStack.Depth-2].modfs; CurrentSemanticValue.modfs.Add(ValueStack[ValueStack.Depth-1].modf); }
#line default
        break;
      case 13: // ClassModifiers -> /* empty */
#line 143 "parser.y"
                          { CurrentSemanticValue.modfs = new List<Modifier>(); }
#line default
        break;
      case 14: // ClassModifier -> PUBLIC
#line 147 "parser.y"
                      { CurrentSemanticValue.modf = Modifier.PUBLIC; }
#line default
        break;
      case 15: // ClassModifier -> PROTECTED
#line 148 "parser.y"
                         { CurrentSemanticValue.modf = Modifier.PROTECTED; }
#line default
        break;
      case 16: // ClassModifier -> PRIVATE
#line 149 "parser.y"
                        { CurrentSemanticValue.modf = Modifier.PRIVATE; }
#line default
        break;
      case 17: // ClassModifier -> ABSTRACT
#line 150 "parser.y"
                         { CurrentSemanticValue.modf = Modifier.ABSTRACT; }
#line default
        break;
      case 18: // ClassModifier -> STATIC
#line 151 "parser.y"
                       { CurrentSemanticValue.modf = Modifier.STATIC; }
#line default
        break;
      case 19: // ClassModifier -> FINAL
#line 152 "parser.y"
                      { CurrentSemanticValue.modf = Modifier.FINAL; }
#line default
        break;
      case 20: // ClassModifier -> STRICTFP
#line 153 "parser.y"
                         { CurrentSemanticValue.modf = Modifier.STRICTFP; }
#line default
        break;
      case 21: // TypeParameters_opt -> /* empty */
#line 158 "parser.y"
                                        { CurrentSemanticValue.expr = null; }
#line default
        break;
      case 22: // Superclass_opt -> /* empty */
#line 161 "parser.y"
                                     { CurrentSemanticValue.expr = null; }
#line default
        break;
      case 23: // Superinterfaces_opt -> /* empty */
#line 164 "parser.y"
                                         { CurrentSemanticValue.expr = null; }
#line default
        break;
      case 24: // ClassBody -> '{', ClassBodyDeclarations, '}'
#line 168 "parser.y"
                                        { CurrentSemanticValue.stmts = ValueStack[ValueStack.Depth-2].stmts; }
#line default
        break;
      case 25: // ClassBodyDeclarations -> ClassBodyDeclarations, ClassBodyDeclaration
#line 175 "parser.y"
                                                 { CurrentSemanticValue.stmts = ValueStack[ValueStack.Depth-2].stmts; CurrentSemanticValue.stmts.Add(ValueStack[ValueStack.Depth-1].stmt); }
#line default
        break;
      case 26: // ClassBodyDeclarations -> /* empty */
#line 176 "parser.y"
                          { CurrentSemanticValue.stmts = new List<Statement>(); }
#line default
        break;
      case 27: // ClassBodyDeclaration -> ClassMemberDeclaration
#line 180 "parser.y"
                                  { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 28: // ClassMemberDeclaration -> MethodDeclaration
#line 185 "parser.y"
                               { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 29: // MethodDeclaration -> MethodModifiers, MethodHeader, MethodBody
#line 190 "parser.y"
                                               { CurrentSemanticValue.stmt = new MethodDeclaration( (string)((ArrayList)ValueStack[ValueStack.Depth-2].arrlst[1])[0], ValueStack[ValueStack.Depth-3].modfs, ValueStack[ValueStack.Depth-1].stmt, (AST.Type)ValueStack[ValueStack.Depth-2].arrlst[0], (List<Statement>)((ArrayList)ValueStack[ValueStack.Depth-2].arrlst[1])[1]); }
#line default
        break;
      case 30: // MethodModifiers -> MethodModifiers, MethodModifier
#line 194 "parser.y"
                                              { CurrentSemanticValue.modfs = ValueStack[ValueStack.Depth-2].modfs; CurrentSemanticValue.modfs.Add(ValueStack[ValueStack.Depth-1].modf); }
#line default
        break;
      case 31: // MethodModifiers -> /* empty */
#line 195 "parser.y"
                          { CurrentSemanticValue.modfs = new List<Modifier>(); }
#line default
        break;
      case 32: // MethodModifier -> PUBLIC
#line 199 "parser.y"
                      { CurrentSemanticValue.modf = Modifier.PUBLIC; }
#line default
        break;
      case 33: // MethodModifier -> STATIC
#line 200 "parser.y"
                            { CurrentSemanticValue.modf = Modifier.STATIC; }
#line default
        break;
      case 34: // MethodHeader -> Result, MethodDeclarator, Throws_opt
#line 204 "parser.y"
                                           {CurrentSemanticValue.arrlst = new ArrayList() { ValueStack[ValueStack.Depth-3].type, ValueStack[ValueStack.Depth-2].arrlst, ValueStack[ValueStack.Depth-1].stmt } ; }
#line default
        break;
      case 35: // Result -> VOID
#line 212 "parser.y"
                     {CurrentSemanticValue.type = new NamedType("VOID"); }
#line default
        break;
      case 36: // Result -> UnannType
#line 213 "parser.y"
                         {CurrentSemanticValue.type = ValueStack[ValueStack.Depth-1].type; }
#line default
        break;
      case 37: // Throws_opt -> Empty
#line 217 "parser.y"
                      {CurrentSemanticValue.stmt = null; }
#line default
        break;
      case 38: // MethodDeclarator -> IDENTIFIER, '(', FormalParameterList_Opt, ')', Dims_Opt
#line 222 "parser.y"
                                                        {CurrentSemanticValue.arrlst =  new ArrayList() { ValueStack[ValueStack.Depth-5].name, ValueStack[ValueStack.Depth-3].stmts, ValueStack[ValueStack.Depth-1] };}
#line default
        break;
      case 39: // FormalParameterList_Opt -> FormalParameterList
#line 227 "parser.y"
                                { CurrentSemanticValue.stmts = ValueStack[ValueStack.Depth-1].stmts; }
#line default
        break;
      case 40: // FormalParameterList_Opt -> /* empty */
#line 228 "parser.y"
                          { CurrentSemanticValue.stmts = null; }
#line default
        break;
      case 41: // FormalParameterList -> FormalParameters
#line 235 "parser.y"
                               { CurrentSemanticValue.stmts = ValueStack[ValueStack.Depth-1].stmts; }
#line default
        break;
      case 42: // FormalParameters -> FormalParameter
#line 239 "parser.y"
                              { CurrentSemanticValue.stmts = new List<Statement> { ValueStack[ValueStack.Depth-1].stmt }; }
#line default
        break;
      case 43: // FormalParameters -> FormalParameters, ',', FormalParameter
#line 240 "parser.y"
                                             { CurrentSemanticValue.stmts = ValueStack[ValueStack.Depth-3].stmts; CurrentSemanticValue.stmts.Add(ValueStack[ValueStack.Depth-1].stmt); }
#line default
        break;
      case 44: // FormalParameter -> VariableModifiers, UnannType, VariableDeclaratorId
#line 244 "parser.y"
                                                       { CurrentSemanticValue.stmt = new VariableDeclaration(ValueStack[ValueStack.Depth-2].type, ValueStack[ValueStack.Depth-1].name); }
#line default
        break;
      case 45: // VariableModifiers -> VariableModifiers, VariableModifier
#line 247 "parser.y"
                                           { CurrentSemanticValue.modfs = ValueStack[ValueStack.Depth-2].modfs; CurrentSemanticValue.modfs.Add(ValueStack[ValueStack.Depth-1].modf); }
#line default
        break;
      case 46: // VariableModifiers -> /* empty */
#line 248 "parser.y"
                          { CurrentSemanticValue.modfs = new List<Modifier>(); }
#line default
        break;
      case 47: // VariableModifier -> FINAL
#line 252 "parser.y"
                      { CurrentSemanticValue.modf = Modifier.FINAL; }
#line default
        break;
      case 48: // Dims_Opt -> Dims
#line 258 "parser.y"
                     { CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
#line default
        break;
      case 49: // Dims_Opt -> /* empty */
#line 259 "parser.y"
                          { }
#line default
        break;
      case 51: // UnannType -> UnannReferenceType
#line 268 "parser.y"
                               { CurrentSemanticValue.type = ValueStack[ValueStack.Depth-1].type; }
#line default
        break;
      case 52: // UnannType -> UnannPrimitiveType
#line 269 "parser.y"
                               { CurrentSemanticValue.type = ValueStack[ValueStack.Depth-1].type; }
#line default
        break;
      case 53: // UnannPrimitiveType -> NumericType
#line 273 "parser.y"
                          { CurrentSemanticValue.type = ValueStack[ValueStack.Depth-1].type; }
#line default
        break;
      case 54: // UnannPrimitiveType -> BOOLEAN
#line 274 "parser.y"
                       { CurrentSemanticValue.type = new NamedType("BOOLEAN"); }
#line default
        break;
      case 55: // NumericType -> IntegralType
#line 278 "parser.y"
                           { CurrentSemanticValue.type = ValueStack[ValueStack.Depth-1].type; }
#line default
        break;
      case 56: // NumericType -> FloatingPointType
#line 279 "parser.y"
                               { CurrentSemanticValue.type = ValueStack[ValueStack.Depth-1].type; }
#line default
        break;
      case 57: // IntegralType -> BYTE
#line 283 "parser.y"
                     { CurrentSemanticValue.type = new NamedType("BYTE");  }
#line default
        break;
      case 58: // IntegralType -> SHORT
#line 284 "parser.y"
                      { CurrentSemanticValue.type = new NamedType("SHORT");  }
#line default
        break;
      case 59: // IntegralType -> INT
#line 285 "parser.y"
                    { CurrentSemanticValue.type = new NamedType("INT");}
#line default
        break;
      case 60: // IntegralType -> LONG
#line 286 "parser.y"
                     { CurrentSemanticValue.type = new NamedType("LONG"); }
#line default
        break;
      case 61: // IntegralType -> CHAR
#line 287 "parser.y"
                     { CurrentSemanticValue.type = new NamedType("CHAR"); }
#line default
        break;
      case 62: // FloatingPointType -> FLOAT
#line 291 "parser.y"
                      { CurrentSemanticValue.type = new NamedType("FLOAT"); }
#line default
        break;
      case 63: // FloatingPointType -> DOUBLE
#line 292 "parser.y"
                      { CurrentSemanticValue.type = new NamedType("DOUBLE"); }
#line default
        break;
      case 64: // UnannReferenceType -> UnannArrayType
#line 296 "parser.y"
                            { CurrentSemanticValue.type = ValueStack[ValueStack.Depth-1].type; }
#line default
        break;
      case 65: // UnannArrayType -> UnannTypeVariable, Dims
#line 302 "parser.y"
                                  { CurrentSemanticValue.type = new ArrayType(ValueStack[ValueStack.Depth-2].type); }
#line default
        break;
      case 66: // UnannTypeVariable -> IDENTIFIER
#line 306 "parser.y"
                         { CurrentSemanticValue.type = new NamedType(ValueStack[ValueStack.Depth-1].name); }
#line default
        break;
      case 67: // MethodBody -> Block
#line 311 "parser.y"
                       { CurrentSemanticValue.stmt= ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 68: // MethodBody -> ';'
#line 312 "parser.y"
                    { CurrentSemanticValue.stmt= null;}
#line default
        break;
      case 69: // Block -> '{', BlockStatements_Opt, '}'
#line 322 "parser.y"
                                      { CurrentSemanticValue.stmt = new BlockStatement(ValueStack[ValueStack.Depth-2].stmts); }
#line default
        break;
      case 70: // BlockStatements_Opt -> BlockStatements
#line 326 "parser.y"
                             { CurrentSemanticValue.stmts = ValueStack[ValueStack.Depth-1].stmts; }
#line default
        break;
      case 71: // BlockStatements_Opt -> /* empty */
#line 327 "parser.y"
                          { CurrentSemanticValue.stmts = null; }
#line default
        break;
      case 72: // BlockStatements -> BlockStatement
#line 331 "parser.y"
                            { CurrentSemanticValue.stmts = new List<Statement> { ValueStack[ValueStack.Depth-1].stmt }; }
#line default
        break;
      case 73: // BlockStatements -> BlockStatements, BlockStatement
#line 332 "parser.y"
                                        { CurrentSemanticValue.stmts = ValueStack[ValueStack.Depth-2].stmts; CurrentSemanticValue.stmts.Add(ValueStack[ValueStack.Depth-1].stmt); }
#line default
        break;
      case 74: // BlockStatement -> LocalVariableDeclarationStatement
#line 336 "parser.y"
                                           { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 75: // BlockStatement -> Statement
#line 337 "parser.y"
                         { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 76: // LocalVariableDeclarationStatement -> LocalVariableDeclaration, ';'
#line 341 "parser.y"
                                       { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-2].stmt; }
#line default
        break;
      case 77: // LocalVariableDeclaration -> UnannType, VariableDeclaratorList
#line 345 "parser.y"
                                          { CurrentSemanticValue.stmt = new VariableDeclarationList(ValueStack[ValueStack.Depth-2].type, ValueStack[ValueStack.Depth-1].strlst); }
#line default
        break;
      case 78: // VariableDeclaratorList -> VariableDeclarator
#line 351 "parser.y"
                               { CurrentSemanticValue.strlst = new List<string> { ValueStack[ValueStack.Depth-1].name }; }
#line default
        break;
      case 79: // VariableDeclaratorList -> VariableDeclaratorList, ',', VariableDeclarator
#line 352 "parser.y"
                                                    { CurrentSemanticValue.strlst = ValueStack[ValueStack.Depth-3].strlst; CurrentSemanticValue.strlst.Add(ValueStack[ValueStack.Depth-1].name); }
#line default
        break;
      case 80: // VariableDeclarator -> VariableDeclaratorId
#line 356 "parser.y"
                                 { CurrentSemanticValue.name = ValueStack[ValueStack.Depth-1].name; }
#line default
        break;
      case 81: // VariableDeclaratorId -> IDENTIFIER, Dims_Opt
#line 360 "parser.y"
                                { CurrentSemanticValue.name = ValueStack[ValueStack.Depth-2].name; }
#line default
        break;
      case 82: // Statement -> StatementWithoutTrailingSubstatement
#line 364 "parser.y"
                                             {CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 83: // StatementWithoutTrailingSubstatement -> ExpressionStatement
#line 369 "parser.y"
                                 { CurrentSemanticValue.stmt = ValueStack[ValueStack.Depth-1].stmt; }
#line default
        break;
      case 84: // ExpressionStatement -> StatementExpression, ';'
#line 373 "parser.y"
                                   { CurrentSemanticValue.stmt = new ExpressionStatement(ValueStack[ValueStack.Depth-2].expr); }
#line default
        break;
      case 85: // StatementExpression -> Assignment
#line 377 "parser.y"
                         { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 86: // Assignment -> LeftHandSide, AssignmentOperator, Expression
#line 384 "parser.y"
                                                 { CurrentSemanticValue.expr = new AssignmentExpression(ValueStack[ValueStack.Depth-3].expr, ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 87: // LeftHandSide -> ExpressionName
#line 388 "parser.y"
                            { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 88: // ExpressionName -> IDENTIFIER
#line 392 "parser.y"
                         { CurrentSemanticValue.expr = new VariableExpression(ValueStack[ValueStack.Depth-1].name);  }
#line default
        break;
      case 90: // AssignmentExpression -> Assignment
#line 400 "parser.y"
                         { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 91: // AssignmentExpression -> ConditionalExpression
#line 401 "parser.y"
                                  { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 92: // Primary -> PrimaryNoNewArray
#line 405 "parser.y"
                               { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 93: // PrimaryNoNewArray -> Literal
#line 409 "parser.y"
                       { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 94: // Literal -> IntegerLiteral
#line 413 "parser.y"
                            { CurrentSemanticValue.expr = new IntegerLiteralExpression(ValueStack[ValueStack.Depth-1].num); }
#line default
        break;
      case 95: // Literal -> BooleanLiteral
#line 414 "parser.y"
                            { CurrentSemanticValue.expr = new BooleanLiteralExpression((bool)ValueStack[ValueStack.Depth-1].boolval);}
#line default
        break;
      case 96: // Literal -> FloatingPointLiteral
#line 415 "parser.y"
                                 { CurrentSemanticValue.expr = new FloatingPointLiteralExpression(ValueStack[ValueStack.Depth-1].floatnum);}
#line default
        break;
      case 97: // Expression -> LambdaExpression
#line 421 "parser.y"
                              { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 98: // Expression -> AssignmentExpression
#line 422 "parser.y"
                                 { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 99: // LambdaExpression -> LambdaParameters, ARROW, LambdaBody
#line 426 "parser.y"
                                           { }
#line default
        break;
      case 100: // LambdaParameters -> /* empty */
#line 430 "parser.y"
                          { }
#line default
        break;
      case 101: // LambdaBody -> /* empty */
#line 434 "parser.y"
                          { }
#line default
        break;
      case 102: // ConditionalExpression -> ConditionalOrExpression
#line 438 "parser.y"
                                       { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 103: // ConditionalOrExpression -> ConditionalAndExpression
#line 444 "parser.y"
                                      { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 104: // ConditionalOrExpression -> ConditionalOrExpression, LOGICAL_OR, 
                //                            ConditionalAndExpression
#line 445 "parser.y"
                                                                { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, "||", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 105: // ConditionalAndExpression -> InclusiveOrExpression
#line 449 "parser.y"
                                    { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 106: // ConditionalAndExpression -> ConditionalAndExpression, LOGICAL_AND, 
                //                             InclusiveOrExpression
#line 450 "parser.y"
                                                               { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, "&&", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 107: // InclusiveOrExpression -> ExclusiveOrExpression
#line 454 "parser.y"
                                    { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 108: // ExclusiveOrExpression -> AndExpression
#line 459 "parser.y"
                              { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 109: // AndExpression -> EqualityExpression
#line 464 "parser.y"
                                 { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 110: // EqualityExpression -> RelationalExpression
#line 469 "parser.y"
                                   { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 111: // RelationalExpression -> ShiftExpression
#line 474 "parser.y"
                               { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 112: // ShiftExpression -> AdditiveExpression
#line 479 "parser.y"
                                 { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 113: // AdditiveExpression -> MultiplicativeExpression
#line 484 "parser.y"
                                     { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 114: // AdditiveExpression -> AdditiveExpression, '+', MultiplicativeExpression
#line 485 "parser.y"
                                                      { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, "+", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 115: // AdditiveExpression -> AdditiveExpression, '-', MultiplicativeExpression
#line 486 "parser.y"
                                                      { CurrentSemanticValue.expr = new BinaryExpression(ValueStack[ValueStack.Depth-3].expr, "-", ValueStack[ValueStack.Depth-1].expr); }
#line default
        break;
      case 116: // MultiplicativeExpression -> UnaryExpression
#line 490 "parser.y"
                              { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 117: // UnaryExpression -> PostfixExpression
#line 495 "parser.y"
                                { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 118: // PostfixExpression -> Primary
#line 500 "parser.y"
                        { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
      case 119: // PostfixExpression -> ExpressionName
#line 501 "parser.y"
                             { CurrentSemanticValue.expr = ValueStack[ValueStack.Depth-1].expr; }
#line default
        break;
    }
#pragma warning restore 162, 1522
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliases != null && aliases.ContainsKey(terminal))
        return aliases[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }

#line 506 "parser.y"

public Parser(Scanner scanner) : base(scanner)
{
}
#line default
}
}
